export type CategoryIconDefinition={key:string;label:string;keywords:readonly string[]};

export const CATEGORY_ICON_REGISTRY=[
  {key:'coffee',label:'Καφές',keywords:['coffee','cafe','espresso','καφες']},
  {key:'dining',label:'Φαγητό',keywords:['food','restaurant','dining','φαγητο','εστιαση']},
  {key:'groceries',label:'Σούπερ μάρκετ',keywords:['groceries','supermarket','market','σουπερ μαρκετ']},
  {key:'bakery',label:'Φούρνος',keywords:['bakery','bread','φουρνος','ψωμι']},
  {key:'takeaway',label:'Delivery',keywords:['delivery','takeaway','efood','wolt']},
  {key:'clothing',label:'Ρούχα',keywords:['clothes','fashion','ρουχα','ενδυση']},
  {key:'shoes',label:'Παπούτσια',keywords:['shoes','sneakers','παπουτσια']},
  {key:'shopping',label:'Αγορές',keywords:['shopping','shop','αγορες']},
  {key:'gift',label:'Δώρα',keywords:['gift','present','δωρα']},
  {key:'electronics',label:'Ηλεκτρονικά',keywords:['electronics','devices','ηλεκτρονικα']},
  {key:'computer',label:'Υπολογιστές',keywords:['computer','pc','laptop','υπολογιστης']},
  {key:'phone',label:'Κινητό',keywords:['phone','mobile','smartphone','κινητο']},
  {key:'gaming',label:'Gaming',keywords:['gaming','games','playstation','xbox','steam']},
  {key:'fuel',label:'Καύσιμα',keywords:['fuel','gas','petrol','καυσιμα','βενζινη']},
  {key:'parking',label:'Parking',keywords:['parking','σταθμευση']},
  {key:'car',label:'Αυτοκίνητο',keywords:['car','vehicle','αυτοκινητο','οχημα']},
  {key:'motorcycle',label:'Μηχανή',keywords:['motorcycle','scooter','μηχανη']},
  {key:'public-transport',label:'ΜΜΜ',keywords:['bus','metro','train','transport','λεωφορειο','μετρο']},
  {key:'taxi',label:'Ταξί / Ride',keywords:['taxi','uber','freely','ταξι']},
  {key:'service',label:'Service / Επισκευή',keywords:['service','repair','wrench','επισκευη','συνεργειο']},
  {key:'insurance',label:'Ασφάλιση',keywords:['insurance','ασφαλιση']},
  {key:'home',label:'Σπίτι',keywords:['home','house','σπιτι']},
  {key:'rent',label:'Ενοίκιο',keywords:['rent','lease','ενοικιο']},
  {key:'furniture',label:'Έπιπλα',keywords:['furniture','sofa','επιπλα']},
  {key:'maintenance',label:'Συντήρηση σπιτιού',keywords:['maintenance','repair','home repair','συντηρηση']},
  {key:'electricity',label:'Ρεύμα',keywords:['electricity','power','ρευμα','δεη']},
  {key:'water',label:'Νερό',keywords:['water','νερο','ευδαπ']},
  {key:'heating',label:'Θέρμανση',keywords:['heating','gas','θερμανση']},
  {key:'internet',label:'Internet',keywords:['internet','wifi','fiber']},
  {key:'telephone',label:'Τηλεφωνία',keywords:['telephone','mobile plan','τηλεφωνια']},
  {key:'subscription',label:'Συνδρομή',keywords:['subscription','monthly','annual','συνδρομη']},
  {key:'streaming',label:'Streaming',keywords:['streaming','netflix','disney','youtube']},
  {key:'music',label:'Μουσική',keywords:['music','spotify','μουσικη']},
  {key:'cinema',label:'Σινεμά',keywords:['cinema','movie','σινεμα','ταινια']},
  {key:'entertainment',label:'Ψυχαγωγία',keywords:['entertainment','fun','ψυχαγωγια']},
  {key:'sport',label:'Αθλητισμός',keywords:['sport','sports','athletics','αθλητισμος']},
  {key:'gym',label:'Γυμναστήριο',keywords:['gym','fitness','γυμναστηριο']},
  {key:'health',label:'Υγεία',keywords:['health','medical','υγεια']},
  {key:'doctor',label:'Γιατρός',keywords:['doctor','clinic','γιατρος','ιατρος']},
  {key:'dentist',label:'Οδοντίατρος',keywords:['dentist','dental','οδοντιατρος']},
  {key:'pharmacy',label:'Φαρμακείο',keywords:['pharmacy','medicine','φαρμακειο']},
  {key:'hospital',label:'Νοσοκομείο',keywords:['hospital','νοσοκομειο']},
  {key:'education',label:'Εκπαίδευση',keywords:['education','school','εκπαιδευση']},
  {key:'books',label:'Βιβλία',keywords:['books','book','βιβλια']},
  {key:'course',label:'Μαθήματα',keywords:['course','lesson','μαθηματα']},
  {key:'travel',label:'Ταξίδι',keywords:['travel','trip','ταξιδι']},
  {key:'flight',label:'Πτήση',keywords:['flight','airplane','πτηση','αεροπορικα']},
  {key:'hotel',label:'Ξενοδοχείο',keywords:['hotel','booking','ξενοδοχειο']},
  {key:'ferry',label:'Πλοίο',keywords:['ferry','ship','πλοιο']},
  {key:'holiday',label:'Διακοπές',keywords:['holiday','vacation','διακοπες']},
  {key:'pet',label:'Κατοικίδια',keywords:['pet','dog','cat','κατοικιδια']},
  {key:'child',label:'Παιδί',keywords:['child','kids','baby','παιδι']},
  {key:'family',label:'Οικογένεια',keywords:['family','οικογενεια']},
  {key:'personal-care',label:'Προσωπική φροντίδα',keywords:['personal care','beauty','φροντιδα']},
  {key:'barber',label:'Κομμωτήριο',keywords:['barber','haircut','κομμωτηριο','κουρεμα']},
  {key:'cosmetics',label:'Καλλυντικά',keywords:['cosmetics','beauty','καλλυντικα']},
  {key:'tobacco',label:'Καπνός',keywords:['tobacco','cigarettes','καπνος','τσιγαρα']},
  {key:'kiosk',label:'Ψιλικά',keywords:['kiosk','convenience','ψιλικα','περιπτερο']},
  {key:'tax',label:'Φόροι',keywords:['tax','taxes','φορος','φοροι','ααδε']},
  {key:'government',label:'Δημόσιο',keywords:['government','public','δημοσιο']},
  {key:'bank-fee',label:'Τραπεζικά έξοδα',keywords:['bank fee','commission','τραπεζικα','προμηθεια']},
  {key:'cash',label:'Μετρητά',keywords:['cash','μετρητα']},
  {key:'card',label:'Κάρτα',keywords:['card','credit card','debit card','καρτα']},
  {key:'loan',label:'Δάνειο',keywords:['loan','debt','δανειο']},
  {key:'installment',label:'Δόση',keywords:['installment','installments','δοση','δοσεις']},
  {key:'saving',label:'Αποταμίευση',keywords:['saving','savings','αποταμιευση']},
  {key:'investment',label:'Επένδυση',keywords:['investment','stocks','επενδυση']},
  {key:'salary',label:'Μισθός',keywords:['salary','payroll','μισθος']},
  {key:'bonus',label:'Bonus',keywords:['bonus','reward','μπonus']},
  {key:'income',label:'Έσοδο',keywords:['income','revenue','εσοδο']},
  {key:'refund',label:'Επιστροφή',keywords:['refund','reimbursement','επιστροφη']},
  {key:'sale',label:'Πώληση',keywords:['sale','sold','πωληση']},
  {key:'freelance',label:'Freelance',keywords:['freelance','project','εργασια']},
  {key:'business',label:'Εργασία / Business',keywords:['business','work','briefcase','δουλεια','εργασια']},
  {key:'charity',label:'Δωρεά',keywords:['charity','donation','δωρεα']},
  {key:'celebration',label:'Γιορτή',keywords:['celebration','party','birthday','γιορτη']},
  {key:'calendar',label:'Ημερολόγιο',keywords:['calendar','date','ημερολογιο']},
  {key:'receipt',label:'Απόδειξη',keywords:['receipt','invoice','αποδειξη']},
  {key:'wallet',label:'Πορτοφόλι',keywords:['wallet','πορτοφολι']},
  {key:'transfer',label:'Μεταφορά',keywords:['transfer','move money','μεταφορα']},
  {key:'reconciliation',label:'Διόρθωση',keywords:['reconciliation','adjustment','διορθωση']},
  {key:'other',label:'Άλλο',keywords:['other','misc','αλλο']},
] as const satisfies readonly CategoryIconDefinition[];

export type CategoryIconKey=(typeof CATEGORY_ICON_REGISTRY)[number]['key'];

function normalize(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('el-GR').replace(/[^a-z0-9α-ω]+/g,' ').trim()}

export function categoryIconByKey(key:string){return CATEGORY_ICON_REGISTRY.find(item=>item.key===key)??null}

export function searchCategoryIcons(query:string,limit=40){
  const needle=normalize(query);
  const rows=needle?CATEGORY_ICON_REGISTRY.filter(item=>normalize([item.key,item.label,...item.keywords].join(' ')).includes(needle)):CATEGORY_ICON_REGISTRY;
  return rows.slice(0,Math.max(1,limit));
}
