import { describe, expect, it } from 'vitest';
import { archiveCardRecord, archivedCardMatch, canPermanentlyDeleteCreditCard, cardBanks, cardsForBank, creditCards, creditDebtForCard, creditEventsForCard, creditLimitForCard, historicalCardLabel, legacyCreditOwnerId, primaryCreditCard, restoreCard, withCardProfileDeleted } from '../src/lib/cards.js';
import { migrateProductData } from '../src/lib/productMigration.js';
import type { FinanceData, FinanceEvent } from '../src/types.js';

function fixture():FinanceData{return {app:'RheomIQ',schemaVersion:3,updatedAt:'2026-08-17T00:00:00Z',seed:{accounts:[],months:[],transactions:[],snapshots:[],recurring:[],subscriptions:[],loans:[],lending:[],stats:{}},state:{customTransactions:[],overrides:{},deleted:[],recurringCustom:[],recurringOverrides:{},loanExtra:{},loanOverrides:{},customLoans:[],lendingCustom:[],settings:{excludedFromAvailable:[],accountNames:{},expenseCategories:['Άλλο'],incomeCategories:['Μισθός'],customPresets:[],pinnedPresets:[],defaultExpenseAccount:'cash',defaultIncomeAccount:'cash',defaultLoanAccount:'cash',creditLimit:500},cardBanks:[{id:'custom-bank',name:'CUSTOM',order:60,custom:true}],cards:[{id:'c1',bankId:'piraeus',nickname:'Debit',kind:'debit',network:'visa',formFactor:'physical',designId:'piraeus-yellow',last4:'1234',active:true,createdAt:'2026-08-01T00:00:00Z',updatedAt:'2026-08-01T00:00:00Z'},{id:'cc1',bankId:'piraeus',nickname:'Credit One',kind:'credit',network:'visa',formFactor:'physical',designId:'piraeus-green',last4:'5678',vaultRef:'cc1',creditLimit:1000,active:true,createdAt:'2026-08-02T00:00:00Z',updatedAt:'2026-08-02T00:00:00Z'},{id:'cc2',bankId:'piraeus',nickname:'Credit Two',kind:'credit',network:'visa',formFactor:'physical',designId:'piraeus-gold',last4:'9999',vaultRef:'cc2',creditLimit:2000,active:true,createdAt:'2026-08-05T00:00:00Z',updatedAt:'2026-08-05T00:00:00Z'}],deletedCards:[],events:[{id:'old-purchase',date:'2026-08-03',kind:'card_purchase',amount:25,note:'Legacy',legs:[{accountId:'credit-card',amount:-25}],source:'user',createdAt:'2026-08-03T00:00:00Z',updatedAt:'2026-08-03T00:00:00Z'},{id:'linked-payment',date:'2026-08-04',kind:'card_payment',amount:10,note:'Payment',fromAccountId:'piraeus-payroll',cardId:'cc1',legs:[{accountId:'piraeus-payroll',amount:-10},{accountId:'credit-card',amount:10}],source:'user',createdAt:'2026-08-04T00:00:00Z',updatedAt:'2026-08-04T00:00:00Z'},{id:'cc2-purchase',date:'2026-08-06',kind:'card_purchase',amount:80,note:'Second card purchase',cardId:'cc2',legs:[{accountId:'credit-card',amount:-80}],source:'user',createdAt:'2026-08-06T00:00:00Z',updatedAt:'2026-08-06T00:00:00Z'},{id:'cc2-payment',date:'2026-08-07',kind:'card_payment',amount:30,note:'Second card payment',fromAccountId:'piraeus-payroll',cardId:'cc2',legs:[{accountId:'piraeus-payroll',amount:-30},{accountId:'credit-card',amount:30}],source:'user',createdAt:'2026-08-07T00:00:00Z',updatedAt:'2026-08-07T00:00:00Z'}]}} as FinanceData}

function payment(id:string,cardId:string,amount:number,date='2026-08-08'):FinanceEvent{return {id,date,kind:'card_payment',amount,note:'Settlement',fromAccountId:'piraeus-payroll',cardId,legs:[{accountId:'piraeus-payroll',amount:-amount},{accountId:'credit-card',amount}],source:'user',createdAt:`${date}T00:00:00Z`,updatedAt:`${date}T00:00:00Z`}}

describe('Cards metadata',()=>{
 it('keeps the approved bank order, then adds shared providers before custom banks',()=>{expect(cardBanks(fixture()).map(bank=>bank.id)).toEqual(['piraeus','revolut','alpha','payzy','viva','national','eurobank','paypal','custom-bank'])});
 it('keeps credit cards out of the generic Cards page selectors',()=>{const data=fixture();expect(cardsForBank(data,'piraeus').map(card=>card.id)).toEqual(['c1']);expect(creditCards(data).map(card=>card.id)).toEqual(['cc1','cc2'])});
 it('normalizes credit-card presentation to the approved next-cycle boundary without rewriting stored metadata',()=>{const data=fixture();data.state.cards=data.state.cards?.map(card=>card.id==='cc1'?{...card,statementBoundaryRule:'include-closing-day'}:card);expect(creditCards(data).map(card=>card.statementBoundaryRule)).toEqual(['next-cycle','next-cycle']);expect(data.state.cards?.find(card=>card.id==='cc1')?.statementBoundaryRule).toBe('include-closing-day');expect(data.state.cards?.find(card=>card.id==='cc2')?.statementBoundaryRule).toBeUndefined()});
 it('stores no full secret field in card metadata',()=>{const cards=cardsForBank(fixture(),'piraeus');expect(cards[0]).not.toHaveProperty('pan');expect(cards[0]).not.toHaveProperty('cvv');expect(cards[0]).not.toHaveProperty('expiry')});
 it('soft-archives and restores the exact same card id and vault reference',()=>{const original=primaryCreditCard(fixture())!;const archived=archiveCardRecord(original,'2026-08-10T00:00:00Z');expect(archived).toMatchObject({id:'cc1',active:false,archivedAt:'2026-08-10T00:00:00Z',vaultRef:'cc1'});const restored=restoreCard(archived,'2026-08-11T00:00:00Z');expect(restored).toMatchObject({id:'cc1',active:true,vaultRef:'cc1'});expect(restored).not.toHaveProperty('archivedAt')});
 it('automatically reuses an archived record only when the last4 match is explicit',()=>{const data=fixture();data.state.cards=data.state.cards?.map(card=>card.id==='cc1'?archiveCardRecord(card):card);expect(archivedCardMatch(data,{bankId:'piraeus',kind:'credit'})).toBeUndefined();expect(archivedCardMatch(data,{bankId:'piraeus',kind:'credit',last4:'0000'})).toBeUndefined();expect(archivedCardMatch(data,{bankId:'piraeus',kind:'credit',last4:'5678'})?.id).toBe('cc1')});
 it('assigns pre-cardId legacy events only to the deterministic historical credit identity',()=>{expect(primaryCreditCard(fixture())?.id).toBe('cc1');expect(legacyCreditOwnerId(fixture())).toBe('cc1');expect(creditEventsForCard(fixture(),'cc1').map(event=>event.id)).toEqual(['old-purchase','linked-payment']);expect(creditEventsForCard(fixture(),'cc2').map(event=>event.id)).toEqual(['cc2-purchase','cc2-payment'])});
 it('computes independent debt and limits per credit card',()=>{const data=fixture();expect(creditDebtForCard(data,'cc1','2026-08-31')).toBe(15);expect(creditDebtForCard(data,'cc2','2026-08-31')).toBe(50);expect(creditLimitForCard(data,data.state.cards!.find(card=>card.id==='cc1')!)).toBe(1000);expect(creditLimitForCard(data,{...data.state.cards!.find(card=>card.id==='cc2')!,creditLimit:undefined})).toBe(500)});
 it('requires archive before total credit deletion even after full repayment',()=>{const data=fixture();data.state.events=[...(data.state.events??[]),payment('cc1-final','cc1',15)];const card=data.state.cards!.find(item=>item.id==='cc1')!;expect(canPermanentlyDeleteCreditCard(data,'cc1','2026-08-31')).toBe(false);expect(()=>withCardProfileDeleted(data,card,'2026-08-31T12:00:00Z','2026-08-31')).toThrow('CREDIT_CARD_MUST_BE_ARCHIVED')});
 it('blocks archived total credit deletion while debt remains',()=>{const data=fixture();const card=data.state.cards!.find(item=>item.id==='cc1')!;const archived=archiveCardRecord(card,'2026-08-30T12:00:00Z');data.state.cards=data.state.cards!.map(item=>item.id===card.id?archived:item);expect(canPermanentlyDeleteCreditCard(data,'cc1','2026-08-31')).toBe(false);expect(()=>withCardProfileDeleted(data,archived,'2026-08-31T12:00:00Z','2026-08-31')).toThrow('CREDIT_CARD_HAS_OUTSTANDING_BALANCE')});
 it('deletes an archived fully paid credit profile while preserving history through a neutral tombstone',()=>{const data=fixture();data.state.events=[...(data.state.events??[]),payment('cc1-final','cc1',15)];const card=data.state.cards!.find(item=>item.id==='cc1')!;const archived=archiveCardRecord(card,'2026-08-30T12:00:00Z');data.state.cards=data.state.cards!.map(item=>item.id===card.id?archived:item);expect(canPermanentlyDeleteCreditCard(data,'cc1','2026-08-31')).toBe(true);const deleted=withCardProfileDeleted(data,archived,'2026-08-31T12:00:00Z','2026-08-31');expect(deleted.state.cards?.some(item=>item.id==='cc1')).toBe(false);expect(deleted.state.deletedCards).toEqual([{id:'cc1',kind:'credit',createdAt:'2026-08-02T00:00:00Z',deletedAt:'2026-08-31T12:00:00Z'}]);expect(legacyCreditOwnerId(deleted)).toBe('cc1');expect(creditEventsForCard(deleted,'cc1').map(event=>event.id)).toEqual(['old-purchase','linked-payment','cc1-final']);expect(historicalCardLabel(deleted,'cc1')).toBe('Διαγραμμένη κάρτα')});
 it('permanently deletes debit/prepaid profiles without creating finance tombstones',()=>{const data=fixture();const card=data.state.cards!.find(item=>item.id==='c1')!;const deleted=withCardProfileDeleted(data,card,'2026-08-31T12:00:00Z','2026-08-31');expect(deleted.state.cards?.some(item=>item.id==='c1')).toBe(false);expect(deleted.state.deletedCards).toEqual([])});
 it('preserves card banks, cards and deleted-card references through the product migration boundary',()=>{const input=fixture();input.state.deletedCards=[{id:'old-credit',kind:'credit',createdAt:'2025-01-01T00:00:00Z',deletedAt:'2026-08-01T00:00:00Z'}];const migrated=migrateProductData(input);expect(migrated.state.cardBanks?.[0]?.id).toBe('custom-bank');expect(migrated.state.cards?.map(card=>card.id)).toEqual(['c1','cc1','cc2']);expect(migrated.state.deletedCards?.[0]?.id).toBe('old-credit')});
});
