import { describe, expect, it } from 'vitest';
import { archiveCardRecord, archivedCardMatch, cardBanks, cardsForBank, creditEventsForCard, primaryCreditCard, restoreCard } from '../src/lib/cards.js';
import { migrateProductData } from '../src/lib/productMigration.js';
import type { FinanceData } from '../src/types.js';

function fixture():FinanceData{return {app:'RheomIQ',schemaVersion:3,updatedAt:'2026-08-17T00:00:00Z',seed:{accounts:[],months:[],transactions:[],snapshots:[],recurring:[],subscriptions:[],loans:[],lending:[],stats:{}},state:{customTransactions:[],overrides:{},deleted:[],recurringCustom:[],recurringOverrides:{},loanExtra:{},loanOverrides:{},customLoans:[],lendingCustom:[],settings:{excludedFromAvailable:[],accountNames:{},expenseCategories:['Άλλο'],incomeCategories:['Μισθός'],customPresets:[],pinnedPresets:[],defaultExpenseAccount:'cash',defaultIncomeAccount:'cash',defaultLoanAccount:'cash'},cardBanks:[{id:'custom-bank',name:'CUSTOM',order:60,custom:true}],cards:[{id:'c1',bankId:'piraeus',nickname:'Debit',kind:'debit',network:'visa',formFactor:'physical',designId:'piraeus-yellow',last4:'1234',active:true,createdAt:'2026-08-01T00:00:00Z',updatedAt:'2026-08-01T00:00:00Z'},{id:'cc1',bankId:'piraeus',nickname:'Credit',kind:'credit',network:'visa',formFactor:'physical',designId:'piraeus-green',last4:'5678',vaultRef:'cc1',active:true,createdAt:'2026-08-02T00:00:00Z',updatedAt:'2026-08-02T00:00:00Z'}],events:[{id:'old-purchase',date:'2026-08-03',kind:'card_purchase',amount:25,note:'Legacy',legs:[{accountId:'credit-card',amount:-25}],source:'user',createdAt:'2026-08-03T00:00:00Z',updatedAt:'2026-08-03T00:00:00Z'},{id:'linked-payment',date:'2026-08-04',kind:'card_payment',amount:10,note:'Payment',fromAccountId:'piraeus-payroll',cardId:'cc1',legs:[{accountId:'piraeus-payroll',amount:-10},{accountId:'credit-card',amount:10}],source:'user',createdAt:'2026-08-04T00:00:00Z',updatedAt:'2026-08-04T00:00:00Z'}]}} as FinanceData}

describe('Cards metadata',()=>{
 it('keeps the required bank order before custom banks',()=>{expect(cardBanks(fixture()).map(bank=>bank.id)).toEqual(['piraeus','revolut','alpha','payzy','viva','custom-bank'])});
 it('shows active cards only and stores no full secret field in metadata',()=>{const cards=cardsForBank(fixture(),'piraeus');expect(cards.map(card=>card.id)).toEqual(['c1','cc1']);expect(cards[0]).not.toHaveProperty('pan');expect(cards[0]).not.toHaveProperty('cvv');expect(cards[0]).not.toHaveProperty('expiry')});
 it('soft-archives and restores the exact same card id and vault reference',()=>{const original=primaryCreditCard(fixture())!;const archived=archiveCardRecord(original,'2026-08-10T00:00:00Z');expect(archived).toMatchObject({id:'cc1',active:false,archivedAt:'2026-08-10T00:00:00Z',vaultRef:'cc1'});const restored=restoreCard(archived,'2026-08-11T00:00:00Z');expect(restored).toMatchObject({id:'cc1',active:true,vaultRef:'cc1'});expect(restored).not.toHaveProperty('archivedAt')});
 it('automatically reuses an archived record only when the last4 match is explicit',()=>{const data=fixture();data.state.cards=data.state.cards?.map(card=>card.id==='cc1'?archiveCardRecord(card):card);expect(archivedCardMatch(data,{bankId:'piraeus',kind:'credit'})).toBeUndefined();expect(archivedCardMatch(data,{bankId:'piraeus',kind:'credit',last4:'9999'})).toBeUndefined();expect(archivedCardMatch(data,{bankId:'piraeus',kind:'credit',last4:'5678'})?.id).toBe('cc1')});
 it('assigns pre-cardId legacy credit events to the historical primary card and keeps linked events',()=>{expect(creditEventsForCard(fixture(),'cc1').map(event=>event.id)).toEqual(['old-purchase','linked-payment'])});
 it('preserves card banks and cards through the product migration boundary',()=>{const input=fixture();const migrated=migrateProductData(input);expect(migrated.state.cardBanks?.[0]?.id).toBe('custom-bank');expect(migrated.state.cards?.map(card=>card.id)).toEqual(['c1','cc1'])});
});