import { describe, expect, it } from 'vitest';
import { accountBalances, createEvent, flowImpactLegacy, migrateData, monthlyFlow, netWorth, suggestSplitParts } from '../src/lib/domain.js';
import type { FinanceData, LegacyTransaction } from '../src/types.js';

const minimal = (): FinanceData => migrateData({
  app:'MBAI Finance',schemaVersion:2,updatedAt:'2026-08-17T00:00:00Z',
  seed:{accounts:[{id:'cash',name:'Μετρητά',kind:'cash'},{id:'piraeus-payroll',name:'Μισθοδοσίας',kind:'bank'},{id:'piraeus-savings',name:'Ταμιευτηρίου',kind:'savings',excludeFromAvailable:true}],months:['2026-08'],transactions:[],snapshots:[{date:'2026-08-17',balances:{cash:100,'piraeus-payroll':1000,'piraeus-savings':500}}],recurring:[],subscriptions:[],loans:[],lending:[],stats:{}},
  state:{customTransactions:[],overrides:{},deleted:[],recurringCustom:[],recurringOverrides:{},loanExtra:{},loanOverrides:{},customLoans:[],lendingCustom:[],settings:{excludedFromAvailable:['piraeus-savings'],accountNames:{},expenseCategories:['Άλλο','Φαγητό'],incomeCategories:['Μισθός'],customPresets:[],pinnedPresets:[],defaultExpenseAccount:'piraeus-payroll',defaultIncomeAccount:'piraeus-payroll',defaultLoanAccount:'piraeus-payroll'}}
} as FinanceData);

describe('RheomIQ ledger invariants',()=>{
  it('migrates schema v2 without inventing browser storage state',()=>{const d=minimal();expect(d.schemaVersion).toBe(3);expect(d.app).toBe('RheomIQ');expect(d.state.events).toEqual([]);expect(d.state.reviewDecisions).toEqual({})});
  it('cash-offset saving never touches cash and preserves net worth',()=>{const d=minimal();const before=netWorth(d,'2026-08-17');const e=createEvent({kind:'saving_cash_offset',date:'2026-08-17',amount:80,note:'saving',fromAccountId:'piraeus-payroll',toAccountId:'piraeus-savings'});d.state.events=[e];const b=accountBalances(d,'2026-08-17');expect(b.cash).toBe(100);expect(b['piraeus-payroll']).toBe(920);expect(b['piraeus-savings']).toBe(580);expect(netWorth(d,'2026-08-17')).toBe(before)});
  it('withdrawal is a zero-sum transfer',()=>{const e=createEvent({kind:'withdrawal',date:'2026-08-17',amount:50,note:'cash',fromAccountId:'piraeus-payroll',toAccountId:'cash'});expect(e.legs.reduce((s,l)=>s+l.amount,0)).toBe(0)});
  it('credit purchase counts expense once while payment has zero cashflow impact',()=>{const d=minimal();const purchase=createEvent({kind:'card_purchase',date:'2026-08-17',amount:40,note:'card',category:'Άλλο'});const payment=createEvent({kind:'card_payment',date:'2026-08-17',amount:40,note:'pay',fromAccountId:'piraeus-payroll'});d.state.events=[purchase,payment];expect(monthlyFlow(d,'2026-08').expense).toBe(40);expect(accountBalances(d,'2026-08-17')['credit-card']).toBe(0)});
  it('lending preserves net worth through receivable asset',()=>{const d=minimal();const before=netWorth(d,'2026-08-17');d.state.events=[createEvent({kind:'lending',date:'2026-08-17',amount:100,note:'lend',accountId:'piraeus-payroll',person:'Χρήστος'})];expect(netWorth(d,'2026-08-17')).toBe(before)});
  it('rejects unbalanced split',()=>{expect(()=>createEvent({kind:'split',date:'2026-08-17',amount:10,note:'bad',accountId:'cash',parts:[{id:'1',label:'x',category:'Άλλο',amount:9}]})).toThrow(/δεν ισούνται/)});
  it('review suggestions do not alter legacy reporting before confirmation',()=>{const d=minimal();const tx:LegacyTransaction={id:'x',date:'2026-08-17',type:'income',accountId:'piraeus-savings',amount:20,note:'Pay&Save',category:'Έσοδα'};d.seed.transactions=[tx];expect(flowImpactLegacy(d,tx).income).toBe(20);d.state.reviewDecisions={x:{status:'confirmed',semanticKind:'saving_cash_offset',decidedAt:new Date().toISOString()}};const f=flowImpactLegacy(d,tx);expect(f.income).toBe(0);expect(f.saving).toBe(20)});
  it('kept review decision preserves original transaction meaning',()=>{const d=minimal();const tx:LegacyTransaction={id:'x',date:'2026-08-17',type:'income',accountId:'cash',amount:30,note:'IRIS',category:'Έσοδα'};d.state.reviewDecisions={x:{status:'kept',decidedAt:new Date().toISOString()}};expect(flowImpactLegacy(d,tx).income).toBe(30)});
  it('parses mixed comments into editable review parts',()=>{const parts=suggestSplitParts('ΕΠΙΔΟΜΑ ΑΔΕΙΑΣ: 450,02€\nΕπιστροφή: 100€');expect(parts).toHaveLength(2);expect(parts[0].kind).toBe('income');expect(parts[1].kind).toBe('refund');expect(parts.reduce((s,p)=>s+p.amount,0)).toBeCloseTo(550.02)});
});
