import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const app=readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8');const qa=readFileSync(new URL('../src/qa.tsx',import.meta.url),'utf8');const dashboard=readFileSync(new URL('../src/pages/DashboardPage.tsx',import.meta.url),'utf8');const skeleton=readFileSync(new URL('../src/components/AppSkeleton.tsx',import.meta.url),'utf8');const finance=readFileSync(new URL('../src/hooks/useFinance.ts',import.meta.url),'utf8');const history=readFileSync(new URL('../src/lib/changeHistory.ts',import.meta.url),'utf8');const shell=readFileSync(new URL('../src/components/AppShell.tsx',import.meta.url),'utf8');const styles=readFileSync(new URL('../src/styles/part41.css',import.meta.url),'utf8');const reconciliationQa=readFileSync(new URL('../scripts/final-ux-reconciliation-qa.mjs',import.meta.url),'utf8');const coordinator=readFileSync(new URL('../scripts/run-rendered-qa.mjs',import.meta.url),'utf8');

describe('final UX reconciliation source contracts',()=>{
  it('keeps the agreed Dashboard semantic priority order',()=>{expect(dashboard).toContain("const PRIMARY_ACCOUNTS=['cash','piraeus-payroll','piraeus-savings']");const primary=dashboard.indexOf('data-dashboard-section="primary-accounts"'),other=dashboard.indexOf('data-dashboard-section="other-balances"'),pending=dashboard.indexOf('data-dashboard-section="pending"'),quick=dashboard.indexOf('data-dashboard-section="quick-entry"'),rest=dashboard.indexOf('data-dashboard-section="rest"');expect(primary).toBeGreaterThan(-1);expect(other).toBeGreaterThan(primary);expect(pending).toBeGreaterThan(other);expect(quick).toBeGreaterThan(pending);expect(rest).toBeGreaterThan(quick);expect(styles).toContain('.dashboard-grid{grid-auto-flow:row}')});
  it('measures box-less and viewport geometry inside the rendered browser context',()=>{expect(reconciliationQa).toContain("if(style.display==='contents')");expect(reconciliationQa).toContain('[...node.children].map(child=>child.getBoundingClientRect())');expect(reconciliationQa).toContain('viewportWidth:innerWidth');expect(reconciliationQa).toContain('state.right<=state.viewportWidth+1');expect(reconciliationQa).toContain('mobile visual order follows semantic order')});
  it('keeps the QA workspace on the shared app shortcut authority',()=>{expect(qa).not.toContain("addEventListener('keydown',onKey)");expect(qa).toContain('onCommand={openCommand}')});
  it('exposes privacy-safe session history for changes, undo and redo',()=>{expect(finance).toContain("export const SESSION_HISTORY_EVENT = 'myfinhub-session-change-history'");expect(finance).toContain('export function financeChangeLabel(current:FinanceData,next:FinanceData)');expect(history).toContain('export function describeFinanceChange');expect(history).not.toContain('holderName');expect(history).not.toContain('vaultRef');expect(app).toContain('history={finance.changeHistory}');expect(shell).toContain('aria-label="Ιστορικό αλλαγών"');expect(styles).toContain('min-height:44px')});
  it('keeps rendered QA history semantics aligned for primary change labels',()=>{expect(qa).toContain("import { financeChangeLabel, type ChangeHistoryEntry, type SaveState } from './hooks/useFinance'");expect(qa).toContain('useState<ChangeHistoryEntry[]>([])');expect(reconciliationQa).toContain("state.text.includes('12,34')");expect(reconciliationQa).toContain("!state.text.includes('Final UX QA Expense')")});
  it('keeps the mutation gate save-state ref synchronous with rendered state',()=>{expect(finance).toContain("const setCurrentSaveState=useCallback((next:SaveState)=>{saveStateRef.current=next;setSaveState(next)},[])");expect(finance).not.toContain('useEffect(() => { saveStateRef.current = saveState; }')});
  it('starts initial finance hydration only once under React StrictMode',()=>{expect(finance).toContain('const initialLoadStartedRef=useRef(false)');expect(finance).toContain('if(initialLoadStartedRef.current)return;');expect(finance).toContain('void reload();')});
  it('keeps skeletons route-shaped and Dashboard-shaped in the same priority order',()=>{const primary=skeleton.indexOf('data-skeleton-section="primary-accounts"'),other=skeleton.indexOf('section="other-balances"'),pending=skeleton.indexOf('data-skeleton-section="pending"'),quick=skeleton.indexOf('section="quick-entry"'),rest=skeleton.indexOf('data-skeleton-section="rest"');expect(primary).toBeGreaterThan(-1);expect(other).toBeGreaterThan(primary);expect(pending).toBeGreaterThan(other);expect(quick).toBeGreaterThan(pending);expect(rest).toBeGreaterThan(quick);for(const page of ['reports','transactions','review','savings','cards','credit','loans','lending','recurring','planning','attention','settings'])expect(skeleton).toContain(`page==='${page}'`)});
  it('runs the focused rendered reconciliation before ledger QA in the coordinator',()=>{const reconciliation=coordinator.indexOf("path:'scripts/final-ux-reconciliation-qa.mjs'"),ledger=coordinator.indexOf("path:'scripts/ledger-foundations-qa.mjs'");expect(reconciliation).toBeGreaterThan(-1);expect(ledger).toBeGreaterThan(reconciliation)});
});
