import { describe, expect, it } from 'vitest';
import { createEvent } from '../src/lib/domain.js';
import { lendingHistory, lendingOutstandingFor, lendingRows } from '../src/lib/lending.js';
import type { FinanceData } from '../src/types.js';

function fixture():FinanceData{return {app:'RheomIQ',schemaVersion:3,updatedAt:'2026-08-17T00:00:00.000Z',seed:{accounts:[{id:'cash',name:'Cash',kind:'cash'}],months:[],transactions:[],snapshots:[],recurring:[],subscriptions:[],loans:[],lending:[{person:'Alex',entries:[{date:'2026-01-01',lent:50,repaid:0},{date:'2026-02-01',lent:0,repaid:20}],outstanding:30}],stats:{}},state:{customTransactions:[],overrides:{},deleted:[],recurringCustom:[],recurringOverrides:{},loanExtra:{},loanOverrides:{},customLoans:[],lendingCustom:[],events:[],reviewDecisions:{},settings:{excludedFromAvailable:[],accountNames:{},expenseCategories:['Άλλο'],incomeCategories:['Μισθός'],customPresets:[],pinnedPresets:[],defaultExpenseAccount:'cash',defaultIncomeAccount:'cash',defaultLoanAccount:'cash',motion:'full'}}} as FinanceData}

describe('receivables history',()=>{
 it('combines legacy history with new events and running outstanding',()=>{const data=fixture();const event=createEvent({kind:'lending',date:'2026-03-01',amount:10,note:'Lunch',accountId:'cash',person:'Alex'});data.state.events=[event];expect(lendingRows(data)[0]?.outstanding).toBe(40);const rows=lendingHistory(data).filter(row=>row.person==='Alex');expect(rows.map(row=>row.action)).toEqual(['lent','repaid','lent']);expect(rows[0]?.runningOutstanding).toBe(40);expect(rows[1]?.runningOutstanding).toBe(30);expect(rows[2]?.runningOutstanding).toBe(50)});
 it('does not infer lending from IRIS or cash reimbursement notes',()=>{const data=fixture();const expense=createEvent({kind:'expense',date:'2026-03-02',amount:25,note:'Πλήρωσα εγώ, θα μου τα στείλει με IRIS',accountId:'cash',person:'Nikos'});const repaymentContext=createEvent({kind:'income',date:'2026-03-03',amount:25,note:'IRIS επιστροφή από Νίκο',accountId:'cash',person:'Nikos'});data.state.events=[expense,repaymentContext];expect(lendingRows(data)).toHaveLength(1);expect(lendingRows(data)[0]?.person).toBe('Alex');expect(lendingRows(data)[0]?.outstanding).toBe(30);expect(lendingHistory(data).some(row=>row.person==='Nikos')).toBe(false)});
 it('skips malformed legacy rows instead of crashing the Lending workspace',()=>{const data=fixture() as unknown as Record<string,any>;data.seed.lending=[{person:null,entries:null,outstanding:'NaN'},{person:42,entries:[],outstanding:10},{person:'  Alex  ',entries:[{date:null,lent:100,repaid:0},{date:'bad-date',lent:50,repaid:0},{date:'2026-04-01',lent:'oops',repaid:0},{date:'2026-04-02',lent:15,repaid:0}],outstanding:15},{person:'Broken entries',entries:{date:'2026-01-01'},outstanding:5}];expect(()=>lendingRows(data as FinanceData)).not.toThrow();expect(()=>lendingHistory(data as FinanceData)).not.toThrow();expect(lendingRows(data as FinanceData).map(row=>row.person)).toEqual(['Alex','Broken entries']);expect(lendingHistory(data as FinanceData)).toEqual([expect.objectContaining({person:'Alex',date:'2026-04-02',action:'lent',amount:15,runningOutstanding:15})]);expect(lendingOutstandingFor(data as FinanceData,'  Alex  ')).toBe(15)});
 it('keeps minimal summary events while excluding malformed rows from dated history',()=>{const data=fixture() as unknown as Record<string,any>;data.seed.lending=[];data.state.events=[{id:'bad-person',date:'2026-05-01',kind:'lending',amount:10,person:{name:'Alex'},receivableDelta:10},{id:'bad-date',date:null,kind:'lending',amount:20,person:'Alex',receivableDelta:20},{id:'bad-amount',date:'2026-05-02',kind:'lending',amount:'oops',person:'Alex',receivableDelta:'oops'},{id:'valid',date:'2026-05-03',kind:'lending',amount:25,note:'Valid',accountId:'cash',person:'Alex',receivableDelta:25}];expect(lendingRows(data as FinanceData)).toEqual([{person:'Alex',outstanding:45,events:2}]);expect(lendingHistory(data as FinanceData)).toEqual([expect.objectContaining({id:'valid',person:'Alex',date:'2026-05-03',amount:25,runningOutstanding:25})])});
});
