import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const source=readFileSync('scripts/real-stack-browser-e2e.ts','utf8');

describe('actual-browser real-stack source contract',()=>{
  it('uses the real app UI and same-origin API without fetch interception',()=>{
    expect(source).toContain("origin+'/#/transactions'");
    expect(source).toContain("document.querySelector('#login-title')");
    expect(source).toContain("document.querySelector('#mfa-title')");
    expect(source).toContain('[data-global-quick-entry]');
    expect(source).toContain("querySelectorAll('label')");
    expect(source).toContain("wrapper?.querySelector('input,textarea,select')");
    expect(source).toContain("getAttribute('aria-label')===label");
    expect(source).toContain("fetch('/api/data'");
    expect(source).toContain('Page.reload');
    expect(source).not.toContain('globalThis.fetch=');
    expect(source).not.toContain('SUPABASE_ACCESS_TOKEN');
    expect(source).toContain('attempt<=2');
    expect(source).toContain("stdio:['ignore','pipe','pipe']");
    expect(source).toContain('child.exitCode!==null');
    expect(source).toContain('Chromium bootstrap attempt');
    expect(source).toContain('await stopBrowser(child)');
  });
  it('covers modern and legacy durable mutation lifecycles across hard reload',()=>{
    expect(source).toContain('stage modern-create-reload');
    expect(source).toContain('stage modern-edit-delete-undo');
    expect(source).toContain('stage quick-entry-intent-matrix-reload');
    expect(source).toContain("waitApiEventKind(note,kind)");
    expect(source).toContain("['Real Browser Quick Income','income']");
    expect(source).toContain("['Real Browser Quick Transfer','transfer']");
    expect(source).toContain("['Real Browser Quick Withdrawal','withdrawal']");
    expect(source).toContain("['Real Browser Quick Saving','saving_cash_offset']");
    expect(source).toContain("['Real Browser Quick Refund','refund']");
    expect(source).toContain("['Real Browser Quick Reconciliation','reconciliation']");
    expect(source).toContain("['Real Browser Quick Split','split']");
    expect(source).toContain('quick-entry-intents-persisted');
    expect(source).toContain('stage legacy-edit-delete-undo');
    expect(source).toContain('stage credit-purchase-payment-reload');
    expect(source).toContain('Real Browser Credit Purchase');
    expect(source).toContain('waitCreditState(false)');
    expect(source).toContain('waitCreditState(true)');
    expect(source).toContain('stage savings-goal-transfer-reload');
    expect(source).toContain('stage loan-create-reload');
    expect(source).toContain('stage lending-repayment-reload');
    expect(source).toContain('stage recurring-create-pause-reload');
    expect(source).toContain('stage planning-create-complete-reload');
    expect(source).toContain('stage attention-decisions-reload');
    expect(source).toContain('chooseOwnedDateOffset');
    expect(source).toContain("chooseOwnedDateOffset('Προγραμματισμένη ημερομηνία',4)");
    expect(source).toContain(".owned-date-popover[role=dialog]");
    expect(source).toContain("[role=gridcell][aria-selected=true]");
    expect(source).not.toContain("new Date(input.value+'T12:00:00Z')");
    expect(source).not.toContain("setByLabel('Προγραμματισμένη ημερομηνία',attentionDismissDue)");
    expect(source).toContain('Real Browser Attention Dismiss');
    expect(source).toContain("waitAttentionDecision(snoozedAttentionId,'snoozed')");
    expect(source).toContain('waitAttentionDecision(snoozedAttentionId,null)');
    expect(source).toContain("waitAttentionDecision(dismissedAttentionId,'dismissed')");
    expect(source).toContain('attention-decisions-persisted');
    expect(source).toContain('stage budget-create-reload');
    expect(source).toContain('stage rule-create-apply-reload');
    expect(source).toContain('stage cards-lifecycle-reload');
    expect(source).toContain("await waitCardState('Real Browser Lifecycle Card',true,true,'4242')");
    expect(source).toContain('new card details closed after final durable save');
    expect(source).toContain('card.last4===last4&&card.vaultRef===card.id');
    expect(source).toContain('Real Browser Lifecycle Card');
    expect(source).toContain("querySelector('button[aria-label=\\\"Αρχειοθέτηση κάρτας\\\"]')");
    expect(source).not.toContain("clickAria('Αρχειοθέτηση κάρτας Real Browser Lifecycle Card')");
    expect(source).not.toContain('aria-label=\\\"Αρχειοθέτηση κάρτας Real Browser Lifecycle Card\\\"');
    expect(source).toContain("waitCardState('Real Browser Lifecycle Card',false,false)");
    expect(source).toContain('stage taxonomy-icons-reload');
    expect(source).toContain('Real Browser Taxonomy');
    expect(source).toContain('Real Browser Target');
    expect(source).toContain('Real Browser Sub');
    expect(source).toContain('waitExpenseCategory');
    expect(source).toContain('waitIconChoice');
    expect(source).toContain("getAttribute('data-category-id')===id");
    expect(source).not.toContain('CSS.escape(id)');
    expect(source).toContain("iconChoice.startsWith('phosphor:')");
    expect(source).toContain('Real Browser Scheduled');
    expect(source).toContain('waitBudgetAmount(777)');
    expect(source).toContain('Real Browser Rule Match');
    expect(source).toContain("waitApiEventCategory('Real Browser Rule Match','Rule Applied')");
    expect(source).toContain('stage provider-storage-create-bind-reload');
    expect(source).toContain('Real Browser Provider');
    expect(source).toContain('real-browser-provider.svg');
    expect(source).toContain('provider-storage-persisted');
    expect(source).toContain("await sleep(240);await shot('provider-storage-persisted')");
    expect(source).toContain("resource=financial-providers");
    expect(source).toContain("/storage/v1/object/public/financial-provider-assets/providers/real-browser-provider/");
    expect(source).toContain('stage account-create-delete-reload');
    expect(source).toContain('waitRecurringStatus');
    expect(source).toContain('Real Browser Savings Transfer');
    expect(source).toContain('Real Browser Loan');
    expect(source).toContain('Real Browser Repayment');
    expect(source).toContain('Real Browser Recurring');
    expect(source).toContain('Real Browser Temp Cash');
    expect(source).toContain('stage data-management-backup-import');
    expect(source).toContain('Backup & λήψη');
    expect(source).toContain('400 /api/import');
    expect(source).toContain('Imported QA Cash');
    expect(source).toContain('change-history-title');
    expect(source).toContain('Durable modern undo is unavailable after reload.');
    expect(source).toContain('Durable legacy undo is unavailable after reload.');
    expect(source).toContain('actual browser auth + modern/legacy/quick-intents/credit/savings/loans/lending/recurring/planning/attention/budgets/rules/cards/taxonomy/icons/providers/accounts/data-management persistence across hard reload');
  });
});
