import { describe, expect, it } from 'vitest';
import { createEvent } from '../src/lib/domain.js';
import { activeRecurringItems, inactiveRecurringItems, nextRecurringDate, recurringAccountChoice, recurringAccountError, recurringMonthlyTotal, recurringPayments, typicalPaymentDay } from '../src/lib/recurring.js';
import type { FinanceData, RecurringItem } from '../src/types.js';

function fixture():FinanceData{return {app:'RheomIQ',schemaVersion:3,updatedAt:'2026-08-17T00:00:00.000Z',seed:{accounts:[{id:'cash',name:'Cash',kind:'cash'}],months:[],transactions:[],snapshots:[],recurring:[{id:'rec-active',name:'Internet',amount:30,day:10,accountId:'cash',category:'Πάγια',active:true},{id:'rec-old',name:'Old plan',amount:12,day:5,accountId:'cash',category:'Συνδρομές',active:false,status:'stopped'}],subscriptions:[],loans:[],lending:[],stats:{}},state:{customTransactions:[],overrides:{},deleted:[],recurringCustom:[{id:'rec-paused',name:'Paused',amount:8,day:20,accountId:'cash',category:'Συνδρομές',active:false,status:'paused'}],recurringOverrides:{},loanExtra:{},loanOverrides:{},customLoans:[],lendingCustom:[],events:[],reviewDecisions:{},settings:{excludedFromAvailable:[],accountNames:{},expenseCategories:['Πάγια'],incomeCategories:['Μισθός'],customPresets:[],pinnedPresets:[],defaultExpenseAccount:'cash',defaultIncomeAccount:'cash',defaultLoanAccount:'cash',motion:'full'}}} as FinanceData}

describe('recurring workspace semantics',()=>{
  it('keeps inactive history while totals include active items only',()=>{const data=fixture();expect(activeRecurringItems(data).map(i=>i.id)).toEqual(['rec-active']);expect(inactiveRecurringItems(data).map(i=>i.id).sort()).toEqual(['rec-old','rec-paused']);expect(recurringMonthlyTotal(data)).toBe(30)});
  it('derives typical payment day from actual linked payments',()=>{const data=fixture();for(const [date,amount] of [['2026-06-12',30],['2026-07-14',31]] as const){const e=createEvent({kind:'expense',date,amount,note:'Internet',category:'Πάγια',accountId:'cash'});e.recurringId='rec-active';data.state.events!.push(e)}const item=data.seed.recurring[0] as RecurringItem;expect(recurringPayments(data,item.id)).toHaveLength(2);expect(typicalPaymentDay(data,item)).toBe(13);expect(nextRecurringDate(data,item,'2026-08-17')).toBe('2026-09-13')});
  it('falls back from stale recurring accounts to the first actually available account',()=>{expect(recurringAccountChoice(['cash','savings'],'removed','cash')).toBe('cash');expect(recurringAccountChoice(['cash','savings'],'removed','also-removed')).toBe('cash');expect(recurringAccountChoice([],'removed')).toBe('')});
  it('rejects stale or missing recurring accounts with actionable copy',()=>{expect(recurringAccountError(['cash'],'cash')).toBeNull();expect(recurringAccountError(['cash'],'removed')).toContain('δεν είναι πλέον διαθέσιμος');expect(recurringAccountError([],'')).toContain('Δεν υπάρχει διαθέσιμος λογαριασμός')});
});
