import { describe, expect, it } from 'vitest';
import { createEvent } from '../src/lib/domain.js';
import { operationalReportSnapshot, reportFlowSeries, subcategoryTotals } from '../src/lib/reports.js';
import type { FinanceData } from '../src/types.js';

function fixture():FinanceData{return {app:'RheomIQ',schemaVersion:3,updatedAt:'2026-08-17T00:00:00.000Z',seed:{accounts:[{id:'piraeus-payroll',name:'Payroll',kind:'bank'},{id:'piraeus-savings',name:'Savings',kind:'savings'},{id:'credit-card',name:'Credit',kind:'credit'}],months:['2026-07','2026-08'],transactions:[{id:'income',date:'2026-08-01',type:'income',accountId:'piraeus-payroll',amount:1000,note:'Salary',category:'Μισθός'},{id:'fuel',date:'2026-08-02',type:'expense',accountId:'piraeus-payroll',amount:40,note:'Fuel',category:'Όχημα',subcategory:'Βενζίνη'}],snapshots:[{date:'2026-07-31',balances:{'piraeus-payroll':200,'piraeus-savings':300,'credit-card':0}},{date:'2026-08-01',balances:{'piraeus-payroll':1200,'piraeus-savings':300,'credit-card':0}}],recurring:[{id:'internet',name:'Internet',amount:30,day:10,accountId:'piraeus-payroll',category:'Πάγια',active:true}],subscriptions:[],loans:[],lending:[{person:'Alex',entries:[],outstanding:25}],stats:{}},state:{customTransactions:[],overrides:{},deleted:[],recurringCustom:[],recurringOverrides:{},loanExtra:{},loanOverrides:{},customLoans:[],lendingCustom:[],events:[],reviewDecisions:{},settings:{excludedFromAvailable:[],accountNames:{},expenseCategories:['Όχημα','Πάγια'],incomeCategories:['Μισθός'],customPresets:[],pinnedPresets:[],defaultExpenseAccount:'piraeus-payroll',defaultIncomeAccount:'piraeus-payroll',defaultLoanAccount:'piraeus-payroll',monthlyBudget:500,creditLimit:500,motion:'full'}}} as FinanceData}

describe('operational reports',()=>{
 it('reports category/subcategory and excludes refunds from headline shape',()=>{const data=fixture();const coffee=createEvent({kind:'expense',date:'2026-08-03',amount:5,note:'Coffee',category:'Φαγητό',accountId:'piraeus-payroll'});coffee.subcategory='Καφές';data.state.events=[coffee];expect(subcategoryTotals(data,'2026-08')).toEqual(expect.arrayContaining([{name:'Όχημα › Βενζίνη',value:40},{name:'Φαγητό › Καφές',value:5}]));const snapshot=operationalReportSnapshot(data,'2026-08');expect(snapshot.flow.expense).toBe(45);expect(snapshot.recurring).toBe(30);expect(snapshot.receivables).toBe(25);expect(snapshot).not.toHaveProperty('refunds')});
 it('returns a stable six-month operational series',()=>{const series=reportFlowSeries(fixture(),'2026-08',6);expect(series).toHaveLength(6);expect(series.at(-1)?.month).toBe('2026-08')});
 it('aggregates independent credit-card limits and debts by card identity',()=>{const data=fixture();data.state.cards=[{id:'credit-a',bankId:'piraeus',nickname:'A',kind:'credit',network:'visa',creditLimit:1000,active:true,createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'},{id:'credit-b',bankId:'alpha',nickname:'B',kind:'credit',network:'mastercard',creditLimit:500,active:true,createdAt:'2026-02-01T00:00:00.000Z',updatedAt:'2026-02-01T00:00:00.000Z'}];const a=createEvent({kind:'card_purchase',date:'2026-08-05',amount:200,note:'A purchase'});a.cardId='credit-a';const aPay=createEvent({kind:'card_payment',date:'2026-08-06',amount:50,note:'A payment',fromAccountId:'piraeus-payroll'});aPay.cardId='credit-a';const b=createEvent({kind:'card_purchase',date:'2026-08-07',amount:100,note:'B purchase'});b.cardId='credit-b';data.state.events=[a,aPay,b];const snapshot=operationalReportSnapshot(data,'2026-08');expect(snapshot.creditCards).toBe(2);expect(snapshot.creditDebt).toBe(250);expect(snapshot.creditLimit).toBe(1500);expect(snapshot.creditAvailable).toBe(1250);expect(snapshot.creditUsage).toBeCloseTo(1/6)});
});
