import { describe, expect, it } from 'vitest';
import { createEvent } from '../src/lib/domain.js';
import { operationalReportSnapshot, reportFlowSeries, subcategoryTotals } from '../src/lib/reports.js';
import type { FinanceData } from '../src/types.js';

function fixture():FinanceData{return {app:'RheomIQ',schemaVersion:3,updatedAt:'2026-08-17T00:00:00.000Z',seed:{accounts:[{id:'piraeus-payroll',name:'Payroll',kind:'bank'},{id:'piraeus-savings',name:'Savings',kind:'savings'},{id:'credit-card',name:'Credit',kind:'credit'}],months:['2026-07','2026-08'],transactions:[{id:'income',date:'2026-08-01',type:'income',accountId:'piraeus-payroll',amount:1000,note:'Salary',category:'Μισθός'},{id:'fuel',date:'2026-08-02',type:'expense',accountId:'piraeus-payroll',amount:40,note:'Fuel',category:'Όχημα',subcategory:'Βενζίνη'}],snapshots:[{date:'2026-07-31',balances:{'piraeus-payroll':200,'piraeus-savings':300,'credit-card':0}},{date:'2026-08-01',balances:{'piraeus-payroll':1200,'piraeus-savings':300,'credit-card':0}}],recurring:[{id:'internet',name:'Internet',amount:30,day:10,accountId:'piraeus-payroll',category:'Πάγια',active:true}],subscriptions:[],loans:[],lending:[{person:'Alex',entries:[],outstanding:25}],stats:{}},state:{customTransactions:[],overrides:{},deleted:[],recurringCustom:[],recurringOverrides:{},loanExtra:{},loanOverrides:{},customLoans:[],lendingCustom:[],events:[],reviewDecisions:{},settings:{excludedFromAvailable:[],accountNames:{},expenseCategories:['Όχημα','Πάγια'],incomeCategories:['Μισθός'],customPresets:[],pinnedPresets:[],defaultExpenseAccount:'piraeus-payroll',defaultIncomeAccount:'piraeus-payroll',defaultLoanAccount:'piraeus-payroll',monthlyBudget:500,creditLimit:500,motion:'full'}}} as FinanceData}

describe('operational reports',()=>{
 it('reports category/subcategory and excludes refunds from headline shape',()=>{const data=fixture();const coffee=createEvent({kind:'expense',date:'2026-08-03',amount:5,note:'Coffee',category:'Φαγητό',accountId:'piraeus-payroll'});coffee.subcategory='Καφές';data.state.events=[coffee];expect(subcategoryTotals(data,'2026-08')).toEqual(expect.arrayContaining([{name:'Όχημα › Βενζίνη',value:40},{name:'Φαγητό › Καφές',value:5}]));const snapshot=operationalReportSnapshot(data,'2026-08');expect(snapshot.flow.expense).toBe(45);expect(snapshot.recurring).toBe(30);expect(snapshot.receivables).toBe(25);expect(snapshot).not.toHaveProperty('refunds')});
 it('returns a stable six-month operational series',()=>{const series=reportFlowSeries(fixture(),'2026-08',6);expect(series).toHaveLength(6);expect(series.at(-1)?.month).toBe('2026-08')});
});
