import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const shell=readFileSync(new URL('../src/components/AppShell.tsx',import.meta.url),'utf8');
const dashboard=readFileSync(new URL('../src/pages/DashboardPage.tsx',import.meta.url),'utf8');
const period=readFileSync(new URL('../src/components/PeriodControl.tsx',import.meta.url),'utf8');
const reporting=readFileSync(new URL('../src/lib/reportingPeriod.ts',import.meta.url),'utf8');
const persistence=readFileSync(new URL('../src/components/PersistenceNotice.tsx',import.meta.url),'utf8');
const qaHtml=readFileSync(new URL('../qa.html',import.meta.url),'utf8');
const part47=readFileSync(new URL('../src/styles/part47.css',import.meta.url),'utf8');
const styles=[readFileSync(new URL('../src/styles/part1.css',import.meta.url),'utf8'),readFileSync(new URL('../src/styles/part2.css',import.meta.url),'utf8'),readFileSync(new URL('../src/styles/part41.css',import.meta.url),'utf8'),readFileSync(new URL('../src/styles/part48.css',import.meta.url),'utf8')].join('\n');
const hierarchyQa=readFileSync(new URL('../scripts/shell-dashboard-hierarchy-qa.mjs',import.meta.url),'utf8');
const renderedCoordinator=readFileSync(new URL('../scripts/run-rendered-qa.mjs',import.meta.url),'utf8');
const pkg=JSON.parse(readFileSync(new URL('../package.json',import.meta.url),'utf8')) as {scripts:Record<string,string>};

describe('shell and approved Dashboard source contracts',()=>{
  it('loads QA base styles before the route-scoped approved Dashboard style chain',()=>{const base=qaHtml.indexOf("await import('/src/styles.css')"),approved=qaHtml.indexOf("await import('/src/styles/part47.css')"),app=qaHtml.indexOf("await import('/src/qa.tsx')");expect(base).toBeGreaterThan(-1);expect(approved).toBeGreaterThan(base);expect(app).toBeGreaterThan(approved);expect(part47).toContain("@import './part48.css';");expect(part47).toContain("@import './part49.css';");expect(part47).toContain("@import './part50.css';");expect(part47).toContain("@import './part51.css';")});
  it('preserves one global quick-entry route per form factor and keyboard command access',()=>{expect(shell).toContain('data-global-quick-entry="desktop"');expect(shell).toContain('data-global-quick-entry="mobile"');expect(shell.match(/data-global-quick-entry=/g)?.length).toBe(2);expect(shell).toContain('useAppShortcuts({onCommand,onQuickEntry:onQuickAdd');expect(shell).toContain('className="command-search-action"')});
  it('implements the approved dense dashboard regions while keeping contextual account actions',()=>{expect(dashboard).toContain('data-approved-dashboard="true"');expect(dashboard).toContain('data-account-quick-entry={account.id}');expect(dashboard).toContain('Κινήσεις μήνα');expect(dashboard).toContain('Επερχόμενες πληρωμές');expect(dashboard).toContain('Σύνοψη οικονομικών');expect(dashboard).toContain('Έσοδα &amp; Έξοδα');expect(dashboard).toContain('Κατηγορίες εξόδων');expect(dashboard).toContain('approved-kpi-strip')});
  it('keeps Dashboard labels and analytical claims wired to canonical behavior and periods',()=>{expect(dashboard).toContain("const accountAction=savings?'Μεταφορά':'Νέα κίνηση'");expect(dashboard).toContain('const previousFlow=selectMonthlyFlow(data,previousMonth)');expect(dashboard).toContain('const balanceMonth=asOf.slice(0,7)');expect(dashboard).toContain('const balancePreviousBalances=selectAccountBalances(data,balancePreviousRange.end)');expect(dashboard).toContain('const savingAmount=flow.saving');expect(dashboard).toContain('previousFlow.saving/previousFlow.income');expect(dashboard).toContain('comparison={savings?previousSavings:undefined}');expect(dashboard).toContain('const periodEndDate=month===asOf.slice(0,7)?asOf:range.end');expect(dashboard).toContain('<small>Αποταμίευση</small>');expect(dashboard).toContain('π.μ. από προηγ. μήνα');expect(dashboard).not.toContain('από Ιούλ.')});
  it('reuses the canonical forecast and ledger semantics for upcoming payments and expense counts',()=>{expect(dashboard).toContain("import { cashFlowForecast } from '../lib/forecast';");expect(dashboard).toContain('cashFlowForecast(data,asOf,30)');expect(dashboard).toContain('item.portfolioDelta<-.005');expect(dashboard).toContain('movements.filter(item=>item.expense).length');expect(dashboard).toContain("if(item.neutral)return `↔ ${money.format(Math.abs(item.amount))}`");expect(dashboard).not.toContain('effectiveRecurringItems');expect(dashboard).not.toContain('pendingScheduled')});
  it('keeps the semantic section order required by keyboard and responsive navigation',()=>{const primary=dashboard.indexOf('data-dashboard-section="primary-accounts"'),other=dashboard.indexOf('data-dashboard-section="other-balances"'),pending=dashboard.indexOf('data-dashboard-section="pending"'),charts=dashboard.indexOf('data-dashboard-section="quick-entry"'),rest=dashboard.indexOf('data-dashboard-section="rest"');expect(primary).toBeGreaterThan(-1);expect(other).toBeGreaterThan(primary);expect(pending).toBeGreaterThan(other);expect(charts).toBeGreaterThan(pending);expect(rest).toBeGreaterThan(charts)});
  it('matches the approved desktop frame with three primary cards, three mid panels, two chart panels and six KPI cards',()=>{expect(styles).toContain('grid-template-columns:210px minmax(0,1fr)');expect(styles).toContain('.approved-primary-grid');expect(styles).toContain('grid-template-columns:1fr 1fr 1.06fr');expect(styles).toContain('.approved-mid-grid');expect(styles).toContain('grid-template-columns:1.03fr .95fr 1.02fr');expect(styles).toContain('.approved-chart-grid');expect(styles).toContain('grid-template-columns:.94fr 1.06fr');expect(styles).toContain('.approved-kpi-strip');expect(styles).toContain('grid-template-columns:repeat(6,minmax(0,1fr))')});
  it('keeps reporting-period and persistence semantics intact',()=>{expect(period).toContain('canAdvanceReportingMonth(month,currentMonth)');expect(period).toContain('disabled={!canAdvance}');expect(period).toContain('window.setInterval(refresh,60_000)');expect(reporting).toContain('shiftReportingMonth(month,1)<=maxMonth');expect(shell).toContain("saveState==='saved'?'is-quiet':'neo-inset is-active'");expect(shell).toContain("saveState==='saved'?undefined:'polite'");expect(styles).toContain('.file-panel.is-quiet');expect(persistence).toContain('role="alert" aria-live="assertive"');expect(persistence).toContain('role="status" aria-live="polite"')});
  it('runs focused desktop/mobile rendered assertions through the canonical coordinator',()=>{expect(pkg.scripts['qa:frontend']).toBe('node scripts/run-rendered-qa.mjs');expect(renderedCoordinator).toContain("path:'scripts/shell-dashboard-hierarchy-qa.mjs'");expect(hierarchyQa).toContain("JSON.stringify(state.globals)===JSON.stringify(['desktop'])");expect(hierarchyQa).toContain("JSON.stringify(state.globals)===JSON.stringify(['mobile'])");expect(hierarchyQa).toContain('Planning does not inherit reporting period navigation')});
});
