import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const page=readFileSync(new URL('../src/pages/TransactionsPage.tsx',import.meta.url),'utf8');
const split=readFileSync(new URL('../src/components/TransactionSplitDetails.tsx',import.meta.url),'utf8');
const responsiveStyles=readFileSync(new URL('../src/styles/part46.css',import.meta.url),'utf8');
const ledgerQa=readFileSync(new URL('../scripts/ledger-foundations-qa.mjs',import.meta.url),'utf8');
const focusedQa=readFileSync(new URL('../scripts/transactions-scanability-qa.mjs',import.meta.url),'utf8');
const coordinator=readFileSync(new URL('../scripts/run-rendered-qa.mjs',import.meta.url),'utf8');

describe('Transactions scanability source contracts',()=>{
  it('removes routine app provenance and replaces internal kind fallbacks with human labels',()=>{expect(page).not.toContain("'MyFinHub'");expect(page).toContain("row.category===row.kind?eventKindLabel(row.kind):categoryPath");expect(page).toContain("if(row.source!=='legacy')return category");expect(page).toContain("row.overridden?'Ιστορικό · override':'Ιστορικό'")});
  it('keeps desktop table headers semantic and gives mobile filters readable width instead of forcing truncation',()=>{expect(page).toContain("mobile?'mobile-transaction-filters':'desktop-finance-table'");expect(page).toContain('transaction-filter-controls');const head=page.match(/<thead>[\s\S]*?<\/thead>/)?.[0]||'';expect(head).not.toContain('AppSelectInput');expect(head).toContain('Ημερομηνία');expect(head).toContain('Περιγραφή');expect(head).toContain('Λογαριασμός');expect(head).toContain('Ποσό');expect(responsiveStyles).toContain('.transactions-workspace .mobile-transaction-filters{grid-template-columns:1fr}')});
  it('keeps split details compact by default, resets disclosure after data changes and exposes accessible semantics',()=>{expect(split).toContain('useState(false)');expect(split).toContain('useEffect(()=>setOpen(false),[parts])');expect(split).toContain('aria-expanded={open}');expect(split).toContain('aria-controls={contentId}');expect(split).toContain('type="button"');expect(split).toContain('<span>{parts.length} μέρη</span>');expect(split).toContain("open?'Απόκρυψη':'Προβολή ανάλυσης'");expect(ledgerQa).toContain('split details are compact by default');expect(ledgerQa).toContain('saved split amount follows edited parts and returns compact');expect(ledgerQa).toContain('mobile transaction list preserves transfer and compact split disclosure')});
  it('keeps edit/delete parity, shared destructive confirmation and explicit empty state',()=>{expect(page).toContain("compact?'mobile-row-actions':'row-actions'");expect(page).toContain('Επεξεργασία ${title}');expect(page).toContain('Διαγραφή ${title}');expect(page).toContain('<ConfirmDialog');expect(page).toContain('tone="destructive"');expect(page).toContain('transaction-empty-state')});
  it('runs dedicated rendered coverage with evidence cropped to the actual target cases',()=>{expect(coordinator).toContain("path:'scripts/transactions-scanability-qa.mjs'");expect(focusedQa).toContain('desktop baseline hierarchy');expect(focusedQa).toContain('filter controls remain functional');expect(focusedQa).toContain('large split disclosure');expect(focusedQa).toContain("shotElement('transactions-large-split-desktop','[data-transaction-kind=split]')");expect(focusedQa).toContain("shotElement('transactions-large-split-mobile','[data-mobile-transaction-kind=split]')");expect(focusedQa).toContain("shotElement('transactions-extreme-mobile','[data-qa-extreme-target=\"true\"]')");expect(focusedQa).toContain('mobile filters remain compact while giving selected values readable width');expect(focusedQa).toContain('empty state')});
});
