import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

const page=readFileSync(new URL('../src/pages/TransactionsPage.tsx',import.meta.url),'utf8');
const split=readFileSync(new URL('../src/components/TransactionSplitDetails.tsx',import.meta.url),'utf8');
const responsiveStyles=readFileSync(new URL('../src/styles/taxonomy-transactions-mobile-layout.css',import.meta.url),'utf8');
const approvedStyles=readFileSync(new URL('../src/styles/transactions-approved.css',import.meta.url),'utf8');
const ledgerQa=readFileSync(new URL('../scripts/ledger-foundations-qa.mjs',import.meta.url),'utf8');
const focusedQa=readFileSync(new URL('../scripts/transactions-scanability-qa.mjs',import.meta.url),'utf8');
const coordinator=readFileSync(new URL('../scripts/run-rendered-qa.mjs',import.meta.url),'utf8');

describe('Transactions scanability source contracts',()=>{
  it('removes routine app provenance and replaces internal kind fallbacks with human labels',()=>{expect(page).not.toContain("'MyFinHub'");expect(page).toContain("row.category===row.kind?eventKindLabel(row.kind):categoryPath");expect(page).toContain("if(row.source!=='legacy')return category");expect(page).toContain("row.overridden?'Ιστορικό · override':'Ιστορικό'")});
  it('keeps desktop table headers semantic and gives mobile filters readable width instead of forcing truncation',()=>{expect(page).toContain("mobile?'mobile-transaction-filters':'desktop-finance-table'");expect(page).toContain('transaction-filter-controls');const head=page.match(/<thead>[\s\S]*?<\/thead>/)?.[0]||'';expect(head).not.toContain('AppSelectInput');expect(head).toContain('Ημερομηνία');expect(head).toContain('Περιγραφή');expect(head).toContain('Λογαριασμός');expect(head).toContain('Ποσό');expect(responsiveStyles).toContain('.transactions-workspace .mobile-transaction-filters{grid-template-columns:1fr}')});
  it('keeps the desktop date range readable and reflows filters before labels collide',()=>{expect(approvedStyles).toContain('minmax(240px,1.15fr) 42px');expect(approvedStyles).toContain('.transactions-approved-date .owned-input{min-width:0;width:100%;border:0;background:transparent;color:#30476e;outline:0;padding:0 2px;font-size:var(--ux-dense-label-size)!important}');expect(approvedStyles).toContain('@media(max-width:1320px)');expect(approvedStyles).toContain('.transactions-approved-filters{grid-template-columns:repeat(2,1fr);align-items:center}');expect(approvedStyles).toContain('@media(max-width:980px){.transactions-approved-grid{grid-template-columns:1fr}');expect(approvedStyles).toContain('.transactions-approved-table th{height:48px;white-space:normal;overflow-wrap:anywhere;line-height:1.2}');expect(focusedQa).toContain('desktop date range keeps both full date controls separated and readable');expect(focusedQa).toContain('tablet-width desktop filters reflow without crowding the date range');expect(focusedQa).toContain('tablet transaction table stacks details and keeps headers readable')});
  it('uses canonical account balances and a truthful date-sort affordance',()=>{expect(page).toContain('selectAccountBalances(data,row.date)');expect(page).not.toContain('legacyBalanceDeltas');expect(page).not.toContain('balanceDeltas');expect(page).toContain('<ArrowUpDown size={17}/>');expect(page).not.toContain('SlidersHorizontal');expect(page).toContain('Εναλλαγή ταξινόμησης κατά ημερομηνία')});
  it('keeps split details compact by default, resets disclosure after data changes and exposes accessible semantics',()=>{expect(split).toContain('useState(false)');expect(split).toContain('useEffect(()=>setOpen(false),[parts])');expect(split).toContain('aria-expanded={open}');expect(split).toContain('aria-controls={contentId}');expect(split).toContain('type="button"');expect(split).toContain('<span>{parts.length} μέρη</span>');expect(split).toContain("open?'Απόκρυψη':'Προβολή ανάλυσης'");expect(ledgerQa).toContain('split details are compact by default');expect(ledgerQa).toContain('saved split amount follows edited parts and returns compact');expect(ledgerQa).toContain('mobile transaction list preserves transfer and compact split disclosure')});
  it('keeps edit/delete parity, shared destructive confirmation and an actionable empty state',()=>{expect(page).toContain("compact?'mobile-row-actions':'row-actions'");expect(page).toContain('Επεξεργασία ${title}');expect(page).toContain('Διαγραφή ${title}');expect(page).toContain('<ConfirmDialog');expect(page).toContain('tone="destructive"');expect(page).toContain('transaction-empty-state');expect(page).toContain('Επαναφορά φίλτρων');expect(page).toContain('const resetFilters=()=>');expect(approvedStyles).toContain('.transaction-empty-state{min-height:330px')});
  it('allows full account-route and long-form metadata wrapping inside the dedicated detail panel',()=>{expect(page).toContain('<span>{accountText(selected.accountIds)}</span>');expect(approvedStyles).toContain('.transactions-detail-row b{color:var(--ink-2);overflow:visible;text-overflow:clip;white-space:normal;overflow-wrap:anywhere');expect(approvedStyles).toContain('.transactions-detail-row .detail-account span{color:inherit;overflow-wrap:anywhere}')});
  it('runs dedicated rendered coverage with evidence cropped to the actual target cases',()=>{expect(coordinator).toContain("path:'scripts/transactions-scanability-qa.mjs'");expect(focusedQa).toContain('desktop baseline hierarchy');expect(focusedQa).toContain('filter controls remain functional');expect(focusedQa).toContain('large split disclosure');expect(focusedQa).toContain("shotElement('transactions-large-split-desktop','[data-transaction-kind=split]')");expect(focusedQa).toContain("shotElement('transactions-large-split-mobile','[data-mobile-transaction-kind=split]')");expect(focusedQa).toContain("shotElement('transactions-extreme-mobile','[data-qa-extreme-target=\"true\"]')");expect(focusedQa).toContain('mobile filters remain compact while giving selected values readable width');expect(focusedQa).toContain('empty state');expect(focusedQa).toContain('Δεν υπάρχουν συναλλαγές σε αυτή την περίοδο');expect(focusedQa).not.toContain("empty.state.includes('Δεν υπάρχουν κινήσεις')")});
});
