import { AlertTriangle, BellRing, CalendarClock, CheckCircle2, Clock3, Eye, EyeOff, Gauge, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { AnimatedAmount } from '../components/AnimatedAmount';
import { Tooltip } from '../components/Tooltip';
import { attentionDismissDecision, attentionSnoozeDecision, visibleAttentionItems, type AttentionItem } from '../lib/attention';
import { money, shortDate } from '../lib/format';
import type { AttentionDecision, FinanceData } from '../types';

const actionLabel=(item:AttentionItem)=>item.action==='complete_scheduled'?'Ολοκλήρωση':item.action==='pay_recurring'?'Πληρωμή παγίου':item.action==='pay_loan'?'Πληρωμή δόσης':item.action==='pay_credit'?'Πληρωμή κάρτας':item.action==='collect_lending'?'Καταγραφή επιστροφής':'Άνοιγμα πρόβλεψης';
const severityLabel=(severity:AttentionItem['severity'])=>severity==='danger'?'Άμεση προσοχή':severity==='warning'?'Σύντομα':'Ενημέρωση';
const SeverityIcon=({severity}:{severity:AttentionItem['severity']})=>severity==='danger'?<AlertTriangle/>:severity==='warning'?<Clock3/>:<BellRing/>;

export function AttentionPage({data,asOf,onAction,onDecision}:{data:FinanceData;asOf:string;onAction:(item:AttentionItem)=>void;onDecision:(id:string,decision:AttentionDecision)=>void}){
  const [visible,setVisible]=useState(false);
  const [message,setMessage]=useState('');
  const items=useMemo(()=>visibleAttentionItems(data,asOf),[data,asOf]);
  const counts={danger:items.filter(item=>item.severity==='danger').length,warning:items.filter(item=>item.severity==='warning').length,info:items.filter(item=>item.severity==='info').length};
  const decide=(item:AttentionItem,kind:'snooze'|'dismiss')=>{try{const decision=kind==='snooze'?attentionSnoozeDecision(item,asOf):attentionDismissDecision(item);onDecision(item.id,decision);setMessage(kind==='snooze'?`Η υπενθύμιση «${item.title}» αναβλήθηκε προσωρινά.`:`Η ενημέρωση «${item.title}» κρύφτηκε όσο δεν αλλάζει η κατάστασή της.`)}catch(reason){setMessage(reason instanceof Error?reason.message:'Δεν ήταν δυνατή η αλλαγή της υπενθύμισης.')}};
  return <div className="page-stack attention-page"><section className="page-heading"><div><span className="eyebrow">NEEDS ATTENTION</span><h1>Τι χρειάζεται προσοχή</h1><p>Μία ντετερμινιστική λίστα ενεργειών από όσα γνωρίζει ήδη το MyFinHub. Δεν είναι οικονομική συμβουλή και δεν δημιουργεί κινήσεις χωρίς δική σου ενέργεια.</p></div><button type="button" className="secondary privacy-toggle" aria-pressed={visible} onClick={()=>setVisible(value=>!value)}>{visible?<EyeOff size={17}/>:<Eye size={17}/>} {visible?'Απόκρυψη ποσών':'Εμφάνιση ποσών'}</button></section>
  <section className="attention-summary-grid" aria-label="Σύνοψη εκκρεμοτήτων"><article className="neo-raised danger"><AlertTriangle/><div><span>Άμεση προσοχή</span><b>{counts.danger}</b><small>Δεν κρύβονται μόνιμα όσο παραμένουν επείγουσες.</small></div></article><article className="neo-raised warning"><Clock3/><div><span>Σύντομα</span><b>{counts.warning}</b><small>Υποχρεώσεις ή όρια που πλησιάζουν.</small></div></article><article className="neo-raised info"><BellRing/><div><span>Ενημέρωση</span><b>{counts.info}</b><small>Γνωστές επόμενες ενέργειες χαμηλότερης προτεραιότητας.</small></div></article></section>
  {message?<div className="action-status" role="status" aria-live="polite">{message}</div>:null}
  <section className="panel neo-raised attention-list-panel"><div className="panel-head"><div><span>Ενεργές εκκρεμότητες</span><small>Ταξινομημένες πρώτα κατά σοβαρότητα και μετά κατά ημερομηνία.</small></div><Gauge size={18}/></div>{items.length?<div className="attention-list" role="list">{items.map(item=><article role="listitem" className={`attention-row ${item.severity}`} data-attention-id={item.id} key={item.id}><span className="attention-severity-icon" aria-hidden="true"><SeverityIcon severity={item.severity}/></span><div className="attention-copy"><div className="attention-title-line"><span className={`attention-badge ${item.severity}`}>{severityLabel(item.severity)}</span><b className={!visible&&(item.kind==='lending'||item.kind==='credit')?'private-text':''}>{item.title}</b></div><p>{item.reason}</p><div className="attention-meta">{item.dueDate?<span><CalendarClock size={14}/> {shortDate(item.dueDate)}</span>:null}{item.amount!==undefined?<span><AnimatedAmount value={item.amount} hidden={!visible}/></span>:null}</div></div><div className="attention-actions"><button type="button" className="save-button compact" onClick={()=>onAction(item)}>{actionLabel(item)}</button><Tooltip label="Προσωρινή αναβολή" side="left"><button type="button" aria-label={`Αναβολή ${item.title}`} onClick={()=>decide(item,'snooze')}><Clock3/></button></Tooltip>{item.severity!=='danger'?<Tooltip label="Απόκρυψη όσο δεν αλλάζει η κατάσταση" side="left"><button type="button" aria-label={`Απόκρυψη ${item.title}`} onClick={()=>decide(item,'dismiss')}><XCircle/></button></Tooltip>:null}</div></article>)}</div>:<div className="attention-empty"><CheckCircle2/><div><b>Δεν υπάρχει κάτι που χρειάζεται άμεση ενέργεια.</b><span>Το MyFinHub θα εμφανίσει εδώ γνωστές υποχρεώσεις, όρια ή προβλεπόμενα χαμηλά υπόλοιπα όταν προκύψουν από τα δεδομένα σου.</span></div></div>}</section>
  <section className="forecast-assumption-note"><b>Πώς λειτουργεί:</b> η λίστα βασίζεται μόνο σε αποθηκευμένες ημερομηνίες, πραγματικές οφειλές/όρια και τη ντετερμινιστική προβολή 30 ημερών. Δανεικά εμφανίζονται ως ληξιπρόθεσμα μόνο αν έχεις ορίσει ρητή αναμενόμενη ημερομηνία επιστροφής.</section></div>;
}
