import { Copy, CreditCard, Eye, EyeOff, Link2, Plus, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import { useModalFocus } from '../hooks/useModalFocus';
import { cardBanks, cardKindLabel, cardLabel, cardNetworkLabel, cardsForBank } from '../lib/cards';
import type { CardBank, CardKind, CardNetwork, FinanceData, PaymentCard } from '../types';

export function CardsPage({data,onUpsertBank,onUpsertCard,onArchiveCard,onOpenCredit}:{data:FinanceData;onUpsertBank:(bank:CardBank)=>void;onUpsertCard:(card:PaymentCard)=>void;onArchiveCard:(card:PaymentCard)=>void;onOpenCredit:()=>void}){
  const banks=cardBanks(data);const [visible,setVisible]=useState(false);const [bankOpen,setBankOpen]=useState(false);const [cardBank,setCardBank]=useState<CardBank|null>(null);const [bankName,setBankName]=useState('');const [nickname,setNickname]=useState('');const [kind,setKind]=useState<CardKind>('debit');const [network,setNetwork]=useState<CardNetwork>('visa');const [holder,setHolder]=useState('');const [last4,setLast4]=useState('');const [error,setError]=useState('');const bankRef=useModalFocus<HTMLElement>(bankOpen,'input');const cardRef=useModalFocus<HTMLElement>(Boolean(cardBank),'input');
  const startBank=()=>{setBankName('');setError('');setBankOpen(true)};const closeBank=()=>{setBankOpen(false);setError('')};
  const saveBank=()=>{const name=bankName.trim();if(!name){setError('Συμπλήρωσε όνομα τράπεζας.');return}const id=`custom-${Date.now()}`;onUpsertBank({id,name:name.toUpperCase(),order:Math.max(60,...banks.map(bank=>bank.order+10)),custom:true});closeBank()};
  const startCard=(bank:CardBank)=>{setCardBank(bank);setNickname('');setKind('debit');setNetwork('visa');setHolder('');setLast4('');setError('')};const closeCard=()=>{setCardBank(null);setError('')};
  const saveCard=()=>{if(!cardBank)return;const name=nickname.trim();const digits=last4.replace(/\D/g,'');if(!name){setError('Συμπλήρωσε ένα όνομα για την κάρτα.');return}if(digits&&digits.length!==4){setError('Τα τελευταία ψηφία πρέπει να είναι ακριβώς 4.');return}const now=new Date().toISOString();onUpsertCard({id:`card-${Date.now()}`,bankId:cardBank.id,nickname:name,kind,network,holderName:holder.trim()||undefined,last4:digits||undefined,active:true,createdAt:now,updatedAt:now});closeCard()};
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">ΚΑΡΤΕΣ</span><h1>Κάρτες</h1><p>Οι κάρτες είναι οργανωμένες ανά τράπεζα. Τα πραγματικά στοιχεία παραμένουν κρυμμένα μέχρι να τα εμφανίσεις.</p></div><div className="heading-actions"><button type="button" className="secondary privacy-toggle" aria-pressed={visible} onClick={()=>setVisible(value=>!value)}>{visible?<EyeOff size={17}/>:<Eye size={17}/>} {visible?'Απόκρυψη':'Εμφάνιση στοιχείων'}</button><button type="button" className="save-button" onClick={startBank}><Plus size={17}/> Τράπεζα</button></div></section>
  <section className="banks-scroll" aria-label="Κάρτες ανά τράπεζα">{banks.map(bank=>{const cards=cardsForBank(data,bank.id);return <article className="bank-column" key={bank.id}><header><div><span>{bank.name}</span><small>{cards.length} {cards.length===1?'κάρτα':'κάρτες'}</small></div><button type="button" aria-label={`Προσθήκη κάρτας στην ${bank.name}`} onClick={()=>startCard(bank)}><Plus size={17}/></button></header><div className="bank-card-stack">{cards.map(card=><article className={`payment-card bank-${bank.id} network-${card.network}`} key={card.id}><div className="payment-card-top"><span>{bank.name}</span><b>{cardNetworkLabel(card)}</b></div><div className="payment-card-chip" aria-hidden="true"/><div className={`payment-card-number ${!visible?'masked-card-text':''}`}>{visible?(card.last4?`•••• •••• •••• ${card.last4}`:'Δεν έχουν αποθηκευτεί στοιχεία'):'•••• •••• •••• ••••'}</div><div className="payment-card-bottom"><div><small>ΚΑΤΟΧΟΣ</small><b className={!visible?'masked-card-text':''}>{card.holderName||cardLabel(card)}</b></div><div><small>ΛΗΞΗ</small><b>{visible?'••/••':'••/••'}</b></div></div><footer><span>{cardKindLabel(card)}</span>{card.kind==='credit'?<button type="button" onClick={onOpenCredit}><Link2 size={14}/> Πιστωτική</button>:null}<button type="button" aria-label={`Αρχειοθέτηση ${cardLabel(card)}`} onClick={()=>{if(window.confirm(`Να κρυφτεί η κάρτα «${cardLabel(card)}» από τις ενεργές;`))onArchiveCard(card)}}><Trash2 size={14}/></button></footer><div className="secure-card-actions" aria-label="Ασφαλή στοιχεία κάρτας"><button type="button" disabled title="Θα ενεργοποιηθεί από το κρυπτογραφημένο card vault"><Copy size={13}/> Αριθμός</button><button type="button" disabled title="Θα ενεργοποιηθεί από το κρυπτογραφημένο card vault"><Copy size={13}/> Λήξη</button><button type="button" disabled title="Το CVV δεν αποθηκεύεται χωρίς ξεχωριστή απόφαση ασφαλείας"><Copy size={13}/> CVV</button></div></article>)}{!cards.length?<button type="button" className="empty-bank-card" onClick={()=>startCard(bank)}><Plus/><span>Προσθήκη κάρτας</span></button>:null}</div></article>})}</section>
  <div className="logic-note compact card-security-note"><CreditCard/><div><b>Ασφαλή στοιχεία</b><span>Αριθμός κάρτας, λήξη και άλλα μυστικά δεν γράφονται στο συνηθισμένο οικονομικό state ή στα JSON backups. Η κρυπτογραφημένη αποθήκευση ενεργοποιείται από ξεχωριστό ασφαλές card vault.</span></div></div>
  {bankOpen?<div className="editor-backdrop" onMouseDown={closeBank}><section ref={bankRef} className="panel neo-raised editor-dialog compact-dialog" role="dialog" aria-modal="true" aria-labelledby="new-bank-title" tabIndex={-1} onMouseDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();closeBank()}}}><div className="panel-head"><div><span id="new-bank-title">Νέα τράπεζα</span><small>Οι πέντε βασικές τράπεζες παραμένουν πάντα στην προκαθορισμένη σειρά.</small></div><button type="button" className="icon-button" aria-label="Κλείσιμο νέας τράπεζας" onClick={closeBank}><X/></button></div><div className="settings-form"><label><span>Όνομα</span><input value={bankName} onChange={e=>setBankName(e.target.value)} placeholder="Τράπεζα"/></label></div>{error?<div className="form-error" role="alert">{error}</div>:null}<div className="editor-actions"><button type="button" className="secondary" onClick={closeBank}>Ακύρωση</button><button type="button" className="save-button" onClick={saveBank}>Προσθήκη</button></div></section></div>:null}
  {cardBank?<div className="editor-backdrop" onMouseDown={closeCard}><section ref={cardRef} className="panel neo-raised editor-dialog" role="dialog" aria-modal="true" aria-labelledby="new-card-title" tabIndex={-1} onMouseDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();closeCard()}}}><div className="panel-head"><div><span id="new-card-title">Νέα κάρτα · {cardBank.name}</span><small>Εδώ αποθηκεύονται μόνο μη μυστικά metadata. Τα πλήρη στοιχεία θα πάνε στο ασφαλές vault.</small></div><button type="button" className="icon-button" aria-label="Κλείσιμο νέας κάρτας" onClick={closeCard}><X/></button></div><div className="settings-form editor-grid"><label><span>Όνομα κάρτας</span><input data-autofocus="true" value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="π.χ. Blue Debit"/></label><label><span>Τύπος</span><select value={kind} onChange={e=>setKind(e.target.value as CardKind)}><option value="debit">Χρεωστική</option><option value="prepaid">Prepaid</option><option value="credit">Πιστωτική</option></select></label><label><span>Δίκτυο</span><select value={network} onChange={e=>setNetwork(e.target.value as CardNetwork)}><option value="visa">Visa</option><option value="mastercard">Mastercard</option><option value="other">Άλλο</option></select></label><label><span>Τελευταία 4 ψηφία</span><input inputMode="numeric" maxLength={4} value={last4} onChange={e=>setLast4(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="1234"/></label><label className="wide"><span>Όνομα κατόχου <em>προαιρετικό</em></span><input value={holder} onChange={e=>setHolder(e.target.value)}/></label></div>{error?<div className="form-error" role="alert">{error}</div>:null}<div className="editor-actions"><button type="button" className="secondary" onClick={closeCard}>Ακύρωση</button><button type="button" className="save-button" onClick={saveCard}>Προσθήκη κάρτας</button></div></section></div>:null}</div>;
}
