import { CreditCard, ReceiptText, WalletCards, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useModalFocus } from '../hooks/useModalFocus';
import { categoryPath, genericCategoryTree, subcategoriesFor } from '../lib/categories';
import { accountBalances, allAccounts, createEvent } from '../lib/domain';
import { money, shortDate } from '../lib/format';
import { accountDisplayName } from '../lib/ui';
import type { FinanceData, FinanceEvent } from '../types';

export function CreditCardPage({data,asOf,onCreateEvent}:{data:FinanceData;asOf:string;onCreateEvent:(event:FinanceEvent)=>void}){
  const balances=accountBalances(data,asOf);
  const debt=Math.abs(Math.min(0,balances['credit-card']||0));
  const limit=data.state.settings.creditLimit??500;
  const available=Math.max(0,limit-debt);
  const usage=limit>0?Math.min(100,(debt/limit)*100):0;
  const purchases=useMemo(()=>[...(data.state.events??[])].filter(event=>event.kind==='card_purchase').sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)),[data]);
  const piraeusAccounts=allAccounts(data).filter(account=>account.kind!=='credit'&&account.id.startsWith('piraeus-'));
  const categories=genericCategoryTree(data.state.settings,'expense');
  const [purchaseOpen,setPurchaseOpen]=useState(false);const [repayOpen,setRepayOpen]=useState(false);
  const [amount,setAmount]=useState('');const [date,setDate]=useState(asOf);const [note,setNote]=useState('');const [category,setCategory]=useState(categories[0]?.name||data.state.settings.expenseCategories[0]||'Άλλο');const [subcategory,setSubcategory]=useState('');const [sourceAccount,setSourceAccount]=useState(piraeusAccounts[0]?.id||data.state.settings.defaultExpenseAccount);const [error,setError]=useState('');
  const purchaseRef=useModalFocus<HTMLElement>(purchaseOpen,'[data-autofocus="true"]');const repayRef=useModalFocus<HTMLElement>(repayOpen,'[data-autofocus="true"]');
  const reset=()=>{setAmount('');setDate(asOf);setNote('');setError('')};
  const openPurchase=()=>{reset();setCategory(categories[0]?.name||'Άλλο');setSubcategory('');setPurchaseOpen(true)};
  const openRepay=()=>{reset();setAmount(debt>0?String(Number(debt.toFixed(2))):'');setSourceAccount(piraeusAccounts[0]?.id||data.state.settings.defaultExpenseAccount);setRepayOpen(true)};
  const closePurchase=()=>{setPurchaseOpen(false);setError('')};const closeRepay=()=>{setRepayOpen(false);setError('')};
  const submitPurchase=()=>{const numeric=Number(amount.replace(',','.'));if(!Number.isFinite(numeric)||numeric<=0){setError('Βάλε θετικό ποσό αγοράς.');return}try{const event=createEvent({kind:'card_purchase',date,amount:numeric,note:note.trim()||category,category});event.subcategory=subcategory||undefined;onCreateEvent(event);closePurchase()}catch(e){setError(e instanceof Error?e.message:'Η αγορά δεν καταχωρίστηκε.')}};
  const submitRepay=()=>{const numeric=Number(amount.replace(',','.'));if(debt<=0){setError('Δεν υπάρχει οφειλή προς αποπληρωμή.');return}if(!Number.isFinite(numeric)||numeric<=0){setError('Βάλε θετικό ποσό αποπληρωμής.');return}if(numeric>debt+.005){setError(`Η αποπληρωμή δεν μπορεί να ξεπερνά την οφειλή των ${money.format(debt)}.`);return}if(!piraeusAccounts.some(account=>account.id===sourceAccount)){setError('Η αποπληρωμή πρέπει να γίνει από λογαριασμό της Πειραιώς.');return}try{const event=createEvent({kind:'card_payment',date,amount:numeric,note:'Αποπληρωμή πιστωτικής',fromAccountId:sourceAccount});onCreateEvent(event);closeRepay()}catch(e){setError(e instanceof Error?e.message:'Η αποπληρωμή δεν καταχωρίστηκε.')}};
  const subs=subcategoriesFor(data.state.settings,'expense',category);
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">ΠΙΣΤΩΤΙΚΗ ΚΑΡΤΑ</span><h1>Πιστωτική Κάρτα</h1><p>Η αγορά καταγράφεται ως έξοδο και ταυτόχρονα αυξάνει την οφειλή. Η αποπληρωμή μειώνει μόνο την οφειλή και τον επιλεγμένο τραπεζικό λογαριασμό, χωρίς δεύτερο έξοδο.</p></div><div className="heading-actions"><button type="button" className="secondary" disabled={debt<=0} onClick={openRepay}><ReceiptText size={16}/> Αποπληρωμή</button><button type="button" className="save-button" onClick={openPurchase}><CreditCard size={17}/> Νέα αγορά</button></div></section>
  <section className="credit-summary-grid"><article className="credit-hero neo-raised"><div><span>Οφειλή</span><b>{money.format(debt)}</b><small>Συνολικό όριο {money.format(limit)}</small></div><CreditCard size={54}/></article><article className="panel neo-raised"><div className="credit-usage-copy"><span>Διαθέσιμο όριο</span><b>{money.format(available)}</b></div><div className="credit-usage" role="progressbar" aria-label="Χρήση πιστωτικού ορίου" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(usage)}><i style={{width:`${usage}%`}}/></div><div className="credit-usage-copy"><span>{money.format(debt)} χρησιμοποιημένα</span><b>{Math.round(usage)}%</b></div><div className="credit-limit-numbers"><span><small>Όριο</small><b>{money.format(limit)}</b></span><span><small>Διαθέσιμο</small><b>{money.format(available)}</b></span></div></article></section>
  <section className="panel neo-raised"><div className="panel-head"><div><span>Αγορές πιστωτικής</span><small>Αυτό είναι το απομονωμένο ιστορικό εξόδων της πιστωτικής.</small></div><WalletCards/></div>{purchases.length?<div className="semantic-table-wrap"><table className="semantic-table credit-purchases-table"><caption className="sr-only">Αγορές με πιστωτική κάρτα</caption><thead><tr><th>Ημερομηνία</th><th>Περιγραφή</th><th>Κατηγορία</th><th className="amount">Ποσό</th></tr></thead><tbody>{purchases.map(event=><tr key={event.id}><td>{shortDate(event.date)}</td><td><b>{event.note}</b></td><td>{categoryPath(event.category,event.subcategory)}</td><td className="amount negative">{money.format(event.amount)}</td></tr>)}</tbody></table></div>:<div className="empty-state">Δεν υπάρχουν ακόμη αγορές με την πιστωτική.</div>}</section>
  {purchaseOpen?<div className="editor-backdrop" onMouseDown={closePurchase}><section ref={purchaseRef} className="panel neo-raised editor-dialog credit-dialog" role="dialog" aria-modal="true" aria-labelledby="credit-purchase-title" tabIndex={-1} onMouseDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();closePurchase()}}}><div className="panel-head"><div><span id="credit-purchase-title">Νέα αγορά πιστωτικής</span><small>Η αγορά αυξάνει την οφειλή και μετρά μία φορά ως έξοδο.</small></div><button type="button" className="icon-button" aria-label="Κλείσιμο αγοράς πιστωτικής" onClick={closePurchase}><X/></button></div><div className="settings-form editor-grid"><label><span>Ποσό</span><input data-autofocus="true" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value.replace(',','.'))}/></label><label><span>Ημερομηνία</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>Κατηγορία</span><select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('')}}>{categories.map(item=><option key={item.name}>{item.name}</option>)}</select></label>{subs.length?<label><span>Υποκατηγορία</span><select value={subcategory} onChange={e=>setSubcategory(e.target.value)}><option value="">Χωρίς υποκατηγορία</option>{subs.map(value=><option key={value}>{value}</option>)}</select></label>:null}<label className="wide"><span>Περιγραφή</span><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Τι αγόρασες;"/></label></div>{error?<div className="form-error" role="alert">{error}</div>:null}<div className="editor-actions"><button type="button" className="secondary" onClick={closePurchase}>Ακύρωση</button><button type="button" className="save-button" onClick={submitPurchase}>Καταχώριση αγοράς</button></div></section></div>:null}
  {repayOpen?<div className="editor-backdrop" onMouseDown={closeRepay}><section ref={repayRef} className="panel neo-raised editor-dialog credit-dialog" role="dialog" aria-modal="true" aria-labelledby="credit-repay-title" tabIndex={-1} onMouseDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();closeRepay()}}}><div className="panel-head"><div><span id="credit-repay-title">Αποπληρωμή πιστωτικής</span><small>Επιλέγεις λογαριασμό Πειραιώς. Το ίδιο ποσό αφαιρείται από τον λογαριασμό και από την οφειλή.</small></div><button type="button" className="icon-button" aria-label="Κλείσιμο αποπληρωμής πιστωτικής" onClick={closeRepay}><X/></button></div><div className="settings-form editor-grid"><label><span>Ποσό</span><input data-autofocus="true" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value.replace(',','.'))}/></label><label><span>Ημερομηνία</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="wide"><span>Από λογαριασμό Πειραιώς</span><select value={sourceAccount} onChange={e=>setSourceAccount(e.target.value)}>{piraeusAccounts.map(account=><option key={account.id} value={account.id}>{accountDisplayName(data,account.id)} · {money.format(balances[account.id]||0)}</option>)}</select></label></div><div className="credit-repay-preview"><span>Τωρινή οφειλή <b>{money.format(debt)}</b></span><span>Μετά την αποπληρωμή <b>{money.format(Math.max(0,debt-(Number(amount)||0)))}</b></span><span>Διαθέσιμο όριο μετά <b>{money.format(Math.min(limit,available+(Number(amount)||0)))}</b></span></div>{error?<div className="form-error" role="alert">{error}</div>:null}<div className="editor-actions"><button type="button" className="secondary" onClick={closeRepay}>Ακύρωση</button><button type="button" className="save-button" onClick={submitRepay}>Επιβεβαίωση αποπληρωμής</button></div></section></div>:null}</div>;
}
