import { motion, useReducedMotion } from 'framer-motion';
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownRight, ArrowUpRight, CalendarClock, CreditCard, FileCheck2, PiggyBank, Plus, Sparkles, Wallet } from 'lucide-react';
import { MetricCard } from '../components/MetricCard';
import { allAccounts, legacyOutstandingReceivables, reviewSuggestions } from '../lib/domain';
import { selectAccountBalances, selectAvailableMoney, selectCategoryTotals, selectDailyExpenseSeries, selectFrequentDescriptions, selectMonthlyFlow, selectNetWorth } from '../lib/selectors';
import { compactMoney, money } from '../lib/format';
import type { FinanceData } from '../types';

const chartColors=['#2f6fed','#25b9d7','#55c2a3','#f3b43f','#845ef7','#ef6675','#174ea6','#89a9ff'];

export function DashboardPage({ data, month, asOf, onQuickAdd, onReview, onTransactions }: {data:FinanceData;month:string;asOf:string;onQuickAdd:()=>void;onReview:()=>void;onTransactions:()=>void}) {
  const reduce=useReducedMotion();
  const flow=selectMonthlyFlow(data,month);
  const balances=selectAccountBalances(data,asOf);
  const accounts=allAccounts(data);
  const categories=selectCategoryTotals(data,month).slice(0,8);
  const daily=selectDailyExpenseSeries(data,month);
  const reviewCount=reviewSuggestions(data).length;
  const recurring=(data.seed.recurring??[]).filter(r=>r.active).slice(0,4);
  const recent=[...(data.state.events??[])].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
  const saveRate=flow.income>0?flow.saving/flow.income:0;
  const budget=data.state.settings.monthlyBudget||1200;
  const frequent=selectFrequentDescriptions(data,'expense',5);
  const receivables=legacyOutstandingReceivables(data)+(data.state.events??[]).reduce((s,e)=>s+Number(e.receivableDelta||0),0);
  const credit=Math.abs(Math.min(0,balances['credit-card']||0));

  return <div className="page-stack">
    <section className="page-heading"><div><span className="eyebrow">RHEOMIQ OVERVIEW</span><h1>Οικονομική εικόνα</h1><p>Το σημαντικό τώρα, χωρίς να ψάχνεις σε φύλλα και σχόλια.</p></div><button className="save-button" onClick={onQuickAdd}><Plus size={17}/> Νέα κίνηση</button></section>
    <section className="metric-grid"><MetricCard label="Καθαρή θέση" value={money.format(selectNetWorth(data,asOf))} hint={`+ ${money.format(receivables)} που σου οφείλονται`} icon={<Wallet size={17}/>} tone="blue"/><MetricCard label="Διαθέσιμα" value={money.format(selectAvailableMoney(data,asOf))} hint="Χωρίς αποταμιευτικό & πιστωτική" icon={<Wallet size={17}/>} tone="cyan"/><MetricCard label={`Έσοδα ${month.slice(5)}/${month.slice(0,4)}`} value={money.format(flow.income)} hint="Πραγματικό cash inflow" icon={<ArrowUpRight size={17}/>} tone="green"/><MetricCard label={`Έξοδα ${month.slice(5)}/${month.slice(0,4)}`} value={money.format(flow.expense)} hint={`${Math.round((flow.expense/budget)*100)}% του budget`} icon={<ArrowDownRight size={17}/>} tone="red" progress={budget?flow.expense/budget:0}/><MetricCard label="Αποταμίευση" value={money.format(flow.saving)} hint={`${Math.round(saveRate*100)}% των εσόδων`} icon={<PiggyBank size={17}/>} tone="cyan" progress={saveRate}/></section>
    <section className="account-strip neo-flat"><div className="section-title"><div><span>Λογαριασμοί</span><b>Υπόλοιπα έως {asOf.split('-').reverse().join('/')}</b></div><button className="text-button" onClick={onTransactions}>Προβολή κινήσεων</button></div><div className="account-grid">{accounts.map(a=>{const bal=balances[a.id]||0; const isCredit=a.kind==='credit';return <motion.div className={`account-chip ${isCredit?'credit':''}`} key={a.id} whileHover={reduce?undefined:{y:-2}}><span className="account-mark">{a.short||a.name.slice(0,2)}</span><div><small>{a.name}</small><b className={bal<0?'negative':''}>{money.format(bal)}</b></div>{a.kind==='savings'?<PiggyBank size={18}/>:isCredit?<CreditCard size={18}/>:null}</motion.div>})}</div></section>
    <section className="dashboard-grid"><article className="panel neo-raised quick-panel"><div className="panel-head"><div><span>Γρήγορη καταχώριση</span><small>Σχεδόν χωρίς πληκτρολόγηση</small></div><Sparkles size={18}/></div><div className="frequent-grid">{frequent.map(f=><button key={f.label} onClick={onQuickAdd}><b>{f.label}</b><span>{f.count} φορές</span><strong>{money.format(f.lastAmount)}</strong></button>)}</div><button className="wide-action" onClick={onQuickAdd}><Plus size={16}/> Άνοιγμα Smart Entry</button></article><article className="panel neo-raised chart-panel"><div className="panel-head"><div><span>Έξοδα ανά κατηγορία</span><small>{money.format(flow.expense)} αυτόν τον μήνα</small></div></div><div className="pie-layout"><div className="chart-wrap"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={58} outerRadius={85} paddingAngle={2}>{categories.map((_,i)=><Cell key={i} fill={chartColors[i%chartColors.length]}/>)}</Pie><Tooltip formatter={(v)=>money.format(Number(v))}/></PieChart></ResponsiveContainer><div className="pie-center"><b>{compactMoney.format(flow.expense)}</b><span>σύνολο</span></div></div><div className="legend">{categories.map((c,i)=><div key={c.name}><i style={{background:chartColors[i%chartColors.length]}}/><span>{c.name}</span><b>{money.format(c.value)}</b></div>)}</div></div></article><article className="panel neo-raised chart-panel"><div className="panel-head"><div><span>Εξέλιξη εξόδων</span><small>Ημερήσια ροή</small></div></div><ResponsiveContainer width="100%" height={245}><AreaChart data={daily}><defs><linearGradient id="expenseFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ef6675" stopOpacity=".3"/><stop offset="100%" stopColor="#ef6675" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#dbe4f0" vertical={false}/><XAxis dataKey="date" tick={{fontSize:10,fill:'#7c8aa5'}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:9,fill:'#7c8aa5'}} axisLine={false} tickLine={false}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Area type="monotone" dataKey="value" stroke="#e94560" strokeWidth={2.4} fill="url(#expenseFill)" animationDuration={reduce?0:700}/></AreaChart></ResponsiveContainer></article></section>
    <section className="lower-grid"><article className="panel neo-raised"><div className="panel-head"><div><span>Έξυπνες επισημάνσεις</span><small>Πράγματα που χρειάζονται προσοχή</small></div><button className="text-button" onClick={onReview}>Όλες</button></div><div className="insight-list"><button onClick={onReview}><span className="insight-icon review"><FileCheck2/></span><div><b>{reviewCount} legacy κινήσεις για review</b><small>Καμία πρόταση δεν αλλάζει τα reports πριν την επιβεβαιώσεις.</small></div><strong>{reviewCount}</strong></button><div><span className="insight-icon saving"><PiggyBank/></span><div><b>Ρυθμός αποταμίευσης {Math.round(saveRate*100)}%</b><small>Στόχος {Math.round((data.state.settings.savingsTargetRate||.2)*100)}%</small></div><strong>{saveRate >= (data.state.settings.savingsTargetRate||.2)?'On track':'Κάτω από στόχο'}</strong></div><div><span className="insight-icon card"><CreditCard/></span><div><b>Πιστωτική οφειλή</b><small>Η εξόφληση δεν μετρά δεύτερη φορά ως expense.</small></div><strong>{money.format(credit)}</strong></div></div></article><article className="panel neo-raised"><div className="panel-head"><div><span>Εκκρεμή πάγια</span><small>Ενεργές επαναλαμβανόμενες υποχρεώσεις</small></div><CalendarClock size={17}/></div><div className="recurring-mini">{recurring.map(r=><div key={r.id}><span>{r.name}</span><b>{money.format(r.amount)}</b><small>{r.day?`${r.day} του μήνα`:'χωρίς ημερομηνία'}</small></div>)}</div></article><article className="panel neo-raised"><div className="panel-head"><div><span>Πρόσφατες έξυπνες κινήσεις</span><small>Νέο event ledger</small></div></div>{recent.length?<div className="recent-list">{recent.map(e=><div key={e.id}><span className={`event-dot ${e.kind}`}/><div><b>{e.note}</b><small>{e.kind} · {e.date}</small></div><strong>{money.format(e.amount)}</strong></div>)}</div>:<div className="empty-state">Οι νέες σύνθετες κινήσεις θα εμφανίζονται εδώ. Το ιστορικό Excel παραμένει διαθέσιμο στις Συναλλαγές.</div>}</article></section>
  </div>;
}
