import { Eye, EyeOff, HandCoins, Plus, RotateCcw, UserRound, X } from 'lucide-react';
import { useState } from 'react';
import { AnimatedAmount } from '../components/AnimatedAmount';
import { useModalFocus } from '../hooks/useModalFocus';
import { allAccounts, createEvent } from '../lib/domain';
import { money, shortDate } from '../lib/format';
import { lendingHistory, lendingOutstandingFor, lendingRows } from '../lib/lending';
import { accountDisplayName } from '../lib/ui';
import type { FinanceData, FinanceEvent } from '../types';

export function LendingPage({data,asOf,onCreateEvent}:{data:FinanceData;asOf:string;onCreateEvent:(event:FinanceEvent)=>void}){
  const rows=lendingRows(data);const history=lendingHistory(data);const total=rows.reduce((s,p)=>s+p.outstanding,0);const accounts=allAccounts(data).filter(account=>account.kind!=='credit');
  const [visible,setVisible]=useState(false);const [open,setOpen]=useState(false);const [kind,setKind]=useState<'lending'|'repayment'>('lending');const [person,setPerson]=useState('');const [amount,setAmount]=useState('');const [date,setDate]=useState(asOf);const [account,setAccount]=useState(data.state.settings.defaultExpenseAccount);const [note,setNote]=useState('');const [error,setError]=useState('');const modalRef=useModalFocus<HTMLElement>(open,'[data-autofocus="true"]');
  const start=(next:'lending'|'repayment',presetPerson='')=>{setKind(next);setPerson(presetPerson);setAmount('');setDate(asOf);setAccount(next==='lending'?data.state.settings.defaultExpenseAccount:data.state.settings.defaultIncomeAccount);setNote('');setError('');setOpen(true)};const close=()=>{setOpen(false);setError('')};
  const submit=()=>{const cleanPerson=person.trim();const numeric=Number(amount.replace(',','.'));if(!cleanPerson){setError('Συμπλήρωσε το πρόσωπο.');return}if(!Number.isFinite(numeric)||numeric<=0){setError('Βάλε θετικό ποσό.');return}if(kind==='repayment'){const outstanding=lendingOutstandingFor(data,cleanPerson);if(outstanding<=0){setError('Δεν υπάρχει καταγεγραμμένη οφειλή για αυτό το πρόσωπο.');return}if(numeric>outstanding+.01){setError(`Η επιστροφή δεν μπορεί να ξεπερνά την οφειλή των ${money.format(outstanding)}.`);return}}try{const event=createEvent({kind,date,amount:numeric,note:note.trim()||(kind==='lending'?'Πλήρωσα για άλλον':'Επιστροφή δανεικών'),accountId:account,person:cleanPerson});onCreateEvent(event);close()}catch(e){setError(e instanceof Error?e.message:'Δεν ήταν δυνατή η καταχώριση.')}};
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">ΔΑΝΕΙΚΑ ΠΡΟΣ ΑΛΛΟΥΣ</span><h1>Δανεικά & επιστροφές</h1><p>Πλήρες ιστορικό για όσα πλήρωσες για άλλους και όσα σου επέστρεψαν. Δεν θεωρούνται προσωπικό spending όσο παραμένουν απαίτηση.</p></div><div className="heading-actions"><button type="button" className="secondary privacy-toggle" aria-pressed={visible} onClick={()=>setVisible(value=>!value)}>{visible?<EyeOff size={17}/>:<Eye size={17}/>} {visible?'Απόκρυψη στοιχείων':'Εμφάνιση στοιχείων'}</button><button type="button" className="save-button" onClick={()=>start('lending')}><HandCoins size={17}/> Νέα κίνηση</button></div></section>
  <section className="credit-hero receivable-hero neo-raised"><div><span>Συνολικά προς είσπραξη</span><b><AnimatedAmount value={total} hidden={!visible}/></b><small>{rows.length} πρόσωπα με ιστορικό</small></div><HandCoins size={54}/></section>
  <section className="receivable-person-grid">{rows.map(row=><article className="panel neo-raised" key={row.person}><div className="loan-title"><span className="account-mark"><UserRound/></span><div><h3 className={!visible?'private-text':''}>{row.person}</h3><small>{row.events} καταγεγραμμένες κινήσεις</small></div><b className={row.outstanding>0?'positive':''}><AnimatedAmount value={row.outstanding} hidden={!visible}/></b></div><div className="receivable-person-actions"><span>{row.outstanding>0?'Εκκρεμεί':'Εξοφλημένο'}</span><button type="button" className="text-button" onClick={()=>start('lending',row.person)}><Plus size={14}/> Νέο</button>{row.outstanding>0?<button type="button" className="text-button" onClick={()=>start('repayment',row.person)}><RotateCcw size={14}/> Επιστροφή</button>:null}</div></article>)}</section>
  <section className="panel neo-raised"><div className="panel-head"><div><span>Πλήρες ιστορικό</span><small>Ημερομηνία, πρόσωπο, ενέργεια, ποσό και τρέχουσα οφειλή μετά από κάθε κίνηση.</small></div></div>{history.length?<div className="semantic-table-wrap"><table className="semantic-table receivables-table"><caption className="sr-only">Πλήρες ιστορικό δανεικών και επιστροφών</caption><thead><tr><th scope="col">Ημερομηνία</th><th scope="col">Πρόσωπο</th><th scope="col">Κίνηση</th><th scope="col">Σχόλιο</th><th scope="col">Λογαριασμός</th><th scope="col" className="amount">Ποσό</th><th scope="col" className="amount">Υπόλοιπο</th></tr></thead><tbody>{history.map(row=><tr key={row.id}><td>{shortDate(row.date)}</td><td><b className={!visible?'private-text':''}>{row.person}</b></td><td><span className={`receivable-action ${row.action}`}>{row.action==='lent'?'Πλήρωσα για άλλον':row.action==='repaid'?'Μου επέστρεψαν':'Χάρισμα'}</span></td><td><span className={!visible?'private-text':''}>{row.note}</span></td><td>{row.accountId?accountDisplayName(data,row.accountId):'Ιστορικό'}</td><td className="amount">{row.action==='lent'?'+':'−'}{money.format(row.amount)}</td><td className="amount"><AnimatedAmount value={row.runningOutstanding} hidden={!visible}/></td></tr>)}</tbody></table></div>:<div className="empty-state">Δεν υπάρχει ιστορικό δανεικών.</div>}</section>
  {open?<div className="editor-backdrop" onMouseDown={close}><section ref={modalRef} className="panel neo-raised editor-dialog lending-dialog" role="dialog" aria-modal="true" aria-labelledby="lending-dialog-title" tabIndex={-1} onMouseDown={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();close()}}}><div className="panel-head"><div><span id="lending-dialog-title">{kind==='lending'?'Πλήρωσα για άλλον':'Μου επέστρεψαν'}</span><small>{kind==='lending'?'Αυξάνει όσα σου χρωστά το πρόσωπο.':'Μειώνει την οφειλή και αυξάνει τον επιλεγμένο λογαριασμό.'}</small></div><button type="button" className="icon-button" aria-label="Κλείσιμο κίνησης δανεικών" onClick={close}><X/></button></div><div className="settings-form editor-grid"><label><span>Πρόσωπο</span><input data-autofocus="true" list="known-people" value={person} onChange={e=>setPerson(e.target.value)} placeholder="Όνομα"/><datalist id="known-people">{rows.map(row=><option key={row.person} value={row.person}/>)}</datalist></label><label><span>Ποσό</span><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value.replace(',','.'))} placeholder="0,00"/></label><label><span>Ημερομηνία</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>{kind==='lending'?'Πληρωμή από':'Επιστροφή σε'}</span><select value={account} onChange={e=>setAccount(e.target.value)}>{accounts.map(item=><option key={item.id} value={item.id}>{accountDisplayName(data,item.id)}</option>)}</select></label><label className="wide"><span>Σχόλιο <em>προαιρετικό</em></span><input value={note} onChange={e=>setNote(e.target.value)}/></label></div>{error?<div className="form-error" role="alert">{error}</div>:null}<div className="editor-actions"><button type="button" className="secondary" onClick={close}>Ακύρωση</button><button type="button" className="save-button" onClick={submit}>Καταχώριση</button></div></section></div>:null}</div>;
}
