import { CalendarClock, Pencil, Plus, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import { money } from '../lib/format';
import { recurringDraftError } from '../lib/inputSemantics';
import type { FinanceData, RecurringItem } from '../types';

export function RecurringPage({data,onUpsert,onDelete}:{data:FinanceData;onUpsert:(item:RecurringItem)=>void;onDelete:(id:string)=>void}){
  const items=[...(data.seed.recurring??[]).map(r=>data.state.recurringOverrides?.[r.id]??r),...(data.state.recurringCustom??[])].filter(r=>r.active);
  const [edit,setEdit]=useState<RecurringItem|null>(null);
  const [editError,setEditError]=useState('');
  const startNew=()=>{setEditError('');setEdit({id:`rec-${Date.now()}`,name:'',amount:0,day:null,accountId:data.state.settings.defaultExpenseAccount,category:'Σταθερά έξοδα',active:true,source:'user'})};
  const startEdit=(item:RecurringItem)=>{setEditError('');setEdit({...item})};
  const save=()=>{if(!edit)return;const error=recurringDraftError(edit);if(error){setEditError(error);return}onUpsert(edit);setEdit(null);setEditError('')};
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">SCHEDULED</span><h1>Πάγια & Συνδρομές</h1><p>Προγραμματισμένα ποσά μένουν ξεχωριστά από πραγματικές πληρωμές για να μην υπάρχει διπλή μέτρηση.</p></div><button className="save-button" onClick={startNew}><Plus size={17}/> Νέο πάγιο</button></section><section className="panel neo-raised"><div className="recurring-table">{items.map(r=><div key={r.id}><span className="rec-icon"><CalendarClock/></span><div><b>{r.name}</b><small>{r.category} · {r.day?`${r.day} του μήνα`:'ημερομηνία μη ορισμένη'}</small></div><strong>{money.format(r.amount)}</strong><em>{r.accountId}</em><span className="row-actions"><button onClick={()=>startEdit(r)}><Pencil/></button><button className="danger" onClick={()=>onDelete(r.id)}><Trash2/></button></span></div>)}</div></section>{edit?<section className="panel neo-raised inline-editor"><div className="panel-head"><div><span>{items.some(i=>i.id===edit.id)?'Επεξεργασία παγίου':'Νέο πάγιο'}</span><small>Οι αλλαγές αποθηκεύονται στο Supabase/PostgreSQL.</small></div><button className="icon-button" onClick={()=>{setEdit(null);setEditError('')}}><X/></button></div><div className="settings-form editor-grid"><label><span>Όνομα</span><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label><span>Ποσό</span><input type="number" min="0.01" step="0.01" value={edit.amount||''} onChange={e=>setEdit({...edit,amount:Number(e.target.value)})}/></label><label><span>Ημέρα μήνα</span><input type="number" min="1" max="31" step="1" value={edit.day??''} onChange={e=>setEdit({...edit,day:e.target.value?Number(e.target.value):null})}/></label><label><span>Λογαριασμός</span><select value={edit.accountId} onChange={e=>setEdit({...edit,accountId:e.target.value})}>{data.seed.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span>Κατηγορία</span><select value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}>{data.state.settings.expenseCategories.map(c=><option key={c}>{c}</option>)}</select></label></div>{editError?<div className="form-error">{editError}</div>:null}<div className="editor-actions"><button className="secondary" onClick={()=>{setEdit(null);setEditError('')}}>Ακύρωση</button><button className="save-button" onClick={save}>Αποθήκευση</button></div></section>:null}</div>}
