import { Bar, BarChart, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CircleCheck, CreditCard, Eye, EyeOff, HandCoins, ListChecks, PiggyBank, TriangleAlert } from 'lucide-react';
import { useMemo, useState } from 'react';
import { AnimatedAmount } from '../components/AnimatedAmount';
import { FinanceIcon } from '../components/FinanceIcon';
import { money } from '../lib/format';
import { categoryMomentum, operationalReportSnapshot, primaryAccountSeries, reportFlowSeries, reportInsightModel } from '../lib/reports';
import { SAVING_SOURCE_LABELS } from '../lib/savings';
import { accountDisplayName } from '../lib/ui';
import type { FinanceData } from '../types';

const change=(current:number,previous:number)=>previous===0?(current===0?0:null):((current-previous)/Math.abs(previous))*100;
const changeLabel=(value:number|null)=>value===null?'Νέα βάση':`${value>=0?'+':''}${Math.round(value)}%`;
const percent=(value:number|null,digits=0)=>value===null?'—':`${(value*100).toFixed(digits)}%`;
const directionText=(value:number)=>value>=0?'πάνω':'κάτω';

export function ReportsPage({data,month}:{data:FinanceData;month:string}){
 const snapshot=operationalReportSnapshot(data,month);const insights=reportInsightModel(data,month);const series=reportFlowSeries(data,month,6);const accountSeries=primaryAccountSeries(data,month);const momentum=categoryMomentum(data,month,12);const [accountsVisible,setAccountsVisible]=useState(false);const budget=snapshot.budget;const budgetValue=budget>0?snapshot.budgetRemaining:0;
 const comparisons=[{label:'Έσοδα',value:change(snapshot.flow.income,snapshot.previous.income)},{label:'Έξοδα',value:change(snapshot.flow.expense,snapshot.previous.expense)},{label:'Αποταμίευση',value:change(snapshot.flow.saving,snapshot.previous.saving)}];
 const callouts=useMemo(()=>{
   const rows:Array<{title:string;detail:string;tone:'positive'|'negative'|'neutral'}>=[];
   if(insights.sufficientExpenseHistory&&insights.expenseVsTrailingAverage!==null){const delta=Math.abs(insights.expenseVsTrailingAverage);rows.push({title:`Έξοδα ${Math.round(delta*100)}% ${directionText(insights.expenseVsTrailingAverage)} από τον πρόσφατο μέσο όρο`,detail:`Μέσος όρος 3 προηγούμενων μηνών: ${money.format(insights.trailingExpenseAverage)}.`,tone:insights.expenseVsTrailingAverage>0?'negative':'positive'})}
   else rows.push({title:'Δεν υπάρχει ακόμη αρκετό ιστορικό εξόδων',detail:'Χρειάζονται προηγούμενοι μήνες με έξοδα για αξιόπιστη σύγκριση με πρόσφατο μέσο όρο.',tone:'neutral'});
   if(insights.topCategory?.share!==null&&insights.topCategory){rows.push({title:`Μεγαλύτερη κατηγορία: ${insights.topCategory.name}`,detail:`${money.format(insights.topCategory.value)} · ${Math.round(insights.topCategory.share*100)}% των εξόδων αυτής της περιόδου.`,tone:'neutral'})}
   if(insights.savingsRate!==null){const previous=insights.previousSavingsRate;rows.push({title:`Ρυθμός αποταμίευσης ${percent(insights.savingsRate)}`,detail:previous===null?'Δεν υπάρχει συγκρίσιμος προηγούμενος μήνας με έσοδα.':`Προηγούμενος μήνας: ${percent(previous)}.`,tone:previous!==null&&insights.savingsRate<previous?'negative':'positive'})}
   if(insights.recurringBurden!==null)rows.push({title:`Πάγια ${percent(insights.recurringBurden)} των εσόδων`,detail:`Ενεργές μηνιαίες υποχρεώσεις: ${money.format(snapshot.recurring)}.`,tone:insights.recurringBurden>.5?'negative':'neutral'});
   return rows.slice(0,5);
 },[insights,snapshot.recurring]);
 return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">ΑΝΑΦΟΡΕΣ</span><h1>Αναφορές</h1><p>Σύγκριση της τρέχουσας περιόδου με το πρόσφατο ιστορικό, τις υποχρεώσεις και τις κύριες πηγές μεταβολής — χωρίς υποθέσεις για αιτίες που δεν καταγράφονται στα δεδομένα.</p></div></section>
 <section className="report-kpis useful-report-kpis"><div className="neo-raised"><span>Έσοδα</span><b className="positive"><AnimatedAmount value={snapshot.flow.income}/></b></div><div className="neo-raised"><span>Έξοδα</span><b className="negative"><AnimatedAmount value={snapshot.flow.expense}/></b></div><div className="neo-raised"><span>Ρυθμός αποταμίευσης</span><b>{percent(insights.savingsRate)}</b><small><AnimatedAmount value={snapshot.flow.saving}/> στην άκρη</small></div><div className="neo-raised"><span>{budget>0?(budgetValue>=0?'Υπόλοιπο budget':'Υπέρβαση budget'):'Budget'}</span><b className={budget>0&&budgetValue<0?'negative':''}>{budget>0?<AnimatedAmount value={Math.abs(budgetValue)}/>:'Δεν έχει οριστεί'}</b></div></section>

 <section className="report-comparison neo-flat"><span>Σε σχέση με τον προηγούμενο μήνα</span>{comparisons.map(item=><div key={item.label}><b>{item.label}</b><strong className={item.value!==null&&((item.label==='Έξοδα'&&item.value>0)||(item.label!=='Έξοδα'&&item.value<0))?'negative':'positive'}>{changeLabel(item.value)}</strong></div>)}</section>
 <section className="panel neo-raised"><div className="panel-head"><div><span>Τάση & σύγκριση 6 μηνών</span><small>Έσοδα, έξοδα και αποταμίευση ανά μήνα. Οι συγκρίσεις περιγράφουν μεταβολές, όχι αιτίες.</small></div></div><div aria-hidden="true"><ResponsiveContainer width="100%" height={320}><ComposedChart data={series} margin={{left:5,right:15}}><CartesianGrid stroke="#dbe4f0" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:10,fill:'#52627d'}}/><YAxis tick={{fontSize:10,fill:'#52627d'}}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Bar dataKey="income" name="Έσοδα" fill="#187852" radius={[5,5,0,0]}/><Bar dataKey="expense" name="Έξοδα" fill="#b32942" radius={[5,5,0,0]}/><Line type="monotone" dataKey="saving" name="Αποταμίευση" stroke="#147c95" strokeWidth={2.4} dot={{r:3}}/></ComposedChart></ResponsiveContainer></div><details className="chart-alt"><summary>Ποσά 6 μηνών σε κείμενο</summary><ul className="chart-alt-list report-flow-alt">{series.map(row=><li key={row.month}><span>{row.label}</span><b>Έσοδα {money.format(row.income)} · Έξοδα {money.format(row.expense)} · Αποταμίευση {money.format(row.saving)}</b></li>)}</ul></details></section>

 <section className="panel neo-raised report-insights" aria-labelledby="report-insights-title"><div className="panel-head"><div><span id="report-insights-title">Χρήσιμες παρατηρήσεις</span><small>Μόνο αριθμητικές συγκρίσεις που προκύπτουν από τις καταγεγραμμένες κινήσεις.</small></div></div><div className="report-insight-grid">{callouts.map((item,index)=><article key={`${item.title}-${index}`} className={`report-insight ${item.tone}`}>{item.tone==='negative'?<TriangleAlert aria-hidden="true"/>:item.tone==='positive'?<CircleCheck aria-hidden="true"/>:<ListChecks aria-hidden="true"/>}<div><b>{item.title}</b><small>{item.detail}</small></div></article>)}</div></section>

 <section className="panel neo-raised"><div className="panel-head"><div><span>Υποχρεώσεις & ρευστότητα</span><small>Πάγια, πιστωτικές και ποσά προς είσπραξη στο ίδιο πλαίσιο.</small></div></div><div className="report-operations-grid"><article className="panel neo-flat"><ListChecks/><span>Ενεργά πάγια / μήνα</span><b><AnimatedAmount value={snapshot.recurring}/></b><small>{insights.recurringBurden===null?'Χωρίς έσοδα για ποσοστιαία σύγκριση':`${percent(insights.recurringBurden)} των εσόδων`}</small></article><article className="panel neo-flat"><CreditCard/><span>Χρήση πιστωτικών</span><b>{snapshot.creditLimit>0?`${Math.round(snapshot.creditUsage*100)}%`:'Χωρίς όριο'}</b><small><AnimatedAmount value={snapshot.creditDebt}/> οφειλή · <AnimatedAmount value={snapshot.creditAvailable}/> διαθέσιμο</small></article><article className="panel neo-flat"><HandCoins/><span>Προς είσπραξη</span><b><AnimatedAmount value={snapshot.receivables}/></b><small>Καταγεγραμμένες απαιτήσεις προς άλλα πρόσωπα</small></article></div>{snapshot.creditCardRows.length?<details className="credit-report-drilldown"><summary>Ανάλυση πιστωτικών καρτών</summary><div className="credit-report-list">{snapshot.creditCardRows.map(card=><div key={card.id}><span><b>{card.nickname}</b><small>{card.active?'Ενεργή':'Αρχειοθετημένη'}</small></span><span>Οφειλή <b>{money.format(card.debt)}</b></span><span>{card.limit>0?`Χρήση ${Math.round(card.usage*100)}% · Όριο ${money.format(card.limit)}`:'Χωρίς ενεργό όριο'}</span></div>)}</div></details>:<div className="empty-inline">Δεν υπάρχουν πιστωτικές κάρτες για ανάλυση.</div>}</section>

 <section className="panel neo-raised"><div className="panel-head"><div><span>Κατηγορίες & μεταβολή</span><small>Καθαρά έξοδα της επιλεγμένης περιόδου και σύγκριση με τον προηγούμενο μήνα όταν υπάρχει βάση.</small></div></div>{momentum.length?<><div aria-hidden="true"><ResponsiveContainer width="100%" height={Math.max(320,momentum.length*34)}><BarChart data={momentum} layout="vertical" margin={{left:30,right:35}}><CartesianGrid stroke="#dbe4f0" strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:10,fill:'#52627d'}}/><YAxis type="category" dataKey="name" width={170} tick={{fontSize:10,fill:'#52627d'}}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Bar dataKey="value" fill="#2f6fed" radius={[0,7,7,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><div className="category-momentum-list">{momentum.map(row=>{const [category,subcategory]=row.name.split(' › ');return <div key={row.name}><span className="semantic-list-title"><FinanceIcon kind="expense" category={category} subcategory={subcategory} size={14}/>{row.name}</span><b>{money.format(row.value)}</b><small>{row.change===null?'Νέα βάση':`${row.change>=0?'+':''}${Math.round(row.change*100)}% από τον προηγούμενο μήνα`}</small></div>})}</div></>:<div className="empty-state">Δεν υπάρχουν έξοδα για την επιλεγμένη περίοδο.</div>}</section>

 <section className="panel neo-raised"><div className="panel-head"><div><span>Υπόλοιπα βασικών λογαριασμών</span><small>Μισθοδοσίας και Αποταμιευτηρίου στο τέλος κάθε μήνα.</small></div><button type="button" className="text-button report-eye" aria-pressed={accountsVisible} onClick={()=>setAccountsVisible(value=>!value)}>{accountsVisible?<EyeOff size={15}/>:<Eye size={15}/>} {accountsVisible?'Απόκρυψη':'Εμφάνιση'}</button></div>{accountsVisible?<><div aria-hidden="true"><ResponsiveContainer width="100%" height={285}><ComposedChart data={accountSeries}><CartesianGrid stroke="#dbe4f0" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:10,fill:'#52627d'}}/><YAxis tick={{fontSize:10,fill:'#52627d'}}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Line type="monotone" dataKey="piraeus-payroll" name={accountDisplayName(data,'piraeus-payroll')} stroke="#2f6fed" strokeWidth={2.4}/><Line type="monotone" dataKey="piraeus-savings" name={accountDisplayName(data,'piraeus-savings')} stroke="#147c95" strokeWidth={2.4}/></ComposedChart></ResponsiveContainer></div><div className="account-report-list">{accountSeries.map(row=><div key={String(row.month)}><span>{String(row.label)}</span><b>{accountDisplayName(data,'piraeus-payroll')}: {money.format(Number(row['piraeus-payroll']))}</b><b>{accountDisplayName(data,'piraeus-savings')}: {money.format(Number(row['piraeus-savings']))}</b></div>)}</div></>:<div className="private-report-placeholder"><Eye/><span>Τα υπόλοιπα είναι κρυμμένα. Πάτησε «Εμφάνιση» για να δεις την εξέλιξή τους.</span></div>}</section>

 <section className="panel neo-raised savings-report-breakdown"><div className="panel-head"><div><span>Πηγές αποταμίευσης</span><small>Πώς μοιράστηκε η αποταμίευση της περιόδου.</small></div></div>{Object.entries(snapshot.savings.bySource).map(([source,value])=><div key={source}><span>{SAVING_SOURCE_LABELS[source as keyof typeof SAVING_SOURCE_LABELS]}</span><b><AnimatedAmount value={value}/></b></div>)}<div className="savings-total-row"><span>Σύνολο</span><b><AnimatedAmount value={snapshot.savings.total}/></b></div></section></div>
}
