import { Bar, BarChart, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownRight, ArrowUpRight, CircleCheck, CreditCard, Eye, EyeOff, HandCoins, ListChecks, PiggyBank, TriangleAlert, WalletCards } from 'lucide-react';
import { useMemo, useState } from 'react';
import { AnimatedAmount } from '../components/AnimatedAmount';
import { BudgetProgressPanel } from '../components/BudgetProgressPanel';
import { FinanceIcon } from '../components/FinanceIcon';
import { money } from '../lib/format';
import { categoryMomentum, operationalReportSnapshot, primaryAccountSeries, reportFlowSeries, reportInsightModel } from '../lib/reports';
import { SAVING_SOURCE_LABELS } from '../lib/savings';
import { accountDisplayName } from '../lib/ui';
import type { FinanceData } from '../types';

const change=(current:number,previous:number)=>previous===0?(current===0?0:null):((current-previous)/Math.abs(previous))*100;
const changeLabel=(value:number|null)=>value===null?'Νέα βάση':`${value>=0?'+':''}${Math.round(value)}%`;
const percent=(value:number|null,digits=0)=>value===null?'—':`${(value*100).toFixed(digits)}%`;
const directionText=(value:number)=>value>=0?'πάνω':'κάτω';
const comparisonTone=(label:string,value:number|null)=>value===null?'neutral':((label==='Έξοδα'&&value>0)||(label!=='Έξοδα'&&value<0))?'negative':'positive';

export function ReportsPage({data,month}:{data:FinanceData;month:string}){
 const snapshot=operationalReportSnapshot(data,month);const insights=reportInsightModel(data,month);const series=reportFlowSeries(data,month,6);const accountSeries=primaryAccountSeries(data,month);const momentum=categoryMomentum(data,month,12);const [accountsVisible,setAccountsVisible]=useState(false);const budget=snapshot.budget;const budgetValue=budget>0?snapshot.budgetRemaining:0;const netFlow=snapshot.flow.income-snapshot.flow.expense;const creditPercent=snapshot.creditLimit>0?snapshot.creditUsage:null;
 const comparisons=[{label:'Έσοδα',value:change(snapshot.flow.income,snapshot.previous.income)},{label:'Έξοδα',value:change(snapshot.flow.expense,snapshot.previous.expense)},{label:'Αποταμίευση',value:change(snapshot.flow.saving,snapshot.previous.saving)}];
 const callouts=useMemo(()=>{
   const rows:Array<{title:string;detail:string;tone:'positive'|'negative'|'neutral'}>=[];
   if(insights.sufficientExpenseHistory&&insights.expenseVsTrailingAverage!==null){const delta=Math.abs(insights.expenseVsTrailingAverage);rows.push({title:`Έξοδα ${Math.round(delta*100)}% ${directionText(insights.expenseVsTrailingAverage)} από τον πρόσφατο μέσο όρο`,detail:`Μέσος όρος 3 προηγούμενων μηνών: ${money.format(insights.trailingExpenseAverage)}.`,tone:insights.expenseVsTrailingAverage>0?'negative':'positive'})}
   else rows.push({title:'Δεν υπάρχει ακόμη αρκετό ιστορικό εξόδων',detail:'Χρειάζονται προηγούμενοι μήνες με έξοδα για αξιόπιστη σύγκριση με πρόσφατο μέσο όρο.',tone:'neutral'});
   if(insights.topCategory?.share!==null&&insights.topCategory){rows.push({title:`Μεγαλύτερη κατηγορία: ${insights.topCategory.name}`,detail:`${money.format(insights.topCategory.value)} · ${Math.round(insights.topCategory.share*100)}% των εξόδων αυτής της περιόδου.`,tone:'neutral'})}
   if(insights.savingsRate!==null){const previous=insights.previousSavingsRate;rows.push({title:`Ρυθμός αποταμίευσης ${percent(insights.savingsRate)}`,detail:previous===null?'Δεν υπάρχει συγκρίσιμος προηγούμενος μήνας με έσοδα.':`Προηγούμενος μήνας: ${percent(previous)}.`,tone:previous!==null&&insights.savingsRate<previous?'negative':'positive'})}
   if(insights.recurringBurden!==null)rows.push({title:`Πάγια ${percent(insights.recurringBurden)} των εσόδων`,detail:`Ενεργές μηνιαίες υποχρεώσεις: ${money.format(snapshot.recurring)}.`,tone:insights.recurringBurden>.5?'negative':'neutral'});
   return rows.slice(0,5);
 },[insights,snapshot.recurring]);
 return <div className="page-stack reports-dashboard">
  <section className="page-heading report-heading"><div><span className="eyebrow">ΑΝΑΦΟΡΕΣ · {month}</span><h1>Αναφορές · Η οικονομική εικόνα του μήνα</h1><p>Τάσεις, μεταβολές, δεσμεύσεις και συγκέντρωση εξόδων σε μία ιεραρχημένη εικόνα. Οι συγκρίσεις περιγράφουν μόνο όσα καταγράφονται στα δεδομένα.</p></div></section>

  <section className="report-executive neo-raised" aria-label="Σύνοψη περιόδου">
   <div className="report-executive-main"><span>Καθαρή λειτουργική ροή</span><b className={netFlow<0?'negative':'positive'}><AnimatedAmount value={netFlow}/></b><small>Έσοδα μείον έξοδα της επιλεγμένης περιόδου</small></div>
   <div className="report-executive-rate"><span>Ρυθμός αποταμίευσης</span><strong>{percent(insights.savingsRate)}</strong><small><AnimatedAmount value={snapshot.flow.saving}/> αποταμίευση</small></div>
   <div className="report-executive-comparisons" aria-label="Μεταβολές από προηγούμενο μήνα">{comparisons.map(item=>{const tone=comparisonTone(item.label,item.value);return <div key={item.label} className={`report-delta ${tone}`}><span>{item.label}</span><b>{item.value!==null&&item.value<0?<ArrowDownRight aria-hidden="true"/>:<ArrowUpRight aria-hidden="true"/>}{changeLabel(item.value)}</b></div>})}</div>
  </section>

  <section className="report-kpis useful-report-kpis report-kpis-v2" aria-label="Βασικοί δείκτες">
   <article className="neo-raised"><span>Έσοδα</span><b className="positive"><AnimatedAmount value={snapshot.flow.income}/></b><small>Προηγούμενος: {money.format(snapshot.previous.income)}</small></article>
   <article className="neo-raised"><span>Έξοδα</span><b className="negative"><AnimatedAmount value={snapshot.flow.expense}/></b><small>Προηγούμενος: {money.format(snapshot.previous.expense)}</small></article>
   <article className="neo-raised"><span>{budget>0?(budgetValue>=0?'Υπόλοιπο γενικού budget':'Υπέρβαση γενικού budget'):'Γενικό budget'}</span><b className={budget>0&&budgetValue<0?'negative':''}>{budget>0?<AnimatedAmount value={Math.abs(budgetValue)}/>:'Δεν έχει οριστεί'}</b><small>{budget>0?`Όριο συμβατότητας ${money.format(budget)}`:'Ορίζεται από τις Ρυθμίσεις'}</small></article>
   <article className="neo-raised"><span>Προς είσπραξη</span><b><AnimatedAmount value={snapshot.receivables}/></b><small>Καταγεγραμμένες απαιτήσεις</small></article>
  </section>

  <BudgetProgressPanel data={data} month={month}/>

  <section className="report-primary-grid">
   <article className="panel neo-raised report-flow-panel"><div className="panel-head"><div><span>Ροή 6 μηνών</span><small>Έσοδα, έξοδα και αποταμίευση. Το γράφημα δείχνει κατεύθυνση και μέγεθος, όχι αιτιότητα.</small></div></div><div className="report-chart-frame" aria-hidden="true"><ResponsiveContainer width="100%" height={340}><ComposedChart data={series} margin={{left:4,right:12,top:8,bottom:0}}><CartesianGrid stroke="#dbe4f0" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:11,fill:'#52627d'}}/><YAxis tick={{fontSize:10,fill:'#52627d'}}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Bar dataKey="income" name="Έσοδα" fill="#187852" radius={[6,6,0,0]}/><Bar dataKey="expense" name="Έξοδα" fill="#b32942" radius={[6,6,0,0]}/><Line type="monotone" dataKey="saving" name="Αποταμίευση" stroke="#147c95" strokeWidth={3} dot={{r:3.5}}/></ComposedChart></ResponsiveContainer></div><details className="chart-alt"><summary>Ποσά 6 μηνών σε κείμενο</summary><ul className="chart-alt-list report-flow-alt">{series.map(row=><li key={row.month}><span>{row.label}</span><b>Έσοδα {money.format(row.income)} · Έξοδα {money.format(row.expense)} · Αποταμίευση {money.format(row.saving)}</b></li>)}</ul></details></article>
   <aside className="panel neo-raised report-insights report-insights-rail" aria-labelledby="report-insights-title"><div className="panel-head"><div><span id="report-insights-title">Τι ξεχωρίζει</span><small>Αριθμητικές παρατηρήσεις με σαφή βάση σύγκρισης.</small></div></div><div className="report-insight-grid">{callouts.map((item,index)=><article key={`${item.title}-${index}`} className={`report-insight ${item.tone}`}>{item.tone==='negative'?<TriangleAlert aria-hidden="true"/>:item.tone==='positive'?<CircleCheck aria-hidden="true"/>:<ListChecks aria-hidden="true"/>}<div><b>{item.title}</b><small>{item.detail}</small></div></article>)}</div></aside>
  </section>

  <section className="panel neo-raised report-pressure"><div className="panel-head"><div><span>Πίεση & υποχρεώσεις</span><small>Μηνιαίες δεσμεύσεις και διαθέσιμο περιθώριο σε μία ενότητα.</small></div></div><div className="report-operations-grid report-pressure-grid">
   <article className="report-pressure-card"><div className="report-pressure-icon"><ListChecks/></div><div><span>Ενεργά πάγια / μήνα</span><b><AnimatedAmount value={snapshot.recurring}/></b><small>{insights.recurringBurden===null?'Χωρίς έσοδα για ποσοστιαία σύγκριση':`${percent(insights.recurringBurden)} των εσόδων`}</small></div>{insights.recurringBurden!==null?<div className="report-meter" role="progressbar" aria-label="Ποσοστό παγίων επί των εσόδων" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100,Math.round(insights.recurringBurden*100))} aria-valuetext={`${Math.round(insights.recurringBurden*100)}%`}><i style={{width:`${Math.min(100,insights.recurringBurden*100)}%`}}/></div>:null}</article>
   <article className={`report-pressure-card ${creditPercent!==null&&creditPercent>1?'over-limit':''}`}><div className="report-pressure-icon"><CreditCard/></div><div><span>Χρήση πιστωτικών</span><b>{creditPercent!==null?`${Math.round(creditPercent*100)}%`:'Χωρίς όριο'}</b><small><AnimatedAmount value={snapshot.creditDebt}/> οφειλή · <AnimatedAmount value={snapshot.creditAvailable}/> διαθέσιμο</small></div>{creditPercent!==null?<div className="report-meter" role="progressbar" aria-label="Συνολική χρήση πιστωτικών" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100,Math.round(creditPercent*100))} aria-valuetext={`${Math.round(creditPercent*100)}% χρήση πιστωτικών${creditPercent>1?' · πάνω από το συνολικό όριο':''}`}><i style={{width:`${Math.min(100,creditPercent*100)}%`}}/></div>:null}</article>
   <article className="report-pressure-card"><div className="report-pressure-icon"><HandCoins/></div><div><span>Προς είσπραξη</span><b><AnimatedAmount value={snapshot.receivables}/></b><small>Καταγεγραμμένες απαιτήσεις προς άλλα πρόσωπα</small></div></article>
  </div>{snapshot.creditCardRows.length?<details className="credit-report-drilldown"><summary>Ανάλυση πιστωτικών καρτών</summary><div className="credit-report-list">{snapshot.creditCardRows.map(card=><div key={card.id}><span><b>{card.nickname}</b><small>{card.active?'Ενεργή':'Αρχειοθετημένη'}</small></span><span>Οφειλή <b>{money.format(card.debt)}</b></span><span>{card.limit>0?`Χρήση ${Math.round(card.usage*100)}% · Όριο ${money.format(card.limit)}`:'Χωρίς ενεργό όριο'}</span></div>)}</div></details>:<div className="empty-inline">Δεν υπάρχουν πιστωτικές κάρτες για ανάλυση.</div>}</section>

  <section className="panel neo-raised report-category-panel"><div className="panel-head"><div><span>Πού πηγαίνουν τα έξοδα</span><small>Κατηγορίες της περιόδου με μεταβολή έναντι του προηγούμενου μήνα όταν υπάρχει συγκρίσιμη βάση.</small></div></div>{momentum.length?<div className="report-category-layout"><div className="report-category-chart" aria-hidden="true"><ResponsiveContainer width="100%" height={Math.max(330,momentum.length*34)}><BarChart data={momentum} layout="vertical" margin={{left:18,right:28}}><CartesianGrid stroke="#dbe4f0" strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:10,fill:'#52627d'}}/><YAxis type="category" dataKey="name" width={165} tick={{fontSize:10,fill:'#52627d'}}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Bar dataKey="value" fill="#2f6fed" radius={[0,7,7,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><div className="category-momentum-list report-category-list">{momentum.map(row=>{const [category,subcategory]=row.name.split(' › ');return <div key={row.name}><span className="semantic-list-title"><FinanceIcon settings={data.state.settings} kind="expense" category={category} subcategory={subcategory} size={14}/>{row.name}</span><b>{money.format(row.value)}</b><small>{row.change===null?'Νέα βάση':`${row.change>=0?'+':''}${Math.round(row.change*100)}% από τον προηγούμενο μήνα`}</small></div>})}</div></div>:<div className="empty-state">Δεν υπάρχουν έξοδα για την επιλεγμένη περίοδο.</div>}</section>

  <section className="report-secondary-grid">
   <article className="panel neo-raised"><div className="panel-head"><div><span>Βασικοί λογαριασμοί</span><small>Εξέλιξη Μισθοδοσίας και Αποταμιευτηρίου στο τέλος κάθε μήνα.</small></div><button type="button" className="text-button report-eye" aria-pressed={accountsVisible} onClick={()=>setAccountsVisible(value=>!value)}>{accountsVisible?<EyeOff size={15}/>:<Eye size={15}/>} {accountsVisible?'Απόκρυψη':'Εμφάνιση'}</button></div>{accountsVisible?<><div aria-hidden="true"><ResponsiveContainer width="100%" height={285}><ComposedChart data={accountSeries}><CartesianGrid stroke="#dbe4f0" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:10,fill:'#52627d'}}/><YAxis tick={{fontSize:10,fill:'#52627d'}}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Line type="monotone" dataKey="piraeus-payroll" name={accountDisplayName(data,'piraeus-payroll')} stroke="#2f6fed" strokeWidth={2.4}/><Line type="monotone" dataKey="piraeus-savings" name={accountDisplayName(data,'piraeus-savings')} stroke="#147c95" strokeWidth={2.4}/></ComposedChart></ResponsiveContainer></div><div className="account-report-list">{accountSeries.map(row=><div key={String(row.month)}><span>{String(row.label)}</span><b>{accountDisplayName(data,'piraeus-payroll')}: {money.format(Number(row['piraeus-payroll']))}</b><b>{accountDisplayName(data,'piraeus-savings')}: {money.format(Number(row['piraeus-savings']))}</b></div>)}</div></>:<div className="private-report-placeholder"><Eye/><span>Τα υπόλοιπα είναι κρυμμένα. Πάτησε «Εμφάνιση» για να δεις την εξέλιξή τους.</span></div>}</article>
   <article className="panel neo-raised savings-report-breakdown report-savings-sources"><div className="panel-head"><div><span>Πηγές αποταμίευσης</span><small>Πώς σχηματίστηκε η αποταμίευση της περιόδου.</small></div><PiggyBank aria-hidden="true"/></div>{Object.entries(snapshot.savings.bySource).map(([source,value])=><div key={source}><span>{SAVING_SOURCE_LABELS[source as keyof typeof SAVING_SOURCE_LABELS]}</span><b><AnimatedAmount value={value}/></b></div>)}<div className="savings-total-row"><span><WalletCards size={16} aria-hidden="true"/> Σύνολο</span><b><AnimatedAmount value={snapshot.savings.total}/></b></div></article>
  </section>
 </div>
}
