import { Database, Download, FileJson, Save, ShieldCheck } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { allAccounts } from '../lib/domain';
import { MAX_FINANCE_DOCUMENT_BYTES } from '../lib/limits';
import type { FinanceData, FinanceSettings } from '../types';

function uniqueLines(raw:string){return [...new Set(raw.split(/[\n,]+/).map(value=>value.trim()).filter(Boolean))];}

export function SettingsPage({data,filePath,lastSavedAt,onImport,onBackup,onSettings}:{data:FinanceData;filePath:string;lastSavedAt:string|null;onImport:(d:FinanceData)=>Promise<void>;onBackup:()=>Promise<{path:string}>;onSettings:(settings:FinanceData['state']['settings'])=>void}){
 const ref=useRef<HTMLInputElement|null>(null);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[dirty,setDirty]=useState(false);const[draft,setDraft]=useState<FinanceSettings>(()=>({...data.state.settings,accountNames:{...data.state.settings.accountNames},expenseCategories:[...data.state.settings.expenseCategories],incomeCategories:[...data.state.settings.incomeCategories]}));
 const accounts=allAccounts(data).filter(account=>account.kind!=='credit');
 useEffect(()=>{if(!dirty)setDraft({...data.state.settings,accountNames:{...data.state.settings.accountNames},expenseCategories:[...data.state.settings.expenseCategories],incomeCategories:[...data.state.settings.incomeCategories]})},[data.state.settings,dirty]);
 const change=(next:FinanceSettings)=>{setDraft(next);setDirty(true);setMessage('')};
 const importFile=async(file?:File)=>{if(!file||busy)return;if(file.size>MAX_FINANCE_DOCUMENT_BYTES){setMessage('Το αρχείο είναι μεγαλύτερο από το υποστηριζόμενο όριο των 4 MB.');if(ref.current)ref.current.value='';return}if(!window.confirm('Η εισαγωγή θα αντικαταστήσει το τρέχον RheomIQ state αφού δημιουργηθεί pre-import backup. Συνέχεια;')){if(ref.current)ref.current.value='';return}setBusy(true);try{await onImport(JSON.parse(await file.text()));setMessage('Η εισαγωγή ολοκληρώθηκε και δημιουργήθηκε pre-import backup.');setDirty(false)}catch(e){setMessage(e instanceof Error?e.message:'Η εισαγωγή απέτυχε.')}finally{setBusy(false);if(ref.current)ref.current.value=''}};
 const backup=async()=>{if(busy)return;setBusy(true);try{const r=await onBackup();setMessage(`Backup: ${r.path}`)}catch(e){setMessage(e instanceof Error?e.message:'Η δημιουργία backup απέτυχε.')}finally{setBusy(false)}};
 const saveSettings=()=>{const budget=draft.monthlyBudget??0;const target=draft.savingsTargetRate??0;const creditLimit=draft.creditLimit??0;if(!Number.isFinite(budget)||budget<0){setMessage('Το μηνιαίο budget πρέπει να είναι μη αρνητικό.');return}if(!Number.isFinite(target)||target<0||target>1){setMessage('Ο στόχος αποταμίευσης πρέπει να είναι από 0% έως 100%.');return}if(!Number.isFinite(creditLimit)||creditLimit<0){setMessage('Το πιστωτικό όριο πρέπει να είναι μη αρνητικό.');return}onSettings(draft);setDirty(false);setMessage('Οι ρυθμίσεις εφαρμόστηκαν και αποθηκεύονται.')};
 const labelFor=(id:string)=>draft.accountNames[id]?.trim()||accounts.find(a=>a.id===id)?.name||id;
 return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">SUPABASE / POSTGRESQL</span><h1>Ρυθμίσεις</h1><p>Τα προσωπικά δεδομένα αποθηκεύονται στο Supabase/PostgreSQL. Οι αλλαγές προτιμήσεων εφαρμόζονται μόνο όταν πατήσεις «Εφαρμογή ρυθμίσεων».</p></div></section><section className="settings-grid"><article className="panel neo-raised"><div className="panel-head"><div><span>Βάση δεδομένων</span><small>{filePath}</small></div><Database/></div><div className="settings-list"><div><span>Schema</span><b>v{data.schemaVersion}</b></div><div><span>Τελευταία αποθήκευση</span><b>{lastSavedAt?new Date(lastSavedAt).toLocaleString('el-GR'):'—'}</b></div><div><span>Legacy transactions</span><b>{data.seed.stats.transactions||data.seed.transactions.length}</b></div><div><span>RheomIQ events</span><b>{data.state.events?.length||0}</b></div></div><div className="settings-actions"><input ref={ref} type="file" accept="application/json,.json" hidden onChange={e=>void importFile(e.target.files?.[0])}/><button type="button" disabled={busy} onClick={()=>ref.current?.click()}><FileJson/> Εισαγωγή JSON</button><button type="button" disabled={busy} onClick={()=>void backup()}><Download/> Δημιουργία backup</button></div>{message?<div className="logic-note compact" role="status" aria-live="polite"><ShieldCheck/><span>{message}</span></div>:null}</article><article className="panel neo-raised"><div className="panel-head"><div><span>Στόχοι & κίνηση</span><small>Οι τιμές αποθηκεύονται μαζί με το PostgreSQL state</small></div></div><div className="settings-form"><label><span>Μηνιαίο budget</span><input type="number" min="0" step="0.01" value={draft.monthlyBudget??0} onChange={e=>change({...draft,monthlyBudget:Number(e.target.value)})}/></label><label><span>Στόχος αποταμίευσης %</span><input type="number" min="0" max="100" step="1" value={Math.round((draft.savingsTargetRate??0)*100)} onChange={e=>change({...draft,savingsTargetRate:Number(e.target.value)/100})}/></label><label><span>Πιστωτικό όριο</span><input type="number" min="0" step="0.01" value={draft.creditLimit??0} onChange={e=>change({...draft,creditLimit:Number(e.target.value)})}/></label><label><span>Motion</span><select value={draft.motion||'system'} onChange={e=>change({...draft,motion:e.target.value as 'system'|'reduced'|'full'})}><option value="system">System preference</option><option value="full">Πλήρες</option><option value="reduced">Reduced motion</option></select></label></div></article></section>
 <section className="panel neo-raised"><div className="panel-head"><div><span>Προεπιλογές Smart Entry</span><small>Οι λογαριασμοί χρησιμοποιούνται αυτόματα για έξοδα, έσοδα και πληρωμές δόσεων.</small></div></div><div className="settings-form editor-grid"><label><span>Προεπιλεγμένος λογαριασμός εξόδων</span><select value={draft.defaultExpenseAccount} onChange={e=>change({...draft,defaultExpenseAccount:e.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{labelFor(a.id)}</option>)}</select></label><label><span>Προεπιλεγμένος λογαριασμός εσόδων</span><select value={draft.defaultIncomeAccount} onChange={e=>change({...draft,defaultIncomeAccount:e.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{labelFor(a.id)}</option>)}</select></label><label><span>Λογαριασμός πληρωμής δόσεων</span><select value={draft.defaultLoanAccount} onChange={e=>change({...draft,defaultLoanAccount:e.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{labelFor(a.id)}</option>)}</select></label></div><div className="account-name-grid">{accounts.map(account=><label key={account.id}><span>Όνομα: {account.name}</span><input value={draft.accountNames[account.id]??''} placeholder={account.name} onChange={e=>change({...draft,accountNames:{...draft.accountNames,[account.id]:e.target.value}})}/></label>)}</div></section>
 <section className="settings-grid"><article className="panel neo-raised category-editor"><div className="panel-head"><div><span>Κατηγορίες εξόδων</span><small>Μία ανά γραμμή ή χωρισμένες με κόμμα</small></div></div><textarea aria-label="Κατηγορίες εξόδων" value={draft.expenseCategories.join('\n')} onChange={e=>change({...draft,expenseCategories:uniqueLines(e.target.value)})}/></article><article className="panel neo-raised category-editor"><div className="panel-head"><div><span>Κατηγορίες εσόδων</span><small>Μία ανά γραμμή ή χωρισμένες με κόμμα</small></div></div><textarea aria-label="Κατηγορίες εσόδων" value={draft.incomeCategories.join('\n')} onChange={e=>change({...draft,incomeCategories:uniqueLines(e.target.value)})}/></article></section>
 <div className="settings-draft-actions"><button type="button" className="secondary" disabled={!dirty} onClick={()=>{setDraft({...data.state.settings,accountNames:{...data.state.settings.accountNames},expenseCategories:[...data.state.settings.expenseCategories],incomeCategories:[...data.state.settings.incomeCategories]});setDirty(false);setMessage('Οι μη εφαρμοσμένες αλλαγές ακυρώθηκαν.')}}>Ακύρωση αλλαγών</button><button type="button" className="save-button" disabled={!dirty} onClick={saveSettings}><Save size={16}/> Εφαρμογή ρυθμίσεων</button></div></div>}
