import { Pencil, Search, Trash2 } from 'lucide-react';
import { useDeferredValue, useMemo, useState } from 'react';
import { categoryPath } from '../lib/categories';
import { allAccounts, effectiveLegacyTransactions, flowImpactEvent, flowImpactLegacy } from '../lib/domain';
import { cleanNote, money, shortDate } from '../lib/format';
import { accountDisplayName, eventKindLabel } from '../lib/ui';
import type { FinanceData } from '../types';

export function TransactionsPage({data,month,onEditEvent,onDeleteEvent}:{data:FinanceData;month:string;onEditEvent:(id:string)=>void;onDeleteEvent:(id:string)=>void}){
  const [query,setQuery]=useState('');const [account,setAccount]=useState('all');const [type,setType]=useState('all');const [message,setMessage]=useState('');const deferred=useDeferredValue(query.toLocaleLowerCase('el-GR'));
  const accounts=allAccounts(data).filter(item=>item.kind!=='credit');
  const sourceRows=useMemo(()=>{const legacy=effectiveLegacyTransactions(data).filter(t=>t.date.startsWith(month)).map(t=>({id:t.id,date:t.date,note:cleanNote(t.note),category:t.category||'Άλλο',subcategory:t.subcategory,accountIds:[t.accountId,t.fromAccountId,t.toAccountId].filter(Boolean) as string[],kind:t.type,amount:t.amount,impact:flowImpactLegacy(data,t),source:'legacy' as const}));const events=(data.state.events??[]).filter(e=>e.date.startsWith(month)&&!['card_purchase','card_payment'].includes(e.kind)).map(e=>({id:e.id,date:e.date,note:e.note,category:e.category||e.kind,subcategory:e.subcategory,accountIds:[...new Set(e.legs.map(l=>l.accountId).filter(id=>id!=='credit-card'))],kind:e.kind,amount:e.amount,impact:flowImpactEvent(e),source:'event' as const}));return [...legacy,...events]},[data,month]);
  const types=useMemo(()=>[...new Set(sourceRows.map(row=>row.kind))].sort((a,b)=>eventKindLabel(a).localeCompare(eventKindLabel(b),'el')),[sourceRows]);
  const rows=useMemo(()=>sourceRows.filter(r=>(account==='all'||r.accountIds.includes(account))&&(type==='all'||r.kind===type)&&(!deferred||`${r.note} ${r.category} ${r.subcategory||''} ${r.kind}`.toLocaleLowerCase('el-GR').includes(deferred))).sort((a,b)=>b.date.localeCompare(a.date)),[sourceRows,account,type,deferred]);
  const remove=(id:string,note:string)=>{if(!window.confirm(`Να διαγραφεί η κίνηση «${note.split('\n')[0]}»; Η αλλαγή θα αποθηκευτεί στη βάση.`))return;onDeleteEvent(id);setMessage('Η κίνηση αφαιρέθηκε από το ledger και αποθηκεύεται.')};
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">ΚΙΝΗΣΕΙΣ</span><h1>Συναλλαγές</h1><p>Καθημερινές τραπεζικές και μετρητές κινήσεις. Η πιστωτική διαχειρίζεται στη δική της ενότητα.</p></div></section><section className="panel neo-raised"><div className="filterbar transaction-searchbar"><label className="filter-label search-filter"><span>Αναζήτηση</span><span className="searchbox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Περιγραφή, κατηγορία ή υποκατηγορία"/></span></label><span>{rows.length} κινήσεις</span></div>{message?<div className="action-status" role="status" aria-live="polite">{message}</div>:null}<div className="semantic-table-wrap"><table className="semantic-table"><caption className="sr-only">Κινήσεις για {month}</caption><thead><tr><th scope="col">Ημερομηνία</th><th scope="col">Περιγραφή</th><th scope="col"><label className="column-filter"><span>Τύπος</span><select aria-label="Φίλτρο τύπου κίνησης" value={type} onChange={e=>setType(e.target.value)}><option value="all">Όλοι</option>{types.map(value=><option key={value} value={value}>{eventKindLabel(value)}</option>)}</select></label></th><th scope="col"><label className="column-filter"><span>Λογαριασμός</span><select aria-label="Φίλτρο λογαριασμού" value={account} onChange={e=>setAccount(e.target.value)}><option value="all">Όλοι</option>{accounts.map(a=><option value={a.id} key={a.id}>{accountDisplayName(data,a.id)}</option>)}</select></label></th><th scope="col" className="amount">Ποσό</th><th scope="col" className="actions">Ενέργειες</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{shortDate(r.date)}</td><td><b>{r.note.split('\n')[0]}</b><small>{categoryPath(r.category,r.subcategory)} · {r.source==='event'?'RheomIQ':'Ιστορικό'}</small></td><td><em className={`flow-pill ${r.kind}`}>{eventKindLabel(r.kind)}</em></td><td>{r.accountIds.map(id=>accounts.find(a=>a.id===id)?.short||accountDisplayName(data,id)).join(' → ')||'—'}</td><td className={`amount ${r.impact.income>0?'positive':r.impact.expense>0?'negative':''}`}>{r.impact.income>0?'+':r.impact.expense>0?'−':''}{money.format(r.amount)}</td><td className="actions"><span className="row-actions">{r.source==='event'?<><button type="button" aria-label={`Επεξεργασία ${r.note.split('\n')[0]}`} onClick={()=>onEditEvent(r.id)}><Pencil/></button><button type="button" aria-label={`Διαγραφή ${r.note.split('\n')[0]}`} className="danger" onClick={()=>remove(r.id,r.note)}><Trash2/></button></>:null}</span></td></tr>)}</tbody></table></div></section></div>;
}
