import { Pencil, Search, Trash2 } from 'lucide-react';
import { useDeferredValue, useMemo, useState } from 'react';
import { allAccounts, effectiveLegacyTransactions, flowImpactEvent, flowImpactLegacy } from '../lib/domain';
import { cleanNote, money, shortDate } from '../lib/format';
import type { FinanceData } from '../types';

export function TransactionsPage({data,month,onEditEvent,onDeleteEvent}:{data:FinanceData;month:string;onEditEvent:(id:string)=>void;onDeleteEvent:(id:string)=>void}){
  const [query,setQuery]=useState(''); const [account,setAccount]=useState('all'); const deferred=useDeferredValue(query.toLocaleLowerCase('el-GR'));
  const accounts=allAccounts(data);
  const rows=useMemo(()=>{const legacy=effectiveLegacyTransactions(data).filter(t=>t.date.startsWith(month)).map(t=>({id:t.id,date:t.date,note:cleanNote(t.note),category:t.category||'Άλλο',accountIds:[t.accountId,t.fromAccountId,t.toAccountId].filter(Boolean) as string[],kind:t.type,amount:t.amount,impact:flowImpactLegacy(data,t),source:'legacy' as const}));const events=(data.state.events??[]).filter(e=>e.date.startsWith(month)).map(e=>({id:e.id,date:e.date,note:e.note,category:e.category||e.kind,accountIds:[...new Set(e.legs.map(l=>l.accountId))],kind:e.kind,amount:e.amount,impact:flowImpactEvent(e),source:'event' as const}));return [...legacy,...events].filter(r=>(account==='all'||r.accountIds.includes(account))&&(!deferred||`${r.note} ${r.category} ${r.kind}`.toLocaleLowerCase('el-GR').includes(deferred))).sort((a,b)=>b.date.localeCompare(a.date));},[data,month,account,deferred]);
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">LEDGER</span><h1>Συναλλαγές</h1><p>Legacy Excel και νέες σύνθετες κινήσεις σε μία συνεπή προβολή.</p></div></section><section className="panel neo-raised"><div className="filterbar"><label className="searchbox"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Αναζήτηση περιγραφής ή κατηγορίας"/></label><select value={account} onChange={e=>setAccount(e.target.value)}><option value="all">Όλοι οι λογαριασμοί</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><span>{rows.length} κινήσεις</span></div><div className="transaction-table"><div className="tr th"><span>Ημερομηνία</span><span>Περιγραφή</span><span>Τύπος</span><span>Λογαριασμοί</span><span>Ποσό</span><span/></div>{rows.map(r=><div className="tr" key={r.id}><span>{shortDate(r.date)}</span><span><b>{r.note.split('\n')[0]}</b><small>{r.category} · {r.source==='event'?'RheomIQ event':'Excel legacy'}</small></span><span><em className={`flow-pill ${r.kind}`}>{r.kind}</em></span><span>{r.accountIds.map(id=>accounts.find(a=>a.id===id)?.short||id).join(' → ')}</span><span className={r.impact.income>0?'positive':r.impact.expense>0?'negative':''}>{r.impact.income>0?'+':r.impact.expense>0?'−':''}{money.format(r.amount)}</span><span className="row-actions">{r.source==='event'?<><button aria-label="Επεξεργασία" onClick={()=>onEditEvent(r.id)}><Pencil/></button><button aria-label="Διαγραφή" className="danger" onClick={()=>onDeleteEvent(r.id)}><Trash2/></button></>:null}</span></div>)}</div></section></div>;
}
