import { CalendarDays, ChevronLeft, ChevronRight, X } from 'lucide-react';
import { useEffect, useId, useMemo, useState, type InputHTMLAttributes, type KeyboardEvent } from 'react';
import { createPortal } from 'react-dom';
import { useModalFocus } from '../hooks/useModalFocus';
import { addCalendarDays, dateOnlyToUtcDate, isValidDateOnly, monthOnlyToUtcDate } from '../lib/dateOnly';
import { localDateString } from '../lib/localDate';
import { shiftReportingMonth } from '../lib/reportingPeriod';
import { IconButton } from './IconButton';

type ChangeLike={target:{value:string}};
type Props=Omit<InputHTMLAttributes<HTMLInputElement>,'value'|'onChange'|'readOnly'|'type'|'min'|'max'> & {value:string;onChange:(event:ChangeLike)=>void;min?:string;max?:string};
const greekDate=new Intl.DateTimeFormat('el-GR',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'});
const greekMonth=new Intl.DateTimeFormat('el-GR',{month:'long',year:'numeric',timeZone:'UTC'});
const greekLong=new Intl.DateTimeFormat('el-GR',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
function isoDate(date:Date){return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}-${String(date.getUTCDate()).padStart(2,'0')}`}
function monthValue(date:Date){return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}`}
function human(value:string){const parsed=dateOnlyToUtcDate(value);return parsed?greekDate.format(parsed):'Επίλεξε ημερομηνία'}
function boundedDate(value:string,min?:string,max?:string){if(min&&value<min)return min;if(max&&value>max)return max;return value}

export function AppDateInput({value,onChange,disabled=false,min,max,'aria-label':ariaLabel,className='',...inputProps}:Props){
 const today=localDateString();const safeMin=isValidDateOnly(min)?min:undefined;const safeMax=isValidDateOnly(max)?max:undefined;const preferredDate=boundedDate(isValidDateOnly(value)?value:today,safeMin,safeMax);const preferredDateObject=dateOnlyToUtcDate(preferredDate)!;const [open,setOpen]=useState(false);const [month,setMonth]=useState(()=>monthValue(preferredDateObject));const id=useId();const dialogId=`owned-date-${id.replace(/:/g,'')}`;const ref=useModalFocus<HTMLElement>(open,`[data-date="${preferredDate}"]`,()=>setOpen(false));
 useEffect(()=>{if(open){const candidate=boundedDate(isValidDateOnly(value)?value:localDateString(),safeMin,safeMax);const parsed=dateOnlyToUtcDate(candidate);if(parsed)setMonth(monthValue(parsed))}},[open,value,safeMin,safeMax]);
 const cells=useMemo(()=>{const monthStart=monthOnlyToUtcDate(month);if(!monthStart)return[];const monthNumber=monthStart.getUTCMonth()+1;const first=new Date(monthStart);const offset=(first.getUTCDay()+6)%7;first.setUTCDate(first.getUTCDate()-offset);return Array.from({length:42},(_,index)=>{const date=new Date(first);date.setUTCDate(first.getUTCDate()+index);const iso=isoDate(date);return {iso,date,inMonth:date.getUTCMonth()===monthNumber-1,disabled:Boolean((safeMin&&iso<safeMin)||(safeMax&&iso>safeMax))}})},[month,safeMin,safeMax]);
 const close=()=>setOpen(false);const choose=(next:string)=>{if(!isValidDateOnly(next)||(safeMin&&next<safeMin)||(safeMax&&next>safeMax))return;onChange({target:{value:next}});close()};
 const shiftMonth=(delta:number)=>setMonth(shiftReportingMonth(month,delta));
 const moveFocus=(event:KeyboardEvent<HTMLElement>,from:string)=>{const delta=event.key==='ArrowLeft'?-1:event.key==='ArrowRight'?1:event.key==='ArrowUp'?-7:event.key==='ArrowDown'?7:0;if(!delta)return;event.preventDefault();const next=addCalendarDays(from,delta);if((safeMin&&next<safeMin)||(safeMax&&next>safeMax))return;const nextDate=dateOnlyToUtcDate(next);if(!nextDate)return;const nextMonth=monthValue(nextDate);if(nextMonth!==month)setMonth(nextMonth);requestAnimationFrame(()=>ref.current?.querySelector<HTMLButtonElement>(`[data-date="${next}"]:not(:disabled)`)?.focus())};
 const portal=open&&typeof document!=='undefined'?createPortal(<div className="owned-popover-backdrop" onMouseDown={close}><section ref={ref} id={dialogId} className="owned-popover owned-date-popover surface-raised" role="dialog" aria-modal="true" aria-label={ariaLabel||'Επιλογή ημερομηνίας'} tabIndex={-1} onMouseDown={event=>event.stopPropagation()}><header><IconButton type="button" aria-label="Προηγούμενος μήνας" title="Προηγούμενος μήνας" onClick={()=>shiftMonth(-1)}><ChevronLeft size={18}/></IconButton><b>{greekMonth.format(monthOnlyToUtcDate(month)!)}</b><div><IconButton type="button" aria-label="Επόμενος μήνας" title="Επόμενος μήνας" onClick={()=>shiftMonth(1)}><ChevronRight size={18}/></IconButton><IconButton type="button" aria-label="Κλείσιμο ημερολογίου" title="Κλείσιμο ημερολογίου" onClick={close}><X size={17}/></IconButton></div></header><div className="owned-weekdays" aria-hidden="true">{['Δε','Τρ','Τε','Πε','Πα','Σα','Κυ'].map(day=><span key={day}>{day}</span>)}</div><div className="owned-calendar-grid" role="grid" aria-label={ariaLabel||'Ημερολόγιο'}>{cells.map(cell=><button type="button" role="gridcell" data-date={cell.iso} data-today={cell.iso===today?'true':undefined} className={`${cell.inMonth?'':'outside'} ${cell.iso===value?'selected':''}`.trim()} aria-selected={cell.iso===value} aria-label={greekLong.format(cell.date)} disabled={cell.disabled} key={cell.iso} onClick={()=>choose(cell.iso)} onKeyDown={event=>moveFocus(event,cell.iso)}>{cell.date.getUTCDate()}</button>)}</div></section></div>,document.body):null;
 return <><span className={`owned-input-shell owned-date-shell ${className}`.trim()}><input {...inputProps} className="app-control owned-input" readOnly disabled={disabled} value={human(value)} aria-label={ariaLabel} aria-haspopup="dialog" aria-expanded={open} aria-controls={dialogId} onClick={()=>!disabled&&setOpen(true)} onKeyDown={event=>{if(disabled)return;if(['Enter',' ','ArrowDown'].includes(event.key)){event.preventDefault();setOpen(true)}}}/><CalendarDays size={16} aria-hidden="true"/></span>{portal}</>;
}
