import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { BarChart3, CreditCard, FileCheck2, Gauge, HandCoins, Landmark, ListChecks, LogOut, Menu, PiggyBank, Plus, RefreshCw, Repeat2, Settings, X } from 'lucide-react';
import { useEffect, useState, type ReactNode } from 'react';
import { useModalFocus } from '../hooks/useModalFocus';
import type { SaveState } from '../hooks/useFinance';

export type PageId = 'dashboard'|'transactions'|'review'|'savings'|'credit'|'lending'|'recurring'|'reports'|'settings';
const nav: Array<{id:PageId; label:string; icon:ReactNode}> = [
  {id:'dashboard',label:'Dashboard',icon:<Gauge size={18}/>},{id:'transactions',label:'Συναλλαγές',icon:<Repeat2 size={18}/>},{id:'review',label:'Έλεγχος',icon:<FileCheck2 size={18}/>},{id:'savings',label:'Αποταμίευση',icon:<PiggyBank size={18}/>},{id:'credit',label:'Κάρτες & Δόσεις',icon:<CreditCard size={18}/>},{id:'lending',label:'Δανεικά / Οφειλές',icon:<HandCoins size={18}/>},{id:'recurring',label:'Πάγια',icon:<ListChecks size={18}/>},{id:'reports',label:'Αναφορές',icon:<BarChart3 size={18}/>},{id:'settings',label:'Ρυθμίσεις',icon:<Settings size={18}/>},
];
const mobilePrimary = nav.slice(0,4);
const mobileMore = nav.slice(4);

export function AppShell({ page,onPage,onQuickAdd,saveState,filePath,reviewCount,motionMode='system',userEmail,onLogout,children }:{page:PageId;onPage:(p:PageId)=>void;onQuickAdd:()=>void;saveState:SaveState;filePath:string;reviewCount:number;motionMode?:'system'|'reduced'|'full';userEmail?:string|null;onLogout?:()=>void;children:ReactNode}){
 const systemReduced=useReducedMotion();const reduce=Boolean(systemReduced)||motionMode==='reduced';const saveLabel=saveState==='saving'?'Αποθήκευση…':saveState==='saved'?'Αποθηκεύτηκε':saveState==='conflict'?'Σύγκρουση έκδοσης':saveState==='error'?'Σφάλμα':'Φόρτωση…';
 const initial=(userEmail?.trim().charAt(0)||'M').toUpperCase();
 const[mobileMenuOpen,setMobileMenuOpen]=useState(false);
 const menuRef=useModalFocus<HTMLElement>(mobileMenuOpen,'button');
 const moreActive=mobileMore.some(item=>item.id===page);
 useEffect(()=>{if(!mobileMenuOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setMobileMenuOpen(false)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[mobileMenuOpen]);
 const selectPage=(next:PageId)=>{onPage(next);setMobileMenuOpen(false)};
 return <div className="app-shell"><a className="skip-link" href="#main-workspace">Μετάβαση στο κύριο περιεχόμενο</a><aside className="sidebar neo-raised"><div className="brand-block"><img src="/brand/icon-192.png" alt="RheomIQ" className="brand-icon"/><div><div className="brand-word">Rheom<span>IQ</span></div><small>Smart. Clear. In Control.</small></div></div><button type="button" className="primary-action" onClick={onQuickAdd}><Plus size={18}/> Γρήγορη προσθήκη</button><nav aria-label="Κύρια πλοήγηση">{nav.map(item=><button type="button" key={item.id} className={page===item.id?'active':''} aria-current={page===item.id?'page':undefined} onClick={()=>onPage(item.id)}>{item.icon}<span>{item.label}</span>{item.id==='review'&&reviewCount>0?<b className="count-badge" aria-label={`${reviewCount} προς έλεγχο`}>{reviewCount}</b>:null}</button>)}</nav><div className="file-panel neo-inset" aria-live="polite"><div className="file-line"><span className={`status-dot ${saveState}`} aria-hidden="true"/><b>{saveLabel}</b></div><small title={filePath}>{filePath||'Supabase/PostgreSQL'}</small></div><div className="sidebar-foot"><Landmark size={15}/><span>Supabase-backed finance ledger</span></div></aside><main><header className="topbar neo-flat"><div className="mobile-brand"><img src="/brand/icon-192.png" alt=""/><b>RheomIQ</b></div><div className="command-pill"><Menu size={16}/><span>Προσωπικά οικονομικά</span><kbd>Ctrl K</kbd></div><div className="top-actions"><button type="button" aria-label="Ανανέωση εφαρμογής" title="Ανανέωση εφαρμογής" onClick={()=>location.reload()}><RefreshCw size={17}/></button><span className="avatar" title={userEmail||'Owner'} aria-label={userEmail?`Συνδεδεμένος ως ${userEmail}`:'Ιδιοκτήτης'}>{initial}</span>{onLogout?<button type="button" aria-label="Αποσύνδεση" title="Αποσύνδεση" onClick={onLogout}><LogOut size={17}/></button>:null}</div></header><div className="workspace" id="main-workspace" tabIndex={-1}><AnimatePresence mode="wait"><motion.div key={page} initial={reduce?false:{opacity:0,y:7}} animate={{opacity:1,y:0}} exit={reduce?undefined:{opacity:0,y:-5}} transition={{duration:reduce?0:.18}}>{children}</motion.div></AnimatePresence></div>
 <AnimatePresence>{mobileMenuOpen?<motion.div className="mobile-more-backdrop" initial={reduce?false:{opacity:0}} animate={{opacity:1}} exit={reduce?undefined:{opacity:0}} onMouseDown={()=>setMobileMenuOpen(false)}><motion.section ref={menuRef} className="mobile-more-menu neo-raised" role="dialog" aria-modal="true" aria-labelledby="mobile-more-title" tabIndex={-1} initial={reduce?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={reduce?undefined:{opacity:0,y:12}} transition={{duration:reduce?0:.16}} onMouseDown={event=>event.stopPropagation()}><header><div><b id="mobile-more-title">Περισσότερα</b><small>Όλες οι ενότητες του RheomIQ</small></div><button type="button" aria-label="Κλείσιμο μενού" onClick={()=>setMobileMenuOpen(false)}><X size={17}/></button></header><nav aria-label="Περισσότερες ενότητες">{mobileMore.map(item=><button type="button" key={item.id} className={page===item.id?'active':''} aria-current={page===item.id?'page':undefined} onClick={()=>selectPage(item.id)}>{item.icon}<span>{item.label}</span></button>)}</nav></motion.section></motion.div>:null}</AnimatePresence>
 <nav className="mobile-nav neo-raised" aria-label="Κύρια πλοήγηση κινητού">{mobilePrimary.map(item=><button type="button" key={item.id} className={page===item.id?'active':''} aria-current={page===item.id?'page':undefined} onClick={()=>selectPage(item.id)}>{item.icon}<span>{item.label.split(' ')[0]}</span>{item.id==='review'&&reviewCount>0?<b className="mobile-count-badge" aria-label={`${reviewCount} προς έλεγχο`}>{reviewCount}</b>:null}</button>)}<button type="button" className={moreActive?'active':''} aria-label="Περισσότερες ενότητες" aria-expanded={mobileMenuOpen} aria-haspopup="dialog" onClick={()=>setMobileMenuOpen(open=>!open)}><Menu size={18}/><span>Περισσότερα</span></button></nav></main></div>;
}
