import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { BarChart3, Bell, CreditCard, FileCheck2, Gauge, HandCoins, Landmark, ListChecks, Menu, PiggyBank, Plus, RefreshCw, Repeat2, Settings } from 'lucide-react';
import type { ReactNode } from 'react';
import type { SaveState } from '../hooks/useFinance';

export type PageId = 'dashboard'|'transactions'|'review'|'savings'|'credit'|'lending'|'recurring'|'reports'|'settings';
const nav: Array<{id:PageId; label:string; icon:ReactNode}> = [
  {id:'dashboard',label:'Dashboard',icon:<Gauge size={18}/>},{id:'transactions',label:'Συναλλαγές',icon:<Repeat2 size={18}/>},{id:'review',label:'Έλεγχος',icon:<FileCheck2 size={18}/>},{id:'savings',label:'Αποταμίευση',icon:<PiggyBank size={18}/>},{id:'credit',label:'Κάρτες & Δόσεις',icon:<CreditCard size={18}/>},{id:'lending',label:'Δανεικά / Οφειλές',icon:<HandCoins size={18}/>},{id:'recurring',label:'Πάγια',icon:<ListChecks size={18}/>},{id:'reports',label:'Αναφορές',icon:<BarChart3 size={18}/>},{id:'settings',label:'Ρυθμίσεις',icon:<Settings size={18}/>},
];
export function AppShell({ page,onPage,onQuickAdd,saveState,filePath,reviewCount,motionMode='system',children }:{page:PageId;onPage:(p:PageId)=>void;onQuickAdd:()=>void;saveState:SaveState;filePath:string;reviewCount:number;motionMode?:'system'|'reduced'|'full';children:ReactNode}){
 const systemReduced=useReducedMotion();const reduce=systemReduced||motionMode==='reduced';const saveLabel=saveState==='saving'?'Αποθήκευση…':saveState==='saved'?'Αποθηκεύτηκε':saveState==='conflict'?'Σύγκρουση έκδοσης':saveState==='error'?'Σφάλμα':'Φόρτωση…';
 return <div className="app-shell"><aside className="sidebar neo-raised"><div className="brand-block"><img src="/brand/icon-192.png" alt="RheomIQ" className="brand-icon"/><div><div className="brand-word">Rheom<span>IQ</span></div><small>Smart. Clear. In Control.</small></div></div><button className="primary-action" onClick={onQuickAdd}><Plus size={18}/> Γρήγορη προσθήκη</button><nav>{nav.map(item=><button key={item.id} className={page===item.id?'active':''} onClick={()=>onPage(item.id)}>{item.icon}<span>{item.label}</span>{item.id==='review'&&reviewCount>0?<b className="count-badge">{reviewCount}</b>:null}</button>)}</nav><div className="file-panel neo-inset"><div className="file-line"><span className={`status-dot ${saveState}`}/><b>{saveLabel}</b></div><small title={filePath}>{filePath||'Supabase/PostgreSQL'}</small></div><div className="sidebar-foot"><Landmark size={15}/><span>Supabase-backed finance ledger</span></div></aside><main><header className="topbar neo-flat"><div className="mobile-brand"><img src="/brand/icon-192.png" alt=""/><b>RheomIQ</b></div><div className="command-pill"><Menu size={16}/><span>Προσωπικά οικονομικά</span><kbd>Ctrl K</kbd></div><div className="top-actions"><button aria-label="Ανανέωση"><RefreshCw size={17}/></button><button aria-label="Ειδοποιήσεις" className="has-dot"><Bell size={17}/></button><span className="avatar">M</span></div></header><div className="workspace"><AnimatePresence mode="wait"><motion.div key={page} initial={reduce?false:{opacity:0,y:7}} animate={{opacity:1,y:0}} exit={reduce?undefined:{opacity:0,y:-5}} transition={{duration:.18}}>{children}</motion.div></AnimatePresence></div><div className="mobile-nav neo-raised">{nav.slice(0,5).map(item=><button key={item.id} className={page===item.id?'active':''} onClick={()=>onPage(item.id)}>{item.icon}<span>{item.label.split(' ')[0]}</span></button>)}</div></main></div>;
}
