import { spawn, execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
const baseUrl=process.env.RHEOMIQ_QA_URL||'http://127.0.0.1:5173/qa.html';
const chrome=execFileSync('bash',['-lc','command -v google-chrome || command -v chromium || command -v chromium-browser'],{encoding:'utf8'}).trim();
if(!chrome)throw new Error('Chrome/Chromium is required for rendered frontend QA.');
const port=9222;const child=spawn(chrome,['--headless=new',`--remote-debugging-port=${port}`,'--remote-debugging-address=127.0.0.1','--user-data-dir=/tmp/rheomiq-qa-chrome','--no-sandbox','--disable-gpu','about:blank'],{stdio:'ignore'});const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
async function waitHttp(url){for(let i=0;i<60;i++){try{const r=await fetch(url);if(r.ok)return r}catch{}await sleep(250)}throw new Error(`Timed out waiting for ${url}`)}
class Cdp{constructor(url){this.url=url;this.id=0;this.pending=new Map()}async open(){await new Promise((resolve,reject)=>{this.ws=new WebSocket(this.url);this.ws.onopen=resolve;this.ws.onerror=reject;this.ws.onmessage=e=>{const m=JSON.parse(e.data);if(!m.id)return;const p=this.pending.get(m.id);if(!p)return;this.pending.delete(m.id);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result)}})}send(method,params={}){const id=++this.id;return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params}))})}async eval(expression){const r=await this.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text||'Runtime evaluation failed');return r.result.value}close(){this.ws?.close()}}
function assert(v,m){if(!v)throw new Error(`Frontend QA assertion failed: ${m}`)}const q=v=>JSON.stringify(v);
try{await waitHttp(`http://127.0.0.1:${port}/json/version`);const target=await fetch(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`,{method:'PUT'}).then(r=>r.json());const c=new Cdp(target.webSocketDebuggerUrl);await c.open();await c.send('Page.enable');await c.send('Runtime.enable');
const viewport=(width,height)=>c.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<=680});
const navigate=async(url)=>{await c.send('Page.navigate',{url});for(let i=0;i<80;i++){if(await c.eval(`document.readyState==='complete'&&Boolean(document.body?.innerText.trim())`))return;await sleep(100)}throw new Error(`Page not ready: ${url}`)};
const waitFor=async(expression,label)=>{for(let i=0;i<60;i++){if(await c.eval(expression))return;await sleep(100)}throw new Error(`Timed out waiting for ${label}`)};
const clickText=async(selector,text)=>{const ok=await c.eval(`(()=>{const e=[...document.querySelectorAll(${q(selector)})].find(x=>(x.textContent||'').trim().includes(${q(text)}));if(!e)return false;e.click();return true})()`);assert(ok,`missing clickable ${text}`)};
const audit=async(label)=>{const x=await c.eval(`(()=>{const v=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};const names=[...document.querySelectorAll('button')].filter(v).filter(b=>!((b.getAttribute('aria-label')||b.getAttribute('title')||b.textContent||'').trim())).map(b=>b.outerHTML.slice(0,120));const controls=[...document.querySelectorAll('input,select,textarea')].filter(v).filter(e=>!(e.getAttribute('aria-label')||e.getAttribute('aria-labelledby')||e.closest('label')||(e.id&&document.querySelector('label[for="'+CSS.escape(e.id)+'"]')))).map(e=>e.outerHTML.slice(0,120));return {names,controls,overflow:document.documentElement.scrollWidth-window.innerWidth}})()`);assert(!x.names.length,`${label}: unnamed buttons ${x.names.join(' | ')}`);assert(!x.controls.length,`${label}: unnamed controls ${x.controls.join(' | ')}`);assert(x.overflow<=1,`${label}: page overflow ${x.overflow}px`)};
const shot=async name=>{mkdirSync('/tmp/rheomiq-frontend-qa',{recursive:true});const r=await c.send('Page.captureScreenshot',{format:'png',fromSurface:true});writeFileSync(`/tmp/rheomiq-frontend-qa/${name}.png`,Buffer.from(r.data,'base64'))};
await viewport(430,800);await navigate(`${baseUrl}?screen=login`);await waitFor(`Boolean(document.querySelector('#login-title'))`,'login');await audit('login');
await viewport(1440,1000);await navigate(baseUrl);await waitFor(`Boolean(document.querySelector('#main-workspace h1'))`,'dashboard');await audit('dashboard');await shot('desktop-dashboard');
await clickText('button','Γρήγορη προσθήκη');await waitFor(`Boolean(document.querySelector('[role="dialog"][aria-labelledby="quick-add-title"]'))`,'Smart Entry');assert(await c.eval(`document.querySelector('[aria-labelledby="quick-add-title"]').contains(document.activeElement)`),'Smart Entry focus');await clickText('button','Καταχώριση');await waitFor(`Boolean(document.querySelector('.form-error[role="alert"]'))`,'validation alert');await audit('Smart Entry');await c.eval(`document.querySelector('button[aria-label="Κλείσιμο Smart Entry"]').click()`);await waitFor(`!document.querySelector('[aria-labelledby="quick-add-title"]')`,'Smart Entry close');await waitFor(`(document.activeElement?.textContent||'').includes('Γρήγορη προσθήκη')`,'Smart Entry focus restoration');
await clickText('.sidebar nav button','Συναλλαγές');await waitFor(`Boolean(document.querySelector('table.semantic-table'))`,'transactions');await audit('transactions');
await clickText('.sidebar nav button','Πάγια');await waitFor(`Boolean(document.querySelector('table.semantic-table.compact'))`,'recurring');await audit('recurring');assert(await c.eval(`(()=>{const b=[...document.querySelectorAll('button[aria-label^="Επεξεργασία"]')][0];if(!b)return false;b.click();return true})()`),'recurring edit');await waitFor(`Boolean(document.querySelector('[aria-labelledby="recurring-editor-title"]'))`,'recurring editor');assert(await c.eval(`document.querySelector('[aria-labelledby="recurring-editor-title"]').contains(document.activeElement)`),'recurring focus');await c.eval(`document.querySelector('button[aria-label="Κλείσιμο επεξεργασίας παγίου"]').click()`);
await clickText('.sidebar nav button','Κάρτες & Δόσεις');await waitFor(`Boolean(document.querySelector('.card-workspace'))`,'credit workspace');assert(await c.eval(`Boolean(document.querySelector('.credit-usage[role="progressbar"]'))`),'credit progress');await audit('credit');
await clickText('.sidebar nav button','Αναφορές');await waitFor(`Boolean(document.querySelector('.chart-alt'))`,'report alternative');await audit('reports');
await clickText('.sidebar nav button','Ρυθμίσεις');await waitFor(`Boolean([...document.querySelectorAll('label span')].find(x=>x.textContent.includes('Πιστωτικό όριο')))`,'credit setting');await audit('settings');
await c.eval(`document.querySelector('[data-qa-crash]').click()`);await waitFor(`Boolean(document.querySelector('.workspace-error[role="alert"]'))`,'error boundary');await clickText('.workspace-error button','Dashboard');await waitFor(`Boolean(document.querySelector('#main-workspace h1'))`,'error recovery');
await viewport(430,800);await navigate(`${baseUrl}?save=conflict`);await waitFor(`Boolean(document.querySelector('.persistence-notice.conflict[role="alert"]'))`,'conflict notice');assert(await c.eval(`document.querySelector('.persistence-notice.conflict').textContent.includes('Σύγκρουση έκδοσης')`),'conflict copy');await audit('conflict notice');await clickText('.persistence-notice button','Φόρτωση τελευταίας έκδοσης');await waitFor(`Boolean(document.querySelector('.persistence-notice.saved'))`,'conflict recovery');
for(const width of [320,375,430]){await viewport(width,812);await navigate(baseUrl);await waitFor(`Boolean(document.querySelector('.mobile-nav'))`,`mobile shell ${width}`);await audit(`mobile dashboard ${width}`);assert(await c.eval(`(()=>{const b=document.querySelector('button[aria-label="Περισσότερες ενότητες"]');if(!b)return false;b.click();return true})()`),`mobile More ${width}`);await waitFor(`Boolean(document.querySelector('[aria-labelledby="mobile-more-title"]'))`,`mobile More dialog ${width}`);assert(await c.eval(`document.querySelector('[aria-labelledby="mobile-more-title"]').contains(document.activeElement)`),`mobile More focus ${width}`);assert(await c.eval(`Number(getComputedStyle(document.querySelector('.mobile-more-backdrop')).zIndex)>Number(getComputedStyle(document.querySelector('.mobile-nav')).zIndex)`),`mobile modal backdrop must cover background nav at ${width}`);await clickText('.mobile-more-menu button','Πάγια');await waitFor(`Boolean(document.querySelector('table.semantic-table.compact'))`,`mobile recurring ${width}`);await audit(`mobile recurring ${width}`);if(width===375)await shot('mobile-recurring')}
await navigate(`${baseUrl}?motion=reduced`);await waitFor(`Boolean(document.querySelector('#main-workspace h1'))`,'reduced workspace');assert(await c.eval(`document.documentElement.dataset.motion==='reduced'`),'reduced-motion setting');await audit('reduced motion');
c.close();console.log('Rendered frontend QA passed.');}finally{child.kill('SIGTERM')}
