import { execFileSync, spawn } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';

const baseUrl=process.env.RHEOMIQ_QA_URL||'http://127.0.0.1:5173/qa.html';
const evidenceDir=process.env.MYFINHUB_UX_EVIDENCE_DIR||'/tmp/myfinhub-settings-tabs-qa';mkdirSync(evidenceDir,{recursive:true});
const configured=process.env.MYFINHUB_QA_USE_FALLBACK==='1'?process.env.MYFINHUB_QA_FALLBACK_BROWSER:process.env.MYFINHUB_QA_PRIMARY_BROWSER;
const chrome=configured||execFileSync('bash',['-lc','command -v google-chrome || command -v chromium || command -v chromium-browser'],{encoding:'utf8'}).trim();if(!chrome)throw new Error('Chrome/Chromium is required for Settings tabs QA.');
const port=9254;const profile='/tmp/myfinhub-settings-tabs-qa-chrome';const child=spawn(chrome,['--headless=new',`--remote-debugging-port=${port}`,'--remote-debugging-address=127.0.0.1',`--user-data-dir=${profile}`,'--no-sandbox','--disable-gpu','--disable-dev-shm-usage','about:blank'],{stdio:'ignore'});
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitHttp(url){for(let i=0;i<100;i++){try{const response=await fetch(url);if(response.ok)return}catch{}await sleep(150)}throw new Error(`Timed out waiting for ${url}`)}
class Cdp{constructor(url){this.url=url;this.id=0;this.pending=new Map();this.listeners=new Map()}async open(){await new Promise((resolve,reject)=>{this.ws=new WebSocket(this.url);this.ws.onopen=resolve;this.ws.onerror=reject;this.ws.onmessage=event=>{const message=JSON.parse(event.data);if(message.id){const pending=this.pending.get(message.id);if(!pending)return;this.pending.delete(message.id);message.error?pending.reject(new Error(message.error.message)):pending.resolve(message.result);return}for(const fn of this.listeners.get(message.method)||[])fn(message.params)}})}send(method,params={}){const id=++this.id;return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.ws.send(JSON.stringify({id,method,params}))})}on(method,fn){const list=this.listeners.get(method)||[];list.push(fn);this.listeners.set(method,list)}async call(functionDeclaration,args=[]){const root=await this.send('Runtime.evaluate',{expression:'globalThis'});const result=await this.send('Runtime.callFunctionOn',{objectId:root.result.objectId,functionDeclaration,arguments:args.map(value=>({value})),returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.text||'Runtime function call failed');return result.result.value}close(){this.ws?.close()}}
const assert=(value,message)=>{if(!value)throw new Error(`Settings tabs QA assertion failed: ${message}`)};
const tabs=[
  {id:'general',label:'Γενικά',selector:'.settings-general-grid'},
  {id:'profile',label:'Χρήστης & Πρόσβαση',selector:'.account-security-settings'},
  {id:'accounts',label:'Λογαριασμοί',selector:'.settings-accounts-tab'},
  {id:'budgets',label:'Προϋπολογισμοί & Στόχοι',selector:'.settings-budgets-only .budget-settings-panel'},
  {id:'categories',label:'Κατηγορίες',selector:'.settings-categories-only .category-icons-workspace'},
  {id:'icons',label:'Εικονίδια',selector:'.settings-icons-only .category-icons-workspace'},
  {id:'rules',label:'Κανόνες',selector:'.settings-rules-only .rule-settings-panel'},
  {id:'data',label:'Δεδομένα',selector:'.settings-data-tab'},
];
let c=null;
try{
  await waitHttp(`http://127.0.0.1:${port}/json/version`);const url=new URL(baseUrl);url.searchParams.set('page','settings');url.searchParams.set('state','settings-tabs');const target=await fetch(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(url.href)}`,{method:'PUT'}).then(response=>response.json());c=new Cdp(target.webSocketDebuggerUrl);await c.open();await c.send('Page.enable');await c.send('Runtime.enable');await c.send('Network.enable');
  const runtimeErrors=[];const failedRequests=[];c.on('Runtime.exceptionThrown',params=>runtimeErrors.push(params.exceptionDetails?.text||'runtime exception'));c.on('Network.loadingFailed',params=>{if(!params.canceled&&params.errorText!=='net::ERR_ABORTED')failedRequests.push(`${params.errorText||'network failure'} [${params.type||'unknown'}]`)});
  const viewport=(width,height)=>c.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<=680});
  const waitFor=async(fn,label,args=[])=>{for(let i=0;i<120;i++){if(await c.call(fn,args))return;await sleep(100)}throw new Error(`Timed out waiting for ${label}`)};
  const clickTab=async tab=>{const ok=await c.call("function(label){const node=[...document.querySelectorAll('.settings-tablist button')].find(item=>(item.textContent||'').trim()===label);if(!node||node.disabled)return false;node.click();node.scrollIntoView({block:'nearest',inline:'center'});return true}",[tab.label]);assert(ok,`tab ${tab.label} is enabled and clickable`);await waitFor("function(id,selector){const selected=[...document.querySelectorAll('.settings-tablist [role=tab]')].filter(node=>node.getAttribute('aria-selected')==='true');const panel=document.querySelector('.settings-tab-panel');const target=document.querySelector(selector);return selected.length===1&&selected[0].getAttribute('aria-controls')===`settings-panel-${id}`&&panel?.id===`settings-panel-${id}`&&Boolean(target&&target.getClientRects().length)}",`${tab.label} selected panel`,[tab.id,tab.selector]);await c.call("function(){document.querySelector('.settings-tab-panel')?.scrollIntoView({block:'start'});window.scrollBy(0,-132);return true}");await sleep(180)};
  const noPageOverflow=async label=>{const overflow=await c.call("function(){return Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)-innerWidth}");assert(overflow<=1,`${label} horizontal page overflow ${overflow}px`)};
  const prepareScreenshot=async()=>{const state=await c.call("function(){const active=document.activeElement;if(active instanceof HTMLElement)active.blur();window.scrollTo({top:0,left:0,behavior:'auto'});return {scrollY:window.scrollY}}");assert(Math.abs(state.scrollY)<=1,`screenshot capture scroll offset ${state.scrollY}px`);await sleep(120)};
  const screenshot=async(name)=>{await prepareScreenshot();await sleep(120);const shot=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(`${evidenceDir}/${name}.png`,Buffer.from(shot.data,'base64'))};
  const fullScreenshot=async(name)=>{await prepareScreenshot();const metrics=await c.send('Page.getLayoutMetrics');const width=Math.ceil(metrics.cssContentSize?.width||metrics.contentSize?.width||1440);const height=Math.ceil(metrics.cssContentSize?.height||metrics.contentSize?.height||1000);const shot=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width,height,scale:1}});writeFileSync(`${evidenceDir}/${name}.png`,Buffer.from(shot.data,'base64'))};
  const visibleTouchTargets=async label=>{const offenders=await c.call("function(){return [...document.querySelectorAll('#main-workspace button,#main-workspace summary,#main-workspace [role=combobox]')].filter(el=>{const r=el.getBoundingClientRect(),style=getComputedStyle(el);if(!r.width||!r.height||style.visibility==='hidden'||style.display==='none'||el.disabled)return false;return r.width<40||r.height<40}).map(el=>({name:el.getAttribute('aria-label')||(el.textContent||'').trim().slice(0,50),w:Math.round(el.getBoundingClientRect().width),h:Math.round(el.getBoundingClientRect().height)}))}");assert(offenders.length===0,`${label} touch targets below 40px: ${JSON.stringify(offenders.slice(0,8))}`)};

  await waitFor("function(){return Boolean(document.querySelector('.settings-tablist'))}",'Settings tabs');
  const architecture=await c.call("function(){const tabs=[...document.querySelectorAll('.settings-tablist [role=tab]')];return {count:tabs.length,disabled:tabs.filter(tab=>tab.disabled).length,labels:tabs.map(tab=>(tab.textContent||'').trim())}}");assert(architecture.count===tabs.length,`expected ${tabs.length} tabs, got ${architecture.count}`);assert(architecture.disabled===0,'all Settings tabs are enabled');assert(JSON.stringify(architecture.labels)===JSON.stringify(tabs.map(tab=>tab.label)),'Settings tab order changed');

  for(const mode of [{name:'desktop',width:1440,height:1000},{name:'mobile',width:375,height:812}]){
    await viewport(mode.width,mode.height);
    for(const tab of tabs){
      await clickTab(tab);await noPageOverflow(`${mode.name} ${tab.label}`);
      if(tab.id==='profile'){
        await waitFor("function(){return document.querySelectorAll('.device-access-row').length>=2}",'realistic connected-device approval fixture');
        const profile=await c.call("function(){const root=document.querySelector('.account-security-settings');const buttons=[...(root?.querySelectorAll('button')||[])];const pinInputs=[...(root?.querySelectorAll('input[inputmode=\"numeric\"]')||[])];return {text:root?.textContent||'',inputs:root?.querySelectorAll('input').length||0,emailAction:buttons.some(button=>(button.textContent||'').includes('Αλλαγή email')&&!button.disabled),passwordAction:buttons.some(button=>(button.textContent||'').includes('Αλλαγή κωδικού')&&!button.disabled),pinAction:buttons.some(button=>(button.textContent||'').includes('Αλλαγή PIN')&&!button.disabled),lockNow:buttons.some(button=>(button.textContent||'').includes('Κλείδωμα τώρα')&&!button.disabled),devicePanel:Boolean(root?.querySelector('.device-access-settings')),deviceRows:root?.querySelectorAll('.device-access-row').length||0,pinDots:root?.querySelectorAll('.account-security-pin-dots i').length||0,pinInputs:pinInputs.filter(input=>input.maxLength===4).length,currentPin:Boolean(root?.querySelector('[aria-label=\"Τρέχον 4ψήφιο PIN\"]')),ownedIdle:Boolean(root?.querySelector('.account-security-idle-select.owned-select-shell')),idleValue:root?.querySelector('[aria-label=\"Χρόνος αυτόματου κλειδώματος\"]')?.value||''}}");assert(profile.text.includes('Χρήστης & Πρόσβαση'),'User access tab has distinct access identity');assert(profile.text.includes('Τρέχον email:'),'Current email stays inside the email change function');assert(profile.text.includes('Αλλαγή email'),'User access exposes real email change');assert(profile.text.includes('Αλλαγή κωδικού'),'User access exposes real password change');assert(profile.text.includes('Συνδεδεμένες συσκευές'),'User access exposes connected devices');assert(profile.text.includes('Android · Pixel'),'User access renders Android session foundation');assert(!profile.text.includes('Email πρόσβασης'),'User access removes redundant email summary');assert(profile.inputs>=6,'User access renders the compact account-security inputs');assert(profile.pinInputs===2&&!profile.currentPin,'PIN change uses only new and confirmation four-digit inputs');assert(profile.emailAction&&profile.passwordAction,'User access auth actions are actionable');assert(profile.pinAction&&profile.lockNow,'Four-digit PIN controls are actionable in the desktop approval fixture');assert(profile.devicePanel&&profile.deviceRows>=2,'Connected-device panel renders current and remote sessions');assert(profile.pinDots>=12,'PIN UI renders four-dot indicators');assert(profile.ownedIdle&&profile.idleValue==='5 λεπτά','Default idle lock uses the owned modern selector at five minutes');
      }
      if(tab.id==='accounts'){
        const accountState=await c.call("function(){const root=document.querySelector('.account-management-settings');const text=root?.textContent||'';const buttons=[...(root?.querySelectorAll('button')||[])];return {text,rows:root?.querySelectorAll('.account-management-row').length||0,create:buttons.some(button=>(button.textContent||'').includes('Νέος λογαριασμός')),refresh:buttons.some(button=>(button.textContent||'').includes('Ανανέωση')||button.getAttribute('title')==='Ανανέωση'),defaults:root?.querySelectorAll('.account-management-default-grid [role=combobox]').length||0,badges:root?.querySelectorAll('.account-management-default-badge').length||0}}");assert(accountState.text.includes('Προεπιλεγμένοι λογαριασμοί'),'Accounts exposes everyday defaults first');assert(accountState.text.includes('Οι λογαριασμοί μου'),'Accounts exposes the compact account list');assert(accountState.text.includes('Καβάτζα')&&accountState.text.includes('εκτός καθημερινής χρήσης'),'Accounts renders the reserve cash account as a simple row');assert(accountState.rows>=5,'Accounts renders representative account rows');assert(accountState.defaults===3,'Accounts keeps three owned default selectors');assert(accountState.badges>=3,'Accounts renders default-role badges on the configured account');assert(accountState.create,'Accounts exposes real create-account action');assert(!accountState.refresh,'Accounts does not expose the rejected refresh action');
      }
      if(tab.id==='budgets')assert(await c.call("function(){return !document.querySelector('.settings-budgets-only .rule-settings-panel')}") ,'Budgets does not render Rules UI');
      if(tab.id==='categories')assert(await c.call("function(){return ![...document.querySelectorAll('.settings-categories-only .taxonomy-icon-disclosure')].some(node=>node.getClientRects().length)}") ,'Categories keeps icon pickers out of the visible taxonomy workspace');
      if(tab.id==='icons'){
        const iconState=await c.call("function(){const root=document.querySelector('.settings-icons-only');return {picker:[...(root?.querySelectorAll('.taxonomy-icon-disclosure')||[])].some(node=>node.getClientRects().length>0),management:[...(root?.querySelectorAll('.taxonomy-add-row,.taxonomy-row-actions')||[])].some(node=>node.getClientRects().length>0)}}");assert(iconState.picker,'Icons exposes real icon preference controls');assert(!iconState.management,'Icons does not duplicate taxonomy mutation controls');
      }
      if(tab.id==='rules'){
        const ruleState=await c.call("function(){const details=document.querySelector('.settings-rules-only .rule-settings-panel');return {open:Boolean(details?.open),budget:Boolean(document.querySelector('.settings-rules-only .budget-settings-panel')),builder:Boolean(document.querySelector('.settings-rules-only .rule-editor-grid'))}}");assert(ruleState.open,'Rules details is semantically open');assert(!ruleState.budget,'Rules does not render budget editor');assert(ruleState.builder,'Rules renders the existing automation builder');
      }
      if(mode.name==='mobile')await visibleTouchTargets(`${mode.name} ${tab.label}`);
      await screenshot(`settings-${tab.id}-${mode.name}`);
      if(tab.id==='budgets'){
        await screenshot(`settings-budgets-category-${mode.name}`);
        const overallOpened=await c.call("function(){const label=[...document.querySelectorAll('.settings-budgets-only .budget-editor-grid label')].find(node=>(node.querySelector(':scope > span')?.textContent||'').trim()==='Τύπος ορίου');const input=label?.querySelector('[role=\"combobox\"]');if(!input)return false;input.click();return true}");assert(overallOpened,`Budget scope selector opens on ${mode.name}`);
        await waitFor("function(){return Boolean(document.querySelector('.owned-select-popover [role=\"listbox\"]'))}",`budget scope options ${mode.name}`);
        const overallSelected=await c.call("function(){const option=[...document.querySelectorAll('.owned-select-popover [role=\"option\"]')].find(node=>(node.textContent||'').includes('Συνολικό discretionary'));if(!option)return false;option.click();return true}");assert(overallSelected,`Overall budget scope can be selected on ${mode.name}`);
        await waitFor("function(){const root=document.querySelector('.settings-budgets-only .budget-editor-grid');const labels=[...(root?.querySelectorAll('label>span')||[])].map(node=>(node.textContent||'').trim());const scope=[...(root?.querySelectorAll('[role=\"combobox\"]')||[])][0];return !labels.includes('Κατηγορία')&&scope?.value==='Συνολικό discretionary'}",`overall budget state ${mode.name}`);
        await screenshot(`settings-budgets-overall-${mode.name}`);
        const categoryOpened=await c.call("function(){const label=[...document.querySelectorAll('.settings-budgets-only .budget-editor-grid label')].find(node=>(node.querySelector(':scope > span')?.textContent||'').trim()==='Τύπος ορίου');const input=label?.querySelector('[role=\"combobox\"]');if(!input)return false;input.click();return true}");assert(categoryOpened,`Budget scope selector reopens on ${mode.name}`);
        await waitFor("function(){return Boolean(document.querySelector('.owned-select-popover [role=\"listbox\"]'))}",`budget category scope options ${mode.name}`);
        const categorySelected=await c.call("function(){const option=[...document.querySelectorAll('.owned-select-popover [role=\"option\"]')].find(node=>(node.textContent||'').trim()==='Κατηγορία');if(!option)return false;option.click();return true}");assert(categorySelected,`Category budget scope can be restored on ${mode.name}`);
        await waitFor("function(){const root=document.querySelector('.settings-budgets-only .budget-editor-grid');const labels=[...(root?.querySelectorAll('label>span')||[])].map(node=>(node.textContent||'').trim());return labels.includes('Κατηγορία')}",`category budget state restored ${mode.name}`);
      }
      if(mode.name==='desktop'&&tab.id==='profile')await fullScreenshot('settings-profile-desktop-full');
      if(mode.name==='desktop'&&tab.id==='accounts'){
        await fullScreenshot('settings-accounts-desktop-full');

        const defaultDropdownOpened=await c.call("function(){const input=document.querySelector('.account-management-default-grid input[aria-label=\"Προεπιλεγμένος λογαριασμός εξόδων\"]');if(!input)return false;input.click();return true}");assert(defaultDropdownOpened,'Default account dropdown opens');
        await waitFor("function(){return Boolean(document.querySelector('.owned-select-popover[aria-label=\"Προεπιλεγμένος λογαριασμός εξόδων\"]'))}",'default account dropdown');
        await screenshot('settings-accounts-default-dropdown-desktop');
        const defaultDropdownClosed=await c.call("function(){const popover=document.querySelector('.owned-select-popover[aria-label=\"Προεπιλεγμένος λογαριασμός εξόδων\"]');const button=popover?.querySelector('button[aria-label=\"Κλείσιμο επιλογών\"]');if(!button)return false;button.click();return true}");assert(defaultDropdownClosed,'Default account dropdown closes');
        await waitFor("function(){return !document.querySelector('.owned-select-popover[aria-label=\"Προεπιλεγμένος λογαριασμός εξόδων\"]')}",'default account dropdown close');

        const opened=await c.call("function(){const button=[...document.querySelectorAll('.account-management-settings button')].find(node=>(node.textContent||'').includes('Νέος λογαριασμός'));if(!button)return false;button.click();return true}");assert(opened,'New account modal opens');
        await waitFor("function(){return Boolean(document.querySelector('.account-management-modal.is-new'))}",'new account modal');
        await screenshot('settings-accounts-new-bank-empty-desktop');

        const providerDropdownOpened=await c.call("function(){const input=document.querySelector('.account-management-modal.is-new input[aria-label=\"Τράπεζα ή πάροχος\"]');if(!input)return false;input.click();return true}");assert(providerDropdownOpened,'Bank provider dropdown opens');
        await waitFor("function(){return Boolean(document.querySelector('.owned-select-popover[aria-label=\"Τράπεζα ή πάροχος\"]'))}",'bank provider dropdown');
        await screenshot('settings-accounts-new-bank-provider-dropdown-desktop');
        const providerSelected=await c.call("function(){const option=[...document.querySelectorAll('.owned-select-popover[aria-label=\"Τράπεζα ή πάροχος\"] [role=\"option\"]')].find(node=>(node.textContent||'').includes('Πειραιώς'));if(!option)return false;option.click();return true}");assert(providerSelected,'Piraeus can be selected as bank provider');
        await waitFor("function(){return Boolean(document.querySelector('.account-management-provider-preview'))}",'selected bank provider preview');
        await screenshot('settings-accounts-new-bank-selected-desktop');

        const cash=await c.call("function(){const modal=document.querySelector('.account-management-modal');const button=[...(modal?.querySelectorAll('button')||[])].find(node=>(node.textContent||'').trim()==='Μετρητά');if(!button)return false;button.click();return true}");assert(cash,'New account modal can select cash');
        const cashChoices=await c.call("function(){const root=document.querySelector('.account-management-cash-types');const labels=[...(root?.querySelectorAll('button')||[])].map(node=>(node.textContent||'').trim());return labels}");assert(JSON.stringify(cashChoices)===JSON.stringify(['Μετρητά','Καβάτζα']),'Cash creation exposes only daily cash and reserve');
        await screenshot('settings-accounts-new-cash-daily-desktop');
        const reserve=await c.call("function(){const modal=document.querySelector('.account-management-modal');const button=[...(modal?.querySelectorAll('button')||[])].find(node=>(node.textContent||'').trim()==='Καβάτζα');if(!button)return false;button.click();return true}");assert(reserve,'Cash modal exposes reserve role only after cash is selected');
        const modalState=await c.call("function(){const modal=document.querySelector('.account-management-modal');const text=modal?.textContent||'';return {text,bankFields:text.includes('Τράπεζα / πάροχος')||text.includes('IBAN'),visibility:text.includes('Εμφάνιση στις γρήγορες επιλογές'),other:text.includes('Άλλο')}}");assert(modalState.text.includes('Νέος λογαριασμός')&&modalState.text.includes('Τύπος μετρητών'),'New account modal reveals cash-specific choices');assert(!modalState.bankFields,'Cash state hides bank-only fields');assert(!modalState.visibility,'Cash role implies quick-choice behavior without a redundant visibility control');assert(!modalState.other,'Cash state no longer exposes Other');
        await screenshot('settings-accounts-new-modal-desktop');
        const closed=await c.call("function(){const modal=document.querySelector('.account-management-modal');const button=modal?.querySelector('button[aria-label=\"Κλείσιμο\"]');if(!button)return false;button.click();return true}");assert(closed,'New account modal closes');
        await waitFor("function(){return !document.querySelector('.account-management-modal')}",'new account modal close');

        const editOpened=await c.call("function(){const button=document.querySelector('.account-management-row .account-management-edit');if(!button)return false;button.click();return true}");assert(editOpened,'Account edit modal opens');
        await waitFor("function(){return Boolean(document.querySelector('.account-management-modal.is-edit'))}",'account edit modal');
        const editState=await c.call("function(){const modal=document.querySelector('.account-management-modal.is-edit');const text=modal?.textContent||'';return {text,checkboxes:modal?.querySelectorAll('.account-management-edit-defaults input[type=checkbox]').length||0,typeSelector:text.includes('Τύπος λογαριασμού'),providerField:text.includes('Τράπεζα / πάροχος'),iban:text.includes('IBAN'),deleteButton:Boolean(modal?.querySelector('.account-management-delete-modal'))}}");assert(editState.text.includes('Επεξεργασία λογαριασμού'),'Edit modal has the approved edit identity');assert(editState.text.includes('Προεπιλογές')&&editState.checkboxes===3,'Edit modal exposes the three default-account choices');assert(!editState.typeSelector,'Edit modal does not repeat the creation-only account type selector');assert(!editState.providerField&&editState.iban,'Edit modal stays compact while retaining IBAN editing');assert(editState.deleteButton,'Edit modal exposes the protected delete action');
        await screenshot('settings-accounts-edit-modal-desktop');
        const editClosed=await c.call("function(){const modal=document.querySelector('.account-management-modal.is-edit');const button=modal?.querySelector('button[aria-label=\"Κλείσιμο\"]');if(!button)return false;button.click();return true}");assert(editClosed,'Account edit modal closes');
        await waitFor("function(){return !document.querySelector('.account-management-modal')}",'account edit modal close');
      }
    }
  }
  assert(runtimeErrors.length===0,`runtime exceptions: ${runtimeErrors.join(' | ')}`);assert(failedRequests.length===0,`network loading failures: ${failedRequests.join(' | ')}`);c.close();console.log('All Settings tabs rendered QA passed on desktop and mobile.');
}finally{c?.close();child.kill('SIGTERM')}