import type { FinanceData } from './types.js';

export function qaFinanceData(): FinanceData {
  return {
    app:'RheomIQ',schemaVersion:3,updatedAt:'2026-08-17T12:00:00.000Z',
    seed:{accounts:[{id:'piraeus-payroll',name:'Μισθοδοσίας',short:'ΜΙΣ',kind:'bank'},{id:'piraeus-savings',name:'Ταμιευτηρίου',short:'ΤΑΜ',kind:'savings',excludeFromAvailable:true},{id:'cash',name:'Μετρητά',short:'CASH',kind:'cash'}],months:['2026-08'],transactions:[{id:'legacy-1',date:'2026-08-02',type:'expense',accountId:'piraeus-payroll',amount:24.5,note:'Supermarket',category:'Τρόφιμα'},{id:'legacy-2',date:'2026-08-03',type:'income',accountId:'piraeus-payroll',amount:1200,note:'Μισθός',category:'Μισθός'}],snapshots:[{date:'2026-08-01',balances:{'piraeus-payroll':900,'piraeus-savings':1500,cash:80}}],recurring:[{id:'rec-1',name:'Internet',amount:32,day:12,accountId:'piraeus-payroll',category:'Σταθερά έξοδα',active:true,source:'qa'}],subscriptions:[],loans:[{id:'loan-1',name:'Laptop',total:600,installment:100,installments:6,paidCount:2,provider:'QA Store',schedule:[],source:'qa',accountingMode:'expense-per-installment'}],lending:[{person:'Νίκος',entries:[{date:'2026-08-04',lent:50,repaid:0}],outstanding:50}],stats:{transactions:2}},
    state:{customTransactions:[],overrides:{},deleted:[],recurringCustom:[{id:'rec-2',name:'Cloud',amount:8,day:20,accountId:'piraeus-payroll',category:'Σταθερά έξοδα',active:true,source:'qa'}],recurringOverrides:{},loanExtra:{},loanOverrides:{},customLoans:[],lendingCustom:[],settings:{excludedFromAvailable:['piraeus-savings'],accountNames:{'piraeus-payroll':'Κύριος λογαριασμός'},expenseCategories:['Τρόφιμα','Μετακινήσεις','Σταθερά έξοδα','Άλλο'],incomeCategories:['Μισθός','Άλλο'],customPresets:[],pinnedPresets:[],defaultExpenseAccount:'piraeus-payroll',defaultIncomeAccount:'piraeus-payroll',defaultLoanAccount:'piraeus-payroll',monthlyBudget:1000,savingsTargetRate:.2,creditLimit:2000,motion:'system'},events:[{id:'evt-expense',date:'2026-08-05',kind:'expense',amount:18,note:'Καφές & φαγητό',category:'Τρόφιμα',accountId:'piraeus-payroll',legs:[{accountId:'piraeus-payroll',amount:-18}],source:'user',createdAt:'2026-08-05T08:00:00.000Z',updatedAt:'2026-08-05T08:00:00.000Z'},{id:'evt-card',date:'2026-08-06',kind:'card_purchase',amount:120,note:'Ακουστικά',category:'Άλλο',legs:[{accountId:'credit-card',amount:-120}],creditDelta:-120,source:'user',createdAt:'2026-08-06T08:00:00.000Z',updatedAt:'2026-08-06T08:00:00.000Z'},{id:'evt-saving',date:'2026-08-07',kind:'saving_cash_offset',amount:100,note:'Αποταμίευση',fromAccountId:'piraeus-payroll',toAccountId:'piraeus-savings',legs:[{accountId:'piraeus-payroll',amount:-100},{accountId:'piraeus-savings',amount:100}],savingAmount:100,source:'user',createdAt:'2026-08-07T08:00:00.000Z',updatedAt:'2026-08-07T08:00:00.000Z'}],reviewDecisions:{}},
  };
}
