-- Private Android release channel for the owner's sideloaded MyFinHub app.
-- Runtime reads use the owner's authenticated AAL2 JWT; no service-role key is required online.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'android-releases',
  'android-releases',
  false,
  314572800,
  array['application/vnd.android.package-archive', 'application/octet-stream']::text[]
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.rheomiq_android_releases (
  id bigint generated by default as identity primary key,
  version_code integer not null unique check (version_code > 0),
  version_name text not null check (char_length(version_name) between 1 and 64),
  storage_path text not null unique check (
    char_length(storage_path) between 1 and 240
    and storage_path !~ '(^/|\.\.|\\|[?#])'
  ),
  sha256 text not null check (sha256 ~ '^[0-9a-fA-F]{64}$'),
  size_bytes bigint not null check (size_bytes between 1 and 314572800),
  mandatory boolean not null default false,
  notes text not null default '' check (char_length(notes) <= 8000),
  published_at timestamptz not null default now(),
  enabled boolean not null default true
);

alter table public.rheomiq_android_releases enable row level security;
alter table public.rheomiq_android_releases force row level security;

revoke all on table public.rheomiq_android_releases from anon, authenticated;
grant select on table public.rheomiq_android_releases to authenticated;

drop policy if exists rheomiq_android_releases_owner_aal2_select on public.rheomiq_android_releases;
create policy rheomiq_android_releases_owner_aal2_select
on public.rheomiq_android_releases
for select
to authenticated
using (
  coalesce((select auth.jwt()) ->> 'aal', '') = 'aal2'
  and exists (
    select 1
    from public.rheomiq_owner owner_row
    where owner_row.user_id = (select auth.uid())
  )
);

drop policy if exists rheomiq_android_release_objects_owner_aal2_select on storage.objects;
create policy rheomiq_android_release_objects_owner_aal2_select
on storage.objects
for select
to authenticated
using (
  bucket_id = 'android-releases'
  and coalesce((select auth.jwt()) ->> 'aal', '') = 'aal2'
  and exists (
    select 1
    from public.rheomiq_owner owner_row
    where owner_row.user_id = (select auth.uid())
  )
);

comment on table public.rheomiq_android_releases is
  'Owner-only metadata for private production-signed Android APK releases. Upload/publish is an offline signing-handoff operation.';
